const characters = {
	jimiaojimu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dczouyi", "dcyanxi"],
		names: "吉|邈-吉|穆",
	},
	dc_zhugejun: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcgengdu", "dcgumai"],
	},
	dc_xiangchong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcguying", "dcmuzhen"],
	},
	dc_xiahouxuan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcboxuan", "dcyizheng", "dcguilin"],
		names: "夏侯|玄",
	},
	houcheng: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["dcxianniang"],
	},
	dc_zhangyì: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcmurui", "dcaoren"],
	},
	panghong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcpingzhi", "dcgangjian"],
	},
	yue_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcguyin", "dcpinglu"],
	},
	yue_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dctanban", "dcdiou"],
		names: "null|null",
	},
	dc_huangwudie: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["dcshuangrui", "dcfuxie"],
	},
	dc_mateng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "dcxiongyi"],
		dieAudios: ["mateng"],
	},
	dc_sp_zhurong: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["dcremanhou", "dcretanluan"],
		names: "null|null",
	},
	yue_zhugeguo: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dcxidi", "dcchengyan"],
		names: "诸葛|果",
	},
	yue_zoushi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcyunzheng", "dchuoxin"],
		names: "邹|null",
	},
	yue_miheng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcjigu", "dcsirui"],
	},
	dc_lifeng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dctunchu", "dcshuliang"],
	},
	wupu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcduanti", "dcshicao"],
	},
	zangba: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["rehengjiang"],
	},
	gongsunxiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcgangu", "dckuizhen"],
		names: "公孙|修",
	},
	dc_liuli: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcfuli", "dcdehua"],
	},
	yue_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcqiqin", "dczixi"],
		names: "桥|null",
	},
	dc_kongrong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dckrmingshi", "lirang"],
		dieAudios: ["kongrong"],
	},
	dc_sp_menghuo: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcmanwang"],
		dieAudios: ["sp_menghuo"],
	},
	yue_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcqiqin", "dcweiwan"],
		names: "桥|null",
	},
	dc_dongzhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcyijia", "dcdingji"],
	},
	kuaiqi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcliangxiu", "dcxunjie"],
	},
	yue_caiyong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcjiaowei", "dcfeibai"],
	},
	pangshanmin: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dccaisi", "dczhuoli"],
	},
	dc_jiachong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcbeini", "dcshizong"],
		groupBorder: "jin",
	},
	dc_sunchen: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dczigu", "dczuowei"],
	},
	dc_zhangmancheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dclvecheng", "dczhongji"],
	},
	yue_zhoufei: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dclingkong", "dcxianshu"],
		names: "周|null",
	},
	dc_wuban: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcyouzhan"],
		clans: ["陈留吴氏"],
	},
	yue_caiwenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcshuangjia", "dcbeifen"],
	},
	liuchongluojun: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcminze", "dcjini"],
		names: "刘|宠-骆|俊",
	},
	yuechen: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcporui", "dcgonghu"],
	},
	zhangkai: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcxiangshu"],
	},
	gaoxiang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcchiying"],
	},
	yuanyin: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcmoshou", "dcyunjiu"],
	},
	dongwan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcshengdu", "dcjieling"],
	},
	zhangchu: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcjizhong", "dcrihui", "dcguangshi"],
	},
	peiyuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcmoyu"],
	},
	mengjie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcyinlu", "dcyouqi"],
	},
	dc_huojun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcgue", "dcsigong"],
	},
	dc_sunhanhua: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dchuiling", "dcchongxu"],
	},
	dc_sunziliufang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcqinshen", "dcweidang"],
		names: "孙|资-刘|放",
	},
	yuantanyuanxiyuanshang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcneifa"],
		names: "袁|谭-袁|尚-袁|熙",
	},
	qiaorui: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcaishou", "dcsaowei"],
	},
	xianglang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dckanji", "dcqianzheng"],
	},
	qinlang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dchaochong", "dcjinjin"],
	},
	furongfuqian: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 6,
		skills: ["dcxuewei", "dcyuguan"],
		names: "傅|肜-傅|佥",
	},
	zhenghun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcqiangzhi", "dcpitian"],
	},
	dc_zhaotongzhaoguang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["yizan_use", "dcqingren", "dclongyuan"],
		dieAudios: ["zhaotongzhaoguang"],
		names: "赵|统-赵|广",
	},
	dc_huanghao: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcqinqing", "huisheng", "dccunwei"],
	},
	liupi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcjuying"],
	},
	dc_sp_jiaxu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["zhenlue", "dcjianshu", "dcyongdi"],
		dieAudios: ["sp_jiaxu"],
	},
	leibo: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcsilve", "dcshuaijie"],
	},
	gongsundu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dczhenze", "dcanliao"],
		names: "公孙|度",
	},
	panghui: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["dcyiyong", "dcsuchou"],
	},
	dc_yuejiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dccuijin"],
	},
	chenjiao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcxieshou", "dcqingyan", "dcqizi"],
	},
	wanglie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcchongwang", "dchuagui"],
	},
	chengui: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcyingtu", "dccongshi"],
	},
	dc_huangquan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcquanjian", "dctujue"],
	},
	yinfuren: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcyingyu", "dcyongbi"],
		names: "尹|null",
	},
	dc_lvkuanglvxiang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcshuhe", "dcliehou"],
		names: "吕|旷-吕|翔",
	},
	guanhai: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["suoliang", "qinbao"],
	},
	huzhao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["midu", "xianwang"],
	},
	dc_liuba: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dczhubi", "dcliuzhuan"],
	},
	zhangxun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["suizheng"],
	},
	zongyu: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zyqiao", "chengshang"],
	},
	dc_jiling: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcshuangren"],
		dieAudios: ["jiling"],
	},
	dc_yanghu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcdeshao", "dcmingfa"],
		groupBorder: "jin",
	},
	caimaozhangyun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["lianzhou", "jinglan"],
		names: "蔡|瑁-张|允",
	},
	tenggongzhu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["xingchong", "liunian"],
		names: "孙|null",
	},
	dc_huangchengyan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcjiezhen", "dczecai", "dcyinshi"],
	},
	dc_gaolan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xizhen"],
	},
	guanning: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 7,
		skills: ["dunshi"],
	},
	dc_jiben: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xunli", "zhishi", "lieyi"],
	},
	mamidi: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 6,
		skills: ["bingjie", "zhengding"],
	},
	re_dengzhi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jianliang", "weimeng"],
	},
	fengxi: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["yusui", "boyan"],
	},
	re_miheng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rekuangcai", "reshejian"],
	},
	re_chendeng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["refuyuan", "reyingshui", "rewangzu"],
	},
	wanniangongzhu: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["zhenge", "xinghan"],
		names: "刘|null",
	},
	re_xunchen: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["refenglve", "anyong"],
		clans: ["颍川荀氏"],
	},
	re_kanze: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["xiashu", "rekuanshi"],
		dieAudios: ["kanze"],
	},
	lvlingqi: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["guowu", "zhuangrong"],
	},
	zhanghu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["cuijian", "zhtongyuan"],
	},
	luyusheng: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["zhente", "zhiwei"],
		clans: ["吴郡陆氏"],
	},
	huaxin: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["spwanggui", "xibing"],
	},
	mengyou: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["manyi", "dcmanzhi"],
	},
	liuyong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zhuning", "fengxiang"],
	},
	dc_sunru: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["xiecui", "youxu"],
	},
	xiahoulingnv: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["fuping", "weilie"],
		names: "夏侯|令女",
	},
	zhangyao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["yuanyu", "xiyan"],
	},
	tengyin: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["chenjian", "xixiu"],
	},
	zhangxuan: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["tongli", "shezang"],
	},
	wangtao: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["huguan", "yaopei"],
	},
	wangyue: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["huguan", "mingluan"],
	},
	zhaoyan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jinhui", "qingman"],
	},
	heyan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yachai", "qingtan"],
	},
	re_sunluyu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["remeibu", "remumu"],
		dieAudios: ["sunluyu"],
	},
	re_dongbai: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["relianzhu", "rexiahui"],
		dieAudios: ["dongbai"],
	},
	zhoushan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcmiyun", "dcdanying"],
	},
	dc_caiyang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcxunji", "dcjiaofeng"],
	},
	xiahoujie: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["liedan", "zhuangdan"],
		names: "夏侯|杰",
	},
	caoxing: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["cxliushi", "zhanwan"],
	},
	re_chunyuqiong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["recangchu", "reliangying", "reshishou"],
		names: "淳于|琼",
	},
	xingdaorong: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 6,
		skills: ["xuxie"],
	},
	re_panfeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinkuangfu"],
	},
	jiangfei: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["reshengxi", "dcshoucheng"],
		names: "蒋|琬-费|祎",
	},
};

export default characters;
