const characters = {
	yj_zhanghuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcyiju", "dcshuguo"],
	},
	yj_zhangyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcqiaolve", "dchanjie"],
	},
	wufu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dczhonge", "dcjuekai"],
	},
	yj_sb_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xianmou", "lunshi"],
	},
	xunyuxunyou: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["zhinang", "gouzhu"],
		names: "荀|彧-荀|攸",
	},
	xiahoumao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["tongwei", "cuguo"],
		names: "夏侯|楙",
	},
	chenshi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qingbei"],
	},
	sunli: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["kangli"],
	},
	feiyao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zhenfeng"],
	},
	wuanguo: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["diezhang", "duanwan"],
	},
	hanlong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["duwang", "cibei"],
	},
	yj_qiaozhou: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["shiming", "jiangxi"],
	},
	yj_sufei: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["shuojian"],
	},
	liwan: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["liandui", "biejun"],
	},
	zhugeshang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["sangu", "yizu"],
		names: "诸葛|尚",
	},
	kebineng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["kousheng"],
		names: "科比|罐头",
	},
	lukai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["lkbushi", "lkzhongzhuang"],
		clans: ["吴郡陆氏"],
	},
	linghuyu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xvzhi"],
		names: "令狐|愚",
	},
	yj_simafu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["beiyu", "duchi"],
		names: "司马|孚",
		groupBorder: "jin",
	},
	yj_xuangongzhu: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["yjqimei", "yjzhuiji"],
		names: "司马|null",
	},
	xukun: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["fazhu"],
	},
	yj_zhangliao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["weifeng"],
	},
	yj_zhanghe: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinzhilve"],
	},
	yj_xuhuang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinxhzhiyan"],
	},
	yj_ganning: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["gnjinfan", "gnsheque"],
	},
	yj_huangzhong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["spshidi", "spyishi", "spqishe"],
	},
	yj_weiyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 1,
		skills: ["mbguli", "mbaosi"],
	},
	yj_zhoubuyi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbhuiyao", "mbquesong"],
	},
	mp_wangrong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mpjianlin", "mpsixiao"],
	},
	mp_liuling: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["mpjiusong", "mpmaotao", "mpbishi"],
		doubleGroup: ["wei", "qun", "jin"],
	},
	mp_xiangxiu: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["mpmiaoxi", "mpsijiu"],
		doubleGroup: ["wei", "jin"],
	},
	yj_majun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["gongqiao", "jingyi"],
		names: "马|钧",
	},
	new_yj_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 4,
		skills: ["xiongjin", "zhenbian", "baoxi"],
	},
	fj_peixiu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["fjzhitu", "dcfujue"],
		names: "裴|秀",
	},
};

export default characters;
