const translate = {
	linghunzhihuo: "灵魂之火",
	linghunzhihuo_info: "对一名角色造成1点火焰伤害，然后随机弃置一张手牌。",
	shenenshu: "神恩术",
	shenenshu_info: "出牌阶段对自己使用，将所有手牌（含此张）替换为基本牌。",
	zhiliaobo: "治疗波",
	zhiliaobo_info: "出牌阶段对一名受伤角色使用，目标进行一次判定，若结果为红色，则回复1点体力，否则获得1点护甲。",
	yuansuhuimie: "元素毁灭",
	yuansuhuimie_info: "对所有角色使用，令目标弃置0~2张牌，并受到2-X点雷电伤害，X为其弃置的手牌数。",
	xingjiegoutong: "星界沟通",
	xingjiegoutong_info: "增加1点体力上限并回复1点体力，弃置你的所有手牌。",
	tanshezhiren: "弹射之刃",
	tanshezhiren_info: "出牌阶段对自己使用，依次按敌方-友方-敌方-的顺序随机弃置阵营内一名随机角色的一张牌（目标不包含你），共结算X次，X为存活角色数，若X为偶数，改为X-1。",
	chuansongmen: "传送门",
	chuansongmen_info: "摸一张牌并展示，若发生在出牌阶段，你可以立即使用摸到的牌，若如此做，你将传送门收回手牌（每阶段最多收回2张传送门）。",
	dunpaigedang: "盾牌格挡",
	dunpaigedang_info: "获得1点护甲值，摸一张牌，然后弃置一张牌。",
	shihuawuqi: "石化武器",
	shihuawuqi_infox: "本回合内攻击范围+1；若你手牌中没有杀，则从牌堆中获得一张杀。",
	shandianjian: "闪电箭",
	shandianjian_info: "目标角色展示一张手牌，然后若你能弃掉一张与所展示牌相同花色的手牌，则对该角色造成1点雷电伤害。",
	shijieshu: "视界术",
	shijieshu_info: "目标从牌堆或弃牌堆中随机装备两张类别不同的装备牌，然后弃置一张牌。",
	zhaomingdan: "照明弹",
	zhaomingdan_info: "观看一名其他角色的手牌，并弃置其区域内的一张牌，然后其与你各摸一张牌。",
	jihuocard: "激活",
	jihuocard_info: "摸一张牌，本回合手牌上限+2。",
};

export default translate;
