const characters = {
	re_xushu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["zhuhai", "qianxin"],
	},
	re_lidian: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xunxun", "xinwangxi"],
		dieAudios: ["lidian"],
	},
	re_zhongyao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["rehuomo", "zuoding"],
		clans: ["颍川钟氏"],
	},
	xin_zhangliang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["rejijun", "refangtong"],
	},
	re_simalang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["requji", "rejunbing"],
		names: "司马|朗",
	},
	re_zhugedan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["regongao", "rejuyi"],
		names: "诸葛|诞",
	},
	re_caorui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["huituo", "remingjian", "xingshuai"],
		isZhugong: true,
	},
	re_caochong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["rechengxiang", "renxin"],
	},
	ol_zhangzhang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["olzhijian", "olguzheng"],
		names: "张|昭-张|纮",
	},
	re_jsp_huangyueying: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["rejiqiao", "relinglong"],
	},
	re_zhangsong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qiangzhi", "rexiantu"],
	},
	re_zhuzhi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["reanguo"],
	},
	dc_caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["reluoying", "dcjiushi"],
	},
	ol_huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinliegong", "remoshi"],
	},
	re_wenpin: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["rezhenwei"],
	},
	re_guanzhang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["fuhun", "retongxin"],
		names: "关|兴-张|苞",
	},
	re_mazhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["refuman"],
	},
	dc_chenqun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["repindi", "dcfaen"],
	},
	re_sundeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["rekuangbi"],
	},
	re_caiyong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rebizhuan", "retongbo"],
	},
	re_chengong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["remingce", "zhichi"],
	},
	re_xunyou: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["reqice", "rezhiyu"],
		clans: ["颍川荀氏"],
	},
	dc_liru: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinjuece", "dcmieji", "dcfencheng"],
	},
	re_zhuhuan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["refenli", "repingkou"],
	},
	ol_dianwei: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olqiangxi", "olninge"],
	},
	re_sp_taishici: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["rejixu"],
		names: "太史|慈",
	},
	re_liufeng: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rexiansi"],
	},
	ol_xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["quhu", "oljieming"],
		clans: ["颍川荀氏"],
	},
	re_liuchen: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rezhanjue", "reqinwang"],
		isZhugong: true,
	},
	dc_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcyicong", "dcqiaomeng"],
		names: "公孙|瓒",
	},
	re_duji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["reandong", "reyingshi"],
	},
	re_jushou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcjianying", "dcshibei"],
	},
	re_zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["reqiaobian"],
	},
	dc_xushu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rezhuhai", "xsqianxin"],
	},
	xin_gaoshun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["decadexianzhen", "decadejinjiu"],
	},
	re_guohuanghou: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["rejiaozhao", "redanxin"],
		names: "郭|null",
	},
	re_xiahoushi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["reqiaoshi", "reyanyu"],
		names: "夏侯|null",
	},
	ol_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["olhaoshi", "oldimeng"],
	},
	re_jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rewansha", "reluanwu", "reweimu"],
	},
	re_guyong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["reshenxing", "rebingyi"],
	},
	xin_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xinquanji", "xinzili"],
		clans: ["颍川钟氏"],
	},
	re_caifuren: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["reqieting", "rexianzhou"],
		names: "蔡|null",
	},
	re_guanping: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["relongyin", "jiezhong"],
	},
	re_guotufengji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rejigong", "shifei"],
		names: "郭|图-逢|记",
	},
	re_zhoucang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rezhongyong"],
	},
	ol_zhurong: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["juxiang", "lieren", "changbiao"],
		doubleGroup: ["shu", "qun"],
		names: "null|null",
	},
	re_zhangchunhua: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["rejueqing", "shangshi"],
	},
	re_gongsunyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["rehuaiyi"],
		names: "公孙|渊",
	},
	re_caozhen: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["residi"],
	},
	re_fuhuanghou: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["rezhuikong", "reqiuyuan"],
	},
	re_fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["reenyuan", "rexuanhuo"],
	},
	xin_lingtong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["decadexuanfeng", "yongjin"],
	},
	xin_liubiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["decadezishou", "decadezongshi"],
	},
	re_caoxiu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qianju", "reqingxi"],
	},
	re_sunxiu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["reyanzhu", "rexingxue", "zhaofu"],
		isZhugong: true,
	},
	ol_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["oltuntian", "olzaoxian"],
	},
	re_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["reqiaomeng", "reyicong"],
		names: "公孙|瓒",
	},
	re_manchong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["rejunxing", "yuce"],
	},
	xin_yufan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["xinzhiyan", "xinzongxuan"],
	},
	dc_bulianshi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcanxu", "dczhuiyi"],
	},
	re_hanhaoshihuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["reshenduan", "reyonglve"],
		names: "韩|浩-史|涣",
	},
	re_panzhangmazhong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["reduodao", "reanjian"],
		names: "潘|璋-马|忠",
	},
	re_wangyi: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["zhenlie", "miji"],
	},
	re_madai: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "reqianxi"],
	},
	xin_xusheng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["decadepojun"],
	},
	re_taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tianyi", "hanzhan"],
		names: "太史|慈",
	},
	re_masu: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["resanyao", "rezhiman"],
	},
	re_sunluban: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["rechanhui", "rejiaojin"],
	},
	xin_handang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xingongji", "xinjiefan"],
	},
	yujin_yujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["decadezhenjun"],
		dieAudios: ["xin_yujin.mp3"],
	},
	re_caozhang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xinjiangchi"],
	},
	re_chengpu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["ollihuo", "rechunlao"],
	},
	re_quancong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xinyaoming"],
	},
	re_liaohua: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xindangxian", "xinfuli"],
	},
	re_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["decadejingce"],
	},
	re_wuyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinbenxi"],
		clans: ["陈留吴氏"],
	},
	re_zhuran: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xindanshou"],
	},
	ol_pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["ollianhuan", "olniepan"],
	},
	re_zhangyi: {
		sex: "male",
		group: "shu",
		hp: 5,
		skills: ["rewurong", "reshizhi"],
	},
	xin_wuguotai: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["xinganlu", "xinbuyi"],
		names: "丁|null",
	},
	re_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_rejianxiong", "rehujia"],
		isZhugong: true,
	},
	re_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["refankui", "reguicai"],
		names: "司马|懿",
	},
	re_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tiandu", "new_reyiji"],
	},
	re_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_retuxi"],
	},
	re_xuzhu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_reluoyi"],
	},
	re_xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["reganglie", "new_qingjian"],
		names: "夏侯|惇",
	},
	re_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olpaoxiao", "oltishen"],
	},
	re_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["ollongdan", "olyajiao"],
	},
	re_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["new_rewusheng", "new_yijue"],
	},
	re_machao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "retieji"],
	},
	re_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["reyingzi", "refanjian"],
	},
	re_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["keji", "qinxue", "rebotu"],
	},
	re_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qixi", "fenwei"],
	},
	re_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["reqianxun", "relianying"],
		clans: ["吴郡陆氏"],
	},
	re_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["reguose", "liuli"],
		names: "桥|null",
	},
	re_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["rekurou", "zhaxiang"],
	},
	re_lvbu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["wushuang", "new_liyu"],
	},
	re_huatuo: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jijiu", "new_reqingnang"],
	},
	re_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rerende", "rejijiang"],
		isZhugong: true,
	},
	re_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["lijian", "rebiyue"],
		names: "null|null",
	},
	re_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["rejizhi", "reqicai"],
	},
	re_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["rezhiheng", "rejiuyuan"],
		isZhugong: true,
	},
	re_sunshangxiang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["xiaoji", "rejieyin"],
	},
	re_zhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["reluoshen", "qingguo"],
	},
	re_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["reguanxing", "kongcheng"],
		names: "诸葛|亮",
	},
	re_huaxiong: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["reyaowu", "shizhan"],
	},

	re_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinleiji", "xinguidao", "xinhuangtian"],
		isZhugong: true,
	},
	xin_yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["reguhuo"],
	},
	re_zuoci: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rehuashen", "rexinsheng"],
	},

	ol_xiahouyuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xinshensu", "shebian"],
		names: "夏侯|渊",
	},
	caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xinjushou", "xinjiewei"],
	},
	ol_weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinkuanggu", "reqimou"],
	},
	ol_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["oltianxiang", "olhongyan", "piaoling"],
		names: "桥|null",
	},
	zhoutai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["buqu", "fenji"],
	},
	ol_pangde: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "rejianchu"],
	},
	ol_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olduanliang", "oljiezi"],
	},
	ol_sp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["bazhen", "olhuoji", "olkanpo", "cangzhuo"],
		names: "诸葛|亮",
	},
	ol_yanwen: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olshuangxiong"],
		names: "颜|良-文|丑",
	},
	ol_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olluanji", "olxueyi"],
		isZhugong: true,
	},
	re_menghuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["huoshou", "rezaiqi", "twqiushou"],
		isZhugong: true,
		doubleGroup: ["shu", "qun"],
	},
	ol_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 8,
		skills: ["oljiuchi", "roulin", "benghuai", "olbaonue"],
		isZhugong: true,
	},
	ol_sunjian: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 5,
		skills: ["gzyinghun", "wulie", "twpolu"],
		isZhugong: true,
	},
	re_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["rexingshang", "refangzhu", "songwei"],
		isZhugong: true,
	},
	ol_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["oltiaoxin", "olzhiji"],
	},
	ol_caiwenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olbeige", "duanchang"],
	},
	ol_liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xiangle", "olfangquan", "olruoyu"],
		isZhugong: true,
	},

	re_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["oljiang", "olhunzi", "olzhiba"],
		isZhugong: true,
	},
	re_jianyong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["reqiaoshui", "jyzongshi"],
	},
};

export default characters;
