const characters = {
	ol_baosanniang: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["olwuniang", "olxushen"],
		dieAudios: ["baosanniang"],
	},
	junk_sunquan: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["dili", "yuheng"],
		groupInGuozhan: "wu",
		dieAudios: ["shen_sunquan"],
	},
	new_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["jilin", "yingyou", "yingtian"],
		groupInGuozhan: "wei",
		names: "司马|懿",
	},
	hr_wufu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dchuairen", "dcchizei"],
		dieAudios: ["wufu"],
		img: "image/character/wufu.jpg",
	},
	xj_peixiu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xjzhitu", "dcxiujue"],
		names: "裴|秀",
		dieAudios: ["fj_peixiu"],
		img: "image/character/fj_peixiu.jpg",
	},
	cx_majun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["chuanxie", "yjqiaosi"],
		names: "马|钧",
		dieAudios: ["yj_majun"],
		img: "image/character/yj_majun.jpg",
	},
	qq_majun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yuliao", "qiqiao", "yanxie"],
		names: "马|钧",
		dieAudios: ["yj_majun"],
		img: "image/character/yj_majun.jpg",
	},
	one_dc_sp_machao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["onedcspzhuiji", "onedcspshichou"],
	},
	two_dc_sp_machao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["zhuiji", "dc_olshichou"],
	},
	old_wuyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["benxi"],
		clans: ["陈留吴氏"],
	},
	old_shixie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["biluan", "lixia"],
		dieAudios: ["shixie"],
	},
	panfeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["kuangfu"],
	},
	old_guanyinping: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["xueji_old", "oldhuxiao", "oldwuji"],
		dieAudios: ["guanyinping"],
	},
	old_caocao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["junkguixin", "feiying"],
		dieAudios: ["shen_caocao"],
	},
	old_chendao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["drlt_wanglie"],
		dieAudios: ["chendao"],
	},
	old_liyan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["duliang", "fulin"],
		dieAudios: ["liyan"],
	},
	old_guanzhang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["old_fuhun"],
		names: "关|兴-张|苞",
	},
	new_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["moon_jushou", "jiewei"],
		dieAudios: ["caoren"],
	},
	huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["liegong"],
	},
	old_dingfeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["fenxun", "duanbing"],
		dieAudios: ["dingfeng"],
	},
	old_huanghao: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["oldqinqing", "oldhuisheng"],
		dieAudios: ["huanghao"],
	},
	oldre_liubiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zishou", "zongshi"],
		dieAudios: ["liubiao"],
	},
	old_liubiao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["oldzishou", "zongshi"],
		dieAudios: ["liubiao"],
	},
	old_gaoshun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xianzhen", "jinjiu"],
		dieAudios: ["gaoshun"],
	},
	old_caorui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["huituo", "oldmingjian", "xingshuai"],
		isZhugong: true,
		dieAudios: ["caorui"],
	},
	old_handang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["oldgongji", "oldjiefan"],
		dieAudios: ["handang"],
	},
	old_yangzhi: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["wanyi", "maihuo"],
		clans: ["弘农杨氏"],
		dieAudios: ["yangzhi"],
	},
	old_yangyan: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["xuanbei", "xianwan"],
		clans: ["弘农杨氏"],
		dieAudios: ["yangyan"],
	},
	madai: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "oldqianxi"],
	},
	xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["gzduanliang"],
	},
	junk_simayi: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["buchen", "smyyingshi", "xiongzhi", "quanbian"],
		hasHiddenSkill: true,
		names: "司马|懿",
		dieAudios: ["jin_simayi"],
	},
	fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["enyuan", "xuanhuo"],
	},
	ol_yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wangzun", "tongji"],
		dieAudios: ["re_yuanshu"],
	},
	pangde: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "mengjin"],
	},
	ol_huaxiong: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["new_reyaowu"],
		dieAudios: ["old_huaxiong"],
	},
	old_wangyun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wylianji", "moucheng"],
		clans: ["太原王氏"],
		dieAudios: ["wangyun"],
	},
	old_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["tianxiang", "hongyan"],
		names: "桥|null",
		dieAudios: ["xiaoqiao"],
	},
	weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["kuanggu"],
	},
	xiahouyuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["shensu"],
		names: "夏侯|渊",
	},
	old_zhangxingcai: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["oldshenxian", "qiangwu"],
		dieAudios: ["zhangxingcai"],
	},
	old_fuhuanghou: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["oldzhuikong", "oldqiuyuan"],
		dieAudios: ["fuhuanghou"],
	},
	old_caochong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["oldrenxin", "oldchengxiang"],
		dieAudios: ["caochong"],
	},
	yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["old_guhuo"],
	},
	zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["leiji", "guidao", "huangtian"],
		isZhugong: true,
	},
	old_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["new_repaoxiao", "new_tishen"],
		dieAudios: ["re_zhangfei"],
	},
	old_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longdan", "new_yajiao"],
		dieAudios: ["re_zhaoyun"],
	},
	old_huatuo: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jijiu", "chulao"],
		dieAudios: ["re_huatuo"],
	},
	old_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wusheng", "yijue"],
		dieAudios: ["re_guanyu"],
	},
	old_caochun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["shanjia"],
		dieAudios: ["caochun"],
	},
	masu: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xinzhan", "huilei"],
	},
	xushu: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xswuyan", "jujian"],
		groupBorder: "wei",
	},
	liru: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["juece", "mieji", "fencheng"],
	},
	xin_yujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jieyue"],
		dieAudios: ["yujin.mp3"],
	},
	old_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["zzhenggong", "zquanji", "zbaijiang"],
		clans: ["颍川钟氏"],
	},
	old_xusheng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["pojun"],
		dieAudios: ["xusheng"],
	},
	old_zhuran: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["olddanshou"],
		dieAudios: ["zhuran"],
	},
	old_lingtong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["oldxuanfeng"],
		dieAudios: ["lingtong"],
	},
	old_caoxiu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["taoxi"],
		dieAudios: ["caoxiu"],
	},
	old_caozhen: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sidi"],
		dieAudios: ["caozhen"],
	},
	old_maliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xiemu", "naman"],
	},
	old_chenqun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dingpin", "oldfaen"],
		dieAudios: ["chenqun"],
	},
	old_zhuhuan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["youdi"],
	},
	old_zhuzhi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["anguo"],
		dieAudios: ["zhuzhi"],
	},

	old_zhugezhan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["old_zuilun", "old_fuyin"],
		names: "诸葛|瞻",
		dieAudios: ["zhugezhan"],
	},
	old_guanqiujian: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["drlt_zhenrong", "drlt_hongju"],
		names: "毌丘|俭",
		dieAudios: ["guanqiujian"],
	},
	old_wanglang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["gushe", "jici"],
		dieAudios: ["wanglang"],
	},
	old_wangyi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["oldzhenlie", "oldmiji"],
	},
	re_yujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yizhong"],
		dieAudios: ["yujin.mp3"],
	},
};

export default characters;
