window.updateList = [
    //app文件夹
    'app/index.js',
    'app/menu.js',
    'app/redirect.js',

    'downloadExtension.html',
    'main.js',
    'package.json',
    'update.html',

    //教程
    // '(必看)无名杀全教程10.0.pdf',

    //应用配置
    'extension/应用配置/extension.js',
    'extension/应用配置/extension_demo.js',
    'extension/应用配置/export.js',
    'extension/应用配置/api.js',
    'extension/应用配置/highlightjs-line-numbers.min.js',

    //在线更新
    'extension/在线更新/extension.js',
	'extension/在线更新/extension.css',
	'extension/在线更新/typings/index.d.ts',

    //拖拽读取
    'extension/拖拽读取/extension.css',
    'extension/拖拽读取/extension.js',
    'extension/拖拽读取/jszip.js',
    'extension/拖拽读取/minizip-asm.min.js',
    'extension/拖拽读取/updateContent',
    'extension/拖拽读取/version',
    'extension/拖拽读取/worker.js',
    'extension/拖拽读取/worker2.js',
    'extension/拖拽读取/node_modules/iconv-lite/Changelog.md',
    'extension/拖拽读取/node_modules/iconv-lite/LICENSE',
    'extension/拖拽读取/node_modules/iconv-lite/package.json',
    'extension/拖拽读取/node_modules/iconv-lite/README.md',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/dbcs-codec.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/dbcs-data.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/index.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/internal.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/sbcs-codec.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/sbcs-data-generated.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/sbcs-data.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/utf16.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/utf32.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/utf7.js',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/tables/big5-added.json',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/tables/cp936.json',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/tables/cp949.json',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/tables/cp950.json',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/tables/eucjp.json',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/tables/gbk-added.json',
    'extension/拖拽读取/node_modules/iconv-lite/encodings/tables/shiftjis.json',
    'extension/拖拽读取/node_modules/iconv-lite/lib/bom-handling.js',
    'extension/拖拽读取/node_modules/iconv-lite/lib/index.d.ts',
    'extension/拖拽读取/node_modules/iconv-lite/lib/index.js',
    'extension/拖拽读取/node_modules/iconv-lite/lib/streams.js',
    'extension/拖拽读取/node_modules/safer-buffer/dangerous.js',
    'extension/拖拽读取/node_modules/safer-buffer/LICENSE',
    'extension/拖拽读取/node_modules/safer-buffer/package.json',
    'extension/拖拽读取/node_modules/safer-buffer/Porting-Buffer.md',
    'extension/拖拽读取/node_modules/safer-buffer/Readme.md',
    'extension/拖拽读取/node_modules/safer-buffer/safer.js',
    'extension/拖拽读取/node_modules/safer-buffer/tests.js',
    

    // typings
    // "typings/ai.d.ts",
    // "typings/AIConfig.d.ts",
    // "typings/ArrayEx.d.ts",
    // "typings/brawl.d.ts",
    // "typings/button.d.ts",
    // "typings/card.d.ts",
    // "typings/CardConfig.d.ts",
    // "typings/CharacterConfig.d.ts",
    // "typings/cheat.d.ts",
    // "typings/click.d.ts",
    // "typings/client.d.ts",
    // "typings/content.d.ts",
    // "typings/control.d.ts",
	// "typings/cordova-plugin-dialogs.d.ts",
    // "typings/cordova-plugin-file.d.ts",
	// "typings/cordova-plugin-file-transfer.d.ts",
	// "typings/cordova-plugin-local-notifications.d.ts",
    // "typings/cordova.d.ts",
    // "typings/create.d.ts",
    // "typings/DateEx.d.ts",
    // "typings/develop.d.ts",
    // "typings/dialog.d.ts",
    // "typings/electron.d.ts",
    // "typings/event.d.ts",
    // "typings/ExInterface.d.ts",
    // "typings/ExtensionConfig.d.ts",
    // "typings/filter.d.ts",
    // "typings/game.d.ts",
    // "typings/get.d.ts",
    // "typings/HTMLDivElementEx.d.ts",
    // "typings/import-card.d.ts",
    // "typings/import-character.d.ts",
    // "typings/index.d.ts",
    // "typings/init.d.ts",
    // "typings/lib.d.ts",
    // "typings/LocalGameConfigMenu.d.ts",
    // "typings/message.d.ts",
    // "typings/nodews.d.ts",
    // "typings/player.d.ts",
    // "typings/SkillConfig.d.ts",
    // "typings/sort.d.ts",
    // "typings/status.d.ts",
    // "typings/type.d.ts",
    // "typings/ui.d.ts",
    // "typings/windowEx.d.ts",
    // "typings/ws.d.ts"
];

window.removeFileList = [
    //教程
    '(必看)无名杀全教程9.5.pdf',
    '(必看)无名杀全教程9.6.pdf',
    '(必看)无名杀全教程9.7.pdf',
    '(必看)无名杀全教程9.8.pdf',
    '(必看)无名杀全教程9.9.pdf'
];