import { Character } from "../../../../noname/library/element/index.js";

export default {
	// 分组1：野心家
	gz_zhonghui: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakequanji", "fakepaiyi"],
		hasSkinInGuozhan: true,
	}),
	gz_simazhao: new Character({
		sex: "male",
		group: "ye",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhaoxin", "gzsuzhi"],
		hasSkinInGuozhan: true,
	}),
	gz_gongsunyuan: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzhuaiyi", "gzzisui"],
		hasSkinInGuozhan: true,
	}),
	gz_sunchen: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakeshilu", "fakexiongnve"],
		dieAudios: ["pe_sunchen"],
		hasSkinInGuozhan: false,
	}),
	gz_zhugedan: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_gongao"],
	}),
	gz_pot_weiyan: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_new_kuanggu"],
	}),
	gz_re_lvbu: new Character({
		sex: "male",
		group: "ye",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["gz_wuchang", "gz_liyu"],
	}),
	gz_yl_yuanshu: new Character({
		sex: "male",
		group: "ye",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_new_yongsi", "gz_new_weidi"],
	}),
	gz_jsrg_liuyan: new Character({
		sex: "male",
		group: "ye",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_tushe", "gz_limu"],
	}),
	// 分组2：谷爱凌
	gz_tangzi: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxingzhao"],
		doubleGroup: ["wei", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_mengda: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qiuan", "liangfan"],
		dieAudios: ["pe_mengda"],
		doubleGroup: ["wei", "shu"],
		hasSkinInGuozhan: false,
	}),
	gz_liuqi: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzwenji", "gztunjiang"],
		doubleGroup: ["qun", "shu"],
		hasSkinInGuozhan: true,
	}),
	gz_mifangfushiren: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["mffengshi"],
		doubleGroup: ["wu", "shu"],
		hasSkinInGuozhan: false,
	}),
	gz_shixie: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbiluan", "gzrelixia"],
		doubleGroup: ["wu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_zhanglu: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzrebushi", "gzremidao"],
		doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_db_wenyang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_quedi", "gz_zhuifeng", "gz_chongjian"],
		doubleGroup: ["wei", "wu"],
	}),
	gz_dongzhao: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["quanjin", "zaoyun"],
		// doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: false,
	}),
	gz_re_xushu: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhuhai", "gzpozhen", "gzjiancai"],
		hasSkinInGuozhan: true,
	}),
	// 那男舅
	gz_wujing: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["donggui", "fengyang"],
		hasSkinInGuozhan: true,
	}),
	// 严虎
	gz_yanbaihu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhidao", "gzyjili"],
		hasSkinInGuozhan: true,
	}),
	gz_xuyou: new Character({
		doubleGroup: ["wei", "qun"],
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzchenglve", "gzshicai"],
		hasSkinInGuozhan: true,
	}),
	gz_xiahouba: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzbaolie"],
		doubleGroup: ["wei", "shu"],
		hasSkinInGuozhan: true,
	}),
	gz_panjun: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzcongcha", "xinfu_gongqing"],
		doubleGroup: ["shu", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_huangzu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxishe"],
		hasSkinInGuozhan: true,
	}),
	gz_zhugeke: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["aocai", "gzduwu"],
		hasSkinInGuozhan: true,
	}),
	gz_wenqin: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjinfa"],
		dieAudios: ["pe_wenqin"],
		doubleGroup: ["wei", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_xf_sufei: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzlianpian"],
		doubleGroup: ["wu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_liuba: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gztongduo", "qingyin"],
		hasSkinInGuozhan: true,
	}),
	gz_pengyang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gztongling", "gzjinyu"],
		doubleGroup: ["shu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_zhuling: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjuejue", "gzfangyuan"],
		hasSkinInGuozhan: true,
	}),
	gz_wangyi: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhenlie", "miji"],
	}),
	gz_wangji: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzqizhi", "gzjinqu"],
	}),
	gz_xurong: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxionghuo"],
	}),
	gz_xianglang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzkanji", "dcqianzheng"],
	}),
	gz_tengyin: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzchenjian", "gzxixiu"],
	}),
	gz_re_panshu: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhiren", "gzyaner"],
	}),
	gz_maliang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiemu", "naman"],
		dieAudios: ["old_maliang"],
	}),
	gz_caozhen: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzsidi"],
	}),
	gz_bulianshi: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["old_anxu", "zhuiyi"],
	}),
	gz_mazhong: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["twfuman"],
	}),
	gz_ol_lisu: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiaoyan", "xianzhu"],
	}),

	gz_jun_liubei: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhangwu", "jizhao", "shouyue"],
	}),
	gz_jun_zhangjiao: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["wuxin", "hongfa", "wendao"],
	}),
	gz_jun_sunquan: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jiahe", "lianzi", "jubao"],
	}),

	gz_lingcao: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzdujin"],
	}),
	gz_lifeng: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["tunchu", "shuliang"],
	}),
	gz_beimihu: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzguishu", "gzyuanyu"],
	}),
	gz_jianggan: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["weicheng", "daoshu"],
	}),
	gz_sp_duyu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["spwuku", "spmiewu"],
	}),
	gz_huaxin: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["wanggui", "fakexibing"],
	}),
	gz_luyusheng: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakezhente", "fakezhiwei"],
	}),
	gz_zongyu: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zyqiao", "gzchengshang"],
	}),
	gz_miheng: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakekuangcai", "gzshejian"],
		hasSkinInGuozhan: true,
		dieAudios: ["re_miheng"],
	}),
	gz_fengxi: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyusui", "gzboyan"],
		hasSkinInGuozhan: true,
	}),
	gz_dengzhi: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzjianliang", "gzweimeng"],
		hasSkinInGuozhan: true,
	}),
	gz_re_nanhualaoxian: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzgongxiu", "gztaidan", "gzjinghe_new"],
	}),
	gz_zhouyi: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhukou", "gzduannian", "gzlianyou"],
	}),
	gz_re_xunchen: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzfenglve", "gzanyong"],
	}),
	gz_lvlingqi: new Character({
		sex: "female",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["guowu", "gzshenwei", "gzzhuangrong"],
		hasSkinInGuozhan: true,
	}),
	gz_dc_yanghu: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdeshao", "gzmingfa"],
	}),

	gz_jun_caocao: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jianan", "huibian", "gzzongyu"],
	}),

	gz_liaohua: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzdangxian"],
	}),
	gz_zhugejin: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzhuanshi", "gzhongyuan", "gzmingzhe"],
	}),
	gz_yangxiu: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdanlao", "gzjilei"],
	}),
	gz_zumao: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["yinbing", "juedi"],
	}),
	gz_fuwan: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzmoukui"],
		img: "image/character/tw_fuwan.jpg",
	}),
	gz_chendao: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["drlt_wanglie"],
	}),
	gz_tw_tianyu: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhenxi", "gzjiansu"],
	}),
	gz_tw_liufuren: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhuidu", "gzshigong"],
	}),
	gz_old_huaxiong: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzyaowu", "gzshiyong"],
	}),
	gz_tw_xiahoushang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gztanfeng"],
	}),

	gz_xf_huangquan: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdianhu", "gzjianji"],
		doubleGroup: ["wei", "shu"],
	}),
	gz_guohuai: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzduanshi", "gzjingce"],
		hasSkinInGuozhan: true,
	}),
	gz_guanqiujian: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhengrong", "gzhongju"],
	}),
	gz_zhujun: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzgongjian", "gzkuimang"],
	}),
	gz_chengong: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyinpan", "gzxingmou"],
		doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_re_xugong: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbiaozhao", "gzyechou"],
		doubleGroup: ["wu", "qun"],
	}),

	gz_yangwan: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyouyan", "gzzhuihuan"],
		hasSkinInGuozhan: true,
	}),
	// 神谷爱凌
	gz_key_ushio: new Character({
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 3,
		//hujia: 999,
		skills: ["ushio_huanxin", "ushio_xilv"],
		// 就你势力多
		doubleGroup: ["key", "wei", "shu", "wu", "qun", "jin"],
	}),

	gz_wangling: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakemibei"],
	}),
	gz_yanyan: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakejuzhan"],
	}),
	gz_xin_zhuran: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakedanshou"],
	}),
	gz_gaoshun: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakexunxi", "fakehuanjia"],
		hasSkinInGuozhan: true,
	}),
	//国战无双
	//阴的没边了十头人
	gz_shichangshi: new Character({
		sex: "male",
		group: "qun",
		hp: 2,
		maxHp: 2,
		hujia: 0,
		skills: ["gz_danggu", "gz_mowang"],
		trashBin: ["sex:male_castrated"],
		names: "张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望",
	}),
	gz_scs_zhangrang: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_taoluan"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_zhaozhong: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_chiyan"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_sunzhang: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_zimou"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_bilan: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_picai"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_xiayun: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_yaozhuo"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_hankui: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_xiaolu"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_lisong: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_kuiji"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_duangui: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_chihe"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_guosheng: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_niqu"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_gaowang: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		hujia: 0,
		isUnseen: true,
		skills: ["gz_miaoyu"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_gaolan: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_jungong", "gz_dengli"],
		dieAudios: ["sp_gaolan"],
	}),
	gz_caoang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["kaikang"],
	}),
	gz_zhangxingcai: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["shenxian", "gz_qiangwu"],
	}),
	gz_luzhi: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_qingzhong", "gz_weijing"],
	}),
	gz_quyi: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fuqi", "jiaozi"],
	}),
	gz_caoying: new Character({
		sex: "female",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_lingren", "gz_fujian"],
	}),
	gz_guansuo: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_zhengnan"],
	}),
	gz_zhangxuan: new Character({
		sex: "female",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_tongli", "gz_shezang"],
	}),
	gz_zhangyao: new Character({
		sex: "female",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_yuanyu", "gz_xiyan"],
	}),
	gz_guanyinping: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xueji", "gz_huxiao"],
	}),
	gz_xinxianying: new Character({
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_caishi"],
	}),
	gz_yj_zhanghe: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_zhilve"],
	}),
	gz_mizhu: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_ziyuan", "gz_jugu"],
	}),
	gz_caochun: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_shanjia"],
	}),
	//OL限时武将
	gz_re_xusheng: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["repojun"],
	}),
	// 怎么还冒出来一个体力上限不一样的呢？
	gz_ol_sb_sunjian: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 5,
		hujia: 0,
		skills: ["olsbhulie", "olsbyipo"],
	}),
	gz_liuyan: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xinfu_tushe", "xinfu_limu"],
	}),
	gz_re_huanggai: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["rekurou", "zhaxiang"],
	}),
	gz_re_xuzhu: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["new_reluoyi"],
	}),
	gz_ol_weiyan: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xinkuanggu", "reqimou"],
	}),
	gz_ol_yanwen: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["olshuangxiong"],
		names: "颜|良-文|丑",
	}),
};

export const sort = "";
