/** @type { importCharacterConfig['character'] } */
const character = {
	swd_huzhongxian: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["daofa", "xielv", "hujing"],
		names: "null|null",
	},

	swd_anka: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["songci", "anlianying"],
	},
	swd_septem: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jiying", "liaoyuan", "yishan"],
	},
	swd_kama: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["yueren", "shangshi"],
	},
	swd_miles: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["aojian", "miles_xueyi", "mohua2"],
		isUnseen: false,
	},
	swd_nicole: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["huanjian", "lingwu", "minjing"],
	},
	swd_wangsiyue: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["duishi", "biyue"],
	},
	swd_weida: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["yueren", "zhenlie", "duijue"],
	},
	swd_xuanyuanjianxian: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["pozhou", "huajian", "xuanyuan"],
		names: "轩辕|null",
	},

	swd_chenjingchou: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["youyin", "yihua"],
	},
	swd_duguningke: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["nlianji", "touxi"],
		names: "独孤|宁珂",
	},
	swd_guyue: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["gtiandao", "gxianyin", "wangchen"],
	},
	swd_tuobayuer: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["swdliuhong", "poyue", "niepan"],
		names: "拓跋|玉儿",
	},
	swd_yuwentuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wushuang", "xielei", "kunlunjing"],
		names: "宇文|拓",
	},
	swd_yuxiaoxue: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["huanhun", "daixing", "yinyue"],
	},

	swd_jiliang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["yunchou", "gongxin", "jqimou"],
	},
	swd_shuijing: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["mojian", "duanyue", "tuzhen"],
	},
	swd_quxian: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["mojian", "huanxia"],
	},
	swd_xiyan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jiefen", "datong"],
	},
	swd_cheyun: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["cyxianjiang", "cyqiaoxie", "shengong"],
	},
	swd_huanyuanzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["swdtianshu", "lanzhi", "mufeng"],
	},
	swd_murongshi: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["duanyi", "guxing"],
		names: "慕容|诗",
	},
	swd_jipeng: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["reyingzi", "guozao"],
	},
	swd_qi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["yaotong", "heihuo", "pojian"],
	},

	swd_luchengxuan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["ljifeng", "lxianglong"],
	},
	swd_xiarou: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["xianghui", "huiqi"],
	},
	swd_moye: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["rexue", "liuli", "senluo"],
	},

	swd_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longdan", "pozhen", "tanlin"],
	},
	swd_hengai: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["funiao", "ningxian", "hlingbo"],
	},
	swd_duanmeng: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["xuanying", "lieren"],
		names: "马|蕴",
	},
	swd_jiangwu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["yijue", "dangping"],
		names: "严|鹏",
	},
	swd_tuwei: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zhanlu", "susheng"],
	},
	swd_yeyaxi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["rexue", "huopu", "shenyan"],
	},

	swd_muyun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zhuhai", "polang", "jikong"],
	},
	swd_lanyin: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["xingdian", "yulin", "luomei"],
	},
	swd_zhiyin: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["xuehuang", "ningshuang", "zhuyu"],
	},
	swd_qiner: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["huanyin", "tianhuo", "xuanzhou"],
	},
	swd_jiuyou: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["lexue"],
	},
	swd_duopeng: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["luanji", "reyingzi"],
	},

	swd_fengtianling: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["guiyan", "jiang"],
	},
	swd_huyue: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["hyunshen", "fengming"],
	},
	swd_jialanduo: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xianyin", "mailun"],
	},
	swd_rongshuang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["suiyan", "duanxing"],
	},
	swd_zhuoshanzhu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["suiyan", "wanjun"],
	},
	swd_jiting: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["guanhu", "lingshi"],
	},

	swd_sikongyu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sliufeng", "linyun", "hutian"],
		names: "司空|宇",
	},
	swd_muyue: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["xingzhui", "lingxian", "shouyin"],
	},
	swd_ziqiao: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["guaili", "fuyan"],
	},
	swd_fengyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["fzhenwei", "shangxi"],
	},

	swd_huanglei: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jilve", "gongshen", "gaizao"],
	},
	swd_kendi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zhanxing", "kbolan"],
		names: "null|肯迪",
	},
	swd_lilian: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["swd_wuxie", "lqingcheng"],
		names: "null|null",
	},
	swd_kangnalishi: {
		sex: "male",
		group: "qun",
		hp: 1,
		skills: ["busi", "xuying", "yinguo"],
		names: "null|null",
	},
	swd_xuanyuanjiantong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["chengjian", "huanling"],
		names: "轩辕|null",
	},
	swd_huiyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["hwendao", "lingfeng", "hxunzhi"],
	},

	swd_chenfu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xuanzhou", "bingfeng"],
		isUnseen: false,
	},
	swd_chengyaojin: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jiuchi", "jufu"],
		isUnseen: false,
	},
	swd_shanxiaoxiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["shehun", "xiaomoyu"],
	},
	swd_yuchiyanhong: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["huanxing", "meihuo"],
		names: "尉迟|嫣红",
	},
	swd_qinshubao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["huajing", "pingxu"],
		isUnseen: false,
	},
	swd_zhanglie: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["huajin", "poxiao"],
		isUnseen: false,
	},

	swd_hanluo: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["tiebi"],
	},
	swd_fu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["yudun"],
		names: "null|null",
	},
	swd_linyue: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["zhenjiu", "lmazui"],
		names: "null|null",
	},
	swd_zidashu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["shoulie", "hudun"],
	},
	swd_maixing: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["toudan", "shending"],
	},
	swd_fuyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["lianda"],
	},
	swd_haidapang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["bingjian", "rumeng"],
	},
	swd_shaowei: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["jianji", "huangyu"],
	},

	swd_youzhao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longdan", "yuchen"],
		names: "赵|昂",
	},
	swd_shangzhang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["lianwu"],
		names: "马|null",
	},
	swd_situqiang: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["fengze", "lingyue", "jinlin"],
		names: "司徒|蔷",
	},

	swd_chunyuheng: {
		sex: "male",
		group: "wei",
		hp: 2,
		skills: ["jueqing", "shengshou", "xuying"],
		names: "淳于|恒",
	},
	swd_yuli: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["lingxin", "tianxiang"],
	},
	swd_zhanggao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yicong", "poxing"],
	},
	swd_shuwaner: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["sxianjing", "huodan"],
	},
	swd_xiaohuanglong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yeying", "juxi"],
		names: "null|null",
	},

	swd_hupo: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dunxing", "guiying"],
	},
	swd_jiangziya: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["mingfu", "tianlun"],
		names: "姜|尚",
	},
};

for (let i in character) {
	character[i].img = "extension/杀海拾遗/image/character/" + i + ".jpg";
}

export default character;
