const perfectPair = {
	swd_fengtianling: ["swd_huyue", "swd_jiting"],
	swd_rongshuang: ["swd_zhuoshanzhu"],
	swd_jialanduo: ["swd_zhuoshanzhu"],
	swd_sikongyu: ["swd_muyue"],
	swd_fengyu: ["swd_ziqiao"],
	swd_zhaoyun: ["swd_hengai", "swd_yeyaxi", "zhaoyun"],
	swd_hengai: ["zhugeliang", "sp_zhugeliang"],
	swd_duanmeng: ["swd_shangzhang"],
	swd_shangzhang: ["swd_situqiang"],
	swd_tuwei: ["swd_hengai"],
	swd_jiangwu: ["swd_zhaoyun"],
	swd_muyun: ["swd_lanyin", "swd_zhiyin", "swd_zhanggao", "xushu"],
	swd_lanyin: ["swd_zhiyin"],
	swd_yuli: ["swd_chunyuheng"],
	swd_jiuyou: ["swd_zhiyin"],
	swd_qiner: ["swd_hengai"],
	swd_huzhongxian: ["swd_jiliang", "swd_jipeng", "swd_xiyan"],
	swd_anka: ["swd_kama"],
	swd_septem: ["swd_nicole", "swd_kama", "swd_weida", "swd_wangsiyue", "swd_huiyan"],
	swd_nicole: ["swd_lilian"],
	swd_xuanyuanjianxian: ["swd_xuanyuanjiantong"],
	swd_chenjingchou: ["swd_yuxiaoxue", "swd_tuobayuer"],
	swd_yuxiaoxue: ["swd_yuwentuo"],
	swd_zhanglie: ["swd_tuobayuer"],
	swd_duguningke: ["swd_yuwentuo", "swd_shanxiaoxiao", "swd_yuchiyanhong"],
	swd_jiliang: ["swd_shuijing", "swd_jipeng"],
	swd_jipeng: ["swd_duopeng"],
	swd_cheyun: ["swd_huanyuanzhi", "swd_murongshi"],
	swd_murongshi: ["swd_huanyuanzhi", "swd_shuijing"],
	swd_huanyuanzhi: ["swd_jipeng"],
	swd_qi: ["swd_huzhongxian"],
	swd_luchengxuan: ["swd_xiarou"],
};

export default perfectPair;
