const characters = {
	chengjichengcui: {
		sex: "male",
		group: "wei",
		hp: 6,
		skills: ["oltousui", "olchuming"],
		names: "成|济-成|倅",
		groupBorder: "jin",
	},
	wangxiang: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["bingxin"],
	},
	jin_jiachong: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["xiongshu", "jianhui"],
	},
	xuangongzhu: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["gaoling", "qimei", "ybzhuiji"],
		hasHiddenSkill: true,
		names: "司马|null",
	},
	xinchang: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["canmou", "congjian"],
	},
	yangzhi: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["xinwanyi", "maihuo"],
		clans: ["弘农杨氏"],
	},
	yangyan: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["xinxuanbei", "xianwan"],
		clans: ["弘农杨氏"],
	},
	ol_huaxin: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["caozhao", "olxibing"],
	},
	zhongyan: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["bolan", "yifa"],
		clans: ["颍川钟氏"],
	},
	weiguan: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["zhongyun", "shenpin"],
	},
	cheliji: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["chexuan", "qiangshou"],
		names: "null|null",
	},
	simazhou: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["recaiwang", "naxiang"],
		names: "司马|伷",
	},
	ol_lisu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["qiaoyan", "xianzhu"],
	},
	jin_yanghuiyu: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["huirong", "ciwei", "caiyuan"],
		hasHiddenSkill: true,
	},
	shibao: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["zhuosheng"],
	},
	jin_zhangchunhua: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["huishi", "qingleng", "xuanmu"],
		hasHiddenSkill: true,
	},
	jin_simayi: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["buchen", "smyyingshi", "xiongzhi", "xinquanbian"],
		hasHiddenSkill: true,
		names: "司马|懿",
	},
	jin_wangyuanji: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["shiren", "yanxi"],
		hasHiddenSkill: true,
	},
	jin_simazhao: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["tuishi", "xinchoufa", "zhaoran", "chengwu"],
		isZhugong: true,
		hasHiddenSkill: true,
		names: "司马|昭",
	},
	jin_xiahouhui: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["baoqie", "jyishi", "shiduo"],
		hasHiddenSkill: true,
		names: "夏侯|徽",
	},
	jin_simashi: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 4,
		skills: ["taoyin", "yimie", "ruilve", "tairan"],
		hasHiddenSkill: true,
		isZhugong: true,
		names: "司马|师",
	},
	zhanghuyuechen: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["xijue"],
		names: "张|虎-乐|綝",
	},
	duyu: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["sanchen", "zhaotao"],
	},
};

export default characters;
