/** @type { importCharacterConfig['character'] } */
const character = {
	yxs_qinqiong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yxs_fanji", "yxs_menshen"],
	},
	yxs_wuzetian: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["nvquan", "qiandu", "yxsweiyi"],
		names: "武|曌",
	},
	yxs_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zhulu", "xieling"],
	},
	yxs_mozi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jieyong", "feigong", "jianai"],
		names: "墨|翟",
	},
	yxs_bole: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["bolehuiyan", "xiangma"],
		names: "孙|阳",
	},
	yxs_aijiyanhou: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["seyou", "sheshi"],
		names: "null|null",
	},
	yxs_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["fengyi", "wange"],
		names: "null|null",
	},
	yxs_yangyuhuan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["fengyan", "nichang"],
	},
	yxs_baosi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jieyin", "fenghuo"],
		names: "姒|null",
	},
	yxs_napolun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["tongling", "fanpu"],
		names: "波拿巴|拿破仑",
	},
	yxs_kaisa: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["ducai"],
		names: "尤利乌斯|盖乌斯",
	},
	yxs_zhuyuanzhang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qiangyun"],
	},
	yxs_jinke: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["cike", "qiangxi"],
		names: "姜|荆轲",
	},
	yxs_libai: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["miaobi", "zhexian"],
	},
	yxs_luban: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["guifu", "lshengong"],
		names: "公输|般",
	},
	yxs_lvzhi: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["zhensha", "xumou"],
	},
	yxs_goujian: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["keji", "tuqiang"],
		names: "姒|鸠浅",
	},
	yxs_lishimin: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["kongju"],
	},
	yxs_huamulan: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["xiaoji", "yizhuang"],
		names: "null|null",
	},
	yxs_luobinhan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xiadao", "sheshu", "lguiyin"],
		names: "null|null",
	},
	yxs_chengjisihan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "qianglue"],
		names: "孛儿只斤|铁木真",
	},
	yxs_mingchenghuanghou: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["tiewan", "chajue"],
		names: "闵|兹映",
	},
	yxs_wangzhaojun: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["heqin", "wluoyan"],
		names: "王|嫱",
	},
	yxs_luocheng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["hanqiang", "biaoqi"],
	},
	yxs_direnjie: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["shentan", "kanpo"],
	},
	yxs_sunwu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["bingsheng", "taolue"],
	},
	yxs_chengyaojin: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sanbanfu"],
	},
	yxs_yujix: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["ysheshen", "yxschangnian"],
		names: "null|null",
	},
	yxs_xiangyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wushuang", "yxsciqiu"],
		names: "项|籍",
	},
	yxs_yingzheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jianxiong", "batu"],
	},
	yxs_yuefei: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["longdan", "wumu"],
	},
	yxs_fuermosi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yanyi", "jiean"],
		names: "福尔摩斯|夏洛克",
	},
	yxs_guiguzi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["baihe", "yinyang", "xiushen"],
		names: "王|诩",
	},
	yxs_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["chujia", "zhijie"],
		names: "桥|null",
	},
	yxs_luzhishen: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yxsdili", "kuangchan"],
		names: "鲁|达",
	},
	yxs_zhaoyong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zyhufu", "hanbei"],
	},
	yxs_yangguang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["shiqin", "yaoyi"],
	},
	yxs_tangbohu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["luobi", "fengliu"],
		names: "唐|寅",
	},
	yxs_zhangsanfeng: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zbudao", "taiji"],
	},
	yxs_nandinggeer: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["huli", "xianqu", "yixin"],
		names: "南丁格尔|弗洛伦斯",
	},
	yxs_weizhongxian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zhuxin", "wlianhuan"],
	},
	yxs_meixi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["liebo", "yaoji"],
		names: "嬉|null",
	},
	yxs_lanlinwang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["guimian", "lyuxue"],
		names: "高|肃",
	},
};

for (let i in character) {
	character[i].img = "extension/英雄杀/image/character/" + i + ".jpg";
}

export default character;
