/** @type { importCharacterConfig['character'] } */
const character = {
	hs_jaina: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["huopu", "aoshu", "bingjia"],
	},
	hs_lrexxar: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["yushou"],
	},
	hs_wuther: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["fengxian", "rejieming"],
	},
	hs_jgarrosh: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["zhanhou", "qiangxi"],
	},
	hs_malfurion: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jihuo"],
	},
	hs_guldan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["moxie", "fuhua", "hongxi"],
	},
	hs_anduin: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["shengguang", "shijie", "anying"],
	},
	hs_sthrall: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tuteng", "guozai", "zuling"],
	},
	hs_waleera: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["jianren", "mengun", "wlianji"],
	},

	hs_medivh: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["jingxiang", "zuzhou", "mdzhoufu"],
	},
	hs_alleria: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["fengxing", "xinliegong"],
	},
	hs_magni: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["zhongjia", "dunji"],
	},
	hs_liadrin: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["xueren"],
	},
	hs_morgl: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["s_tuteng"],
	},
	hs_khadgar: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["midian", "fuwen", "jinzhou"],
	},
	hs_tyrande: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["yuelu", "xingluo"],
	},

	hs_neptulon: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["liechao", "qingliu"],
	},
	hs_wvelen: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["shengyan", "xianzhi"],
	},
	hs_antonidas: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yanshu", "bingshuang"],
	},
	hs_alakir: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["fengnu", "shengdun"],
	},
	hs_zhouzhuo: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yiwen"],
	},
	hs_yngvar: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["huanwu"],
	},
	hs_bchillmaw: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["hanshuang", "bingshi"],
	},
	hs_malorne: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["enze", "chongsheng"],
	},
	hs_malygos: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["malymowang"],
	},
	hs_xuefashi: {
		sex: "male",
		group: "wei",
		hp: 2,
		skills: ["liehun", "xjumo"],
	},
	hs_loatheb: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["duzhang"],
	},
	hs_trueheart: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["qianghuax"],
	},
	hs_sainaliusi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["chongsheng", "yulu"],
	},
	hs_lrhonin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["bingyan", "yufa"],
	},
	hs_bolvar: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yuanzheng", "bzhuiji"],
	},
	hs_fuding: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["shengdun", "fbeifa"],
	},
	hs_xuanzhuanjijia: {
		sex: "male",
		group: "shu",
		hp: 2,
		skills: ["jixuan"],
	},
	hs_ysera: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["bimeng"],
	},
	hs_alextrasza: {
		sex: "female",
		group: "shu",
		hp: 5,
		skills: ["fushi"],
	},
	hs_nozdormu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["shixu"],
	},
	hs_sapphiron: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["bingdong", "stuxi"],
	},
	hs_kchromaggus: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["fenlie"],
	},
	hs_lreno: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tanmi"],
	},
	hs_brann: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qianghua", "mashu"],
	},
	hs_finley: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["maoxian"],
	},
	hs_kcthun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["luanji", "xianji"],
	},
	hs_anomalus: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mobao"],
	},
	hs_blingtron: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zengli", "xiubu"],
	},
	hs_yogg: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qianhou"],
	},
	hs_xialikeer: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["duxin"],
	},
	hs_pyros: {
		sex: "female",
		group: "shu",
		hp: 2,
		skills: ["pyuhuo"],
	},
	hs_kalimosi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["kqizhou"],
	},

	hs_zhishigushu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jiaohui"],
	},
	hs_zhanzhenggushu: {
		sex: "male",
		group: "wei",
		hp: 6,
		skills: ["biri"],
	},
	hs_ronghejuren: {
		sex: "male",
		group: "shu",
		hp: 8,
		skills: ["ronghuo"],
	},
	hs_shanlingjuren: {
		sex: "male",
		group: "wu",
		hp: 8,
		skills: ["luoshi"],
	},
	hs_aedwin: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["lianzhan"],
	},
	hs_mijiaojisi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["kuixin"],
	},
	hs_huzhixiannv: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jingmeng", "qingliu"],
	},
	hs_totemic: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["peiyu"],
	},
	hs_wujiyuansu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["hswuji"],
	},
	hs_xsylvanas: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["busi", "xshixin", "xmojian"],
	},
	hs_siwangzhiyi: {
		sex: "male",
		group: "qun",
		hp: 12,
		skills: ["mieshi"],
	},
	hs_bilanyoulong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["lingzhou"],
	},
	hs_jinglinglong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["moyao"],
	},
	hs_ruanniguai: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["nianfu", "xiaorong"],
	},
	hs_hudunren: {
		sex: "male",
		group: "shu",
		hp: 2,
		skills: ["hhudun"],
	},
	hs_nate: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["chuidiao"],
	},
	hs_jiaziruila: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["hannu"],
	},
	hs_shifazhe: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["shifa"],
	},
	hs_lafamu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xieneng"],
	},
	hs_yelise: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["xunbao", "zhuizong"],
	},
	hs_jiawodun: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jinhua"],
	},

	hs_fandral: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["nuyan", "chouhuo"],
	},
	hs_hallazeal: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["shengteng", "yuansu"],
	},
	hs_enzoth: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mengye"],
	},
	hs_walian: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wzhanyi"],
	},
	hs_pengpeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yindan"],
	},
	hs_yashaji: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["ysjqisha"],
	},

	hs_tanghangu: {
		sex: "male",
		group: "shu",
		hp: 5,
		skills: ["zhongji"],
	},
	hs_aya: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["ayuling", "qingzun"],
	},
	hs_barnes: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["hsnitai"],
	},
	hs_kazhakusi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["lianjin"],
	},
	hs_shaku: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["shouji"],
	},
	hs_laxiao: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["hsguimou", "yingxi", "hlongyi"],
	},
	hs_mojinbaozi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["jingcu", "shengzhang"],
	},
	hs_shuiwenxuejia: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["kekao"],
	},
	hs_shizugui: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["szbianshen"],
	},
	hs_hemite: {
		sex: "male",
		group: "wu",
		hp: 6,
		skills: ["zhuilie"],
	},
	hs_laila: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["lieyang"],
	},

	hs_selajin: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qianfu", "shimo"],
	},
	hs_bannabusi: {
		sex: "male",
		group: "wu",
		hp: 14,
		skills: ["qingtian"],
	},
	hs_amala: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["azaowu", "shouwang"],
	},
	hs_yinggencao: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["lieqi"],
	},

	hs_zhihuanhua: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["huanjue"],
	},
	hs_shirencao: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["srjici"],
	},
	hs_kaituozhe: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["tansuo", "yinzong"],
	},

	hs_fachaotuteng: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xiyong"],
	},
	hs_huolituteng: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["hllingxi"],
	},
	hs_manyututeng: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["zhaochao"],
	},
	hs_tgolem: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xinwuyan", "guozaix"],
	},

	hs_heifengqishi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["hstianqi"],
	},
	hs_yangyanwageli: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["hspuzhao", "hsyanxin"],
	},

	hs_aiqinvyao: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["nsaiqi", "nsbeiming"],
	},

	hs_yelinlonghou: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["ylyuchu"],
	},
	hs_yelinchulong: {
		sex: "male",
		group: "qun",
		hp: 1,
		skills: [],
		isUnseen: false,
	},
	hs_ashamoer: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["asyouzhang"],
	},
	hs_fengjianhuanfengzhe: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tuteng", "huanfeng"],
	},
	hs_taisi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["hsxingyi", "hshuanling"],
	},

	hs_hajiasha: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["zhoujiang", "muyin"],
	},
	hs_tuoqi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["tqchuanyue"],
	},
	hs_siwangxianzhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["hualing", "yibian"],
	},
	hs_xukongzhiying: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["wxuying"],
	},

	hs_duyaxinshi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["hshuanyu"],
	},
};

for (let i in character) {
	character[i].img = "extension/杀海拾遗/image/character/" + i + ".jpg";
}

export default character;
