export default {
	"#gz_caocao:die": "霸业未成未成啊！",
	"#gz_simayi:die": "难道真是天意难违？",
	"#gz_xiahoudun:die": "两，两边都看不见了……",
	"#gz_zhangliao:die": "真的没想到……",
	"#gz_xuzhu:die": "冷，好冷啊……",
	"#gz_guojia:die": "咳，咳……",
	"#gz_zhenji:die": "悼良会之永绝兮，哀一逝而异乡……",
	"#gz_xiahouyuan:die": "竟然……比我还……快……",
	"#gz_zhanghe:die": "啊……膝盖……中箭了……",
	"#gz_xuhuang:die": "一顿不吃，饿得慌……",
	"#gz_caoren:die": "长江以南，再无王土矣……",
	"#gz_dianwei:die": "主公，快走！",
	"#gz_xunyu:die": "主公要臣死，臣不得不死……",
	"#gz_caopi:die": "子建，子建……",
	"#gz_yuejin:die": "箭疮发作，吾命休矣……",

	"#gz_liubei:die": "这就是桃园吗？",
	"#gz_guanyu:die": "什么？此地名叫麦城？",
	"#gz_zhangfei:die": "实在是，杀不动了……",
	"#gz_zhugeliang:die": "将星陨落，天命难违……",
	"#gz_zhaoyun:die": "这，就是失败的滋味吗？",
	"#gz_machao:die": "（马蹄声远去……）",
	"#gz_huangyueying:die": "亮……",
	"#gz_huangzhong:die": "不得不服老啦~",
	"#gz_weiyan:die": "谁敢杀我？！呃啊……",
	"#gz_pangtong:die": "看来我命中注定将丧命于此……",

	"#gz_huoshui1": "别走了，再玩一会儿嘛。",
	"#gz_huoshui2": "走不动了嘛？",
};
