export const normal = [
	["spade", 1, "juedou"],
	["spade", 1, "shandian"],
	["spade", 2, "feilongduofeng"],
	["spade", 2, "bagua"],
	["spade", 2, "hanbing"],
	["spade", 3, "guohe"],
	["spade", 3, "shunshou"],
	["spade", 4, "guohe"],
	["spade", 4, "shunshou"],
	["spade", 5, "sha"],
	["spade", 5, "jueying"],
	["spade", 6, "qinggang"],
	["spade", 6, "sha", "thunder"],
	["spade", 7, "sha"],
	["spade", 7, "sha", "thunder"],
	["spade", 8, "sha"],
	["spade", 8, "sha"],
	["spade", 9, "sha"],
	["spade", 9, "jiu"],
	["spade", 10, "sha"],
	["spade", 10, "bingliang"],
	["spade", 11, "sha"],
	["spade", 11, "wuxie"],
	["spade", 12, "zhangba"],
	["spade", 12, "tiesuo"],
	["spade", 13, "nanman"],
	["spade", 13, "dawan"],

	["club", 1, "juedou"],
	["club", 1, "baiyin"],
	["club", 2, "sha"],
	["club", 2, "tengjia"],
	["club", 2, "renwang"],
	["club", 3, "sha"],
	["club", 3, "zhibi"],
	["club", 4, "sha"],
	["club", 4, "zhibi"],
	["club", 5, "sha"],
	["club", 5, "dilu"],
	["club", 6, "lebu"],
	["club", 6, "sha", "thunder"],
	["club", 7, "nanman"],
	["club", 7, "sha", "thunder"],
	["club", 8, "sha"],
	["club", 8, "sha", "thunder"],
	["club", 9, "sha"],
	["club", 9, "jiu"],
	["club", 10, "sha"],
	["club", 10, "bingliang"],
	["club", 11, "sha"],
	["club", 11, "sha"],
	["club", 12, "jiedao"],
	["club", 12, "tiesuo"],
	["club", 13, "wuxie", null, ["guo"]],
	["club", 13, "tiesuo"],

	["diamond", 1, "zhuge"],
	["diamond", 1, "zhuque"],
	["diamond", 2, "shan"],
	["diamond", 2, "tao"],
	["diamond", 3, "shan"],
	["diamond", 3, "shunshou"],
	["diamond", 4, "yiyi"],
	["diamond", 4, "sha", "fire"],
	["diamond", 5, "guanshi"],
	["diamond", 5, "sha", "fire"],
	["diamond", 6, "shan"],
	["diamond", 6, "wuliu"],
	["diamond", 7, "shan"],
	["diamond", 7, "shan"],
	["diamond", 8, "shan"],
	["diamond", 8, "shan"],
	["diamond", 9, "shan"],
	["diamond", 9, "jiu"],
	["diamond", 10, "shan"],
	["diamond", 10, "sha"],
	["diamond", 11, "shan"],
	["diamond", 11, "sha"],
	["diamond", 12, "sha"],
	["diamond", 12, "sanjian"],
	["diamond", 12, "wuxie", null, ["guo"]],
	["diamond", 13, "shan"],
	["diamond", 13, "zixin"],

	["heart", 1, "taoyuan"],
	["heart", 1, "wanjian"],
	["heart", 2, "shan"],
	["heart", 2, "huogong"],
	["heart", 3, "wugu"],
	["heart", 3, "taipingyaoshu"],
	["heart", 3, "huogong"],
	["heart", 4, "tao"],
	["heart", 4, "sha", "fire"],
	["heart", 5, "qilin"],
	["heart", 5, "chitu"],
	["heart", 6, "tao"],
	["heart", 6, "lebu"],
	["heart", 7, "tao"],
	["heart", 7, "wuzhong"],
	["heart", 8, "tao"],
	["heart", 8, "wuzhong"],
	["heart", 9, "tao"],
	["heart", 9, "yuanjiao"],
	["heart", 10, "tao"],
	["heart", 10, "sha"],
	["heart", 11, "shan"],
	["heart", 11, "yiyi"],
	["heart", 12, "tao"],
	["heart", 12, "sha"],
	["heart", 12, "guohe"],
	["heart", 13, "shan"],
	["heart", 13, "zhuahuang"],

	["spade", 1, "xietianzi", null, ["lianheng"]],
	["spade", 2, "minguangkai"],
	["spade", 3, "huoshaolianying", null, ["lianheng"]],
	["spade", 4, "sha"],
	["spade", 5, "qinglong"],
	["spade", 6, "jiu", null, ["lianheng"]],
	["spade", 7, "sha"],
	["spade", 8, "sha"],
	["spade", 9, "sha", "thunder"],
	["spade", 10, "sha", "thunder"],
	["spade", 11, "sha", "thunder", ["lianheng"]],
	["spade", 12, "lulitongxin"],
	["spade", 13, "wuxie"],

	["heart", 1, "lianjunshengyan"],
	["heart", 2, "diaohulishan"],
	["heart", 3, "jingfanma", null, ["lianheng"]],
	["heart", 4, "shan"],
	["heart", 5, "shan"],
	["heart", 6, "shan", null, ["lianheng"]],
	["heart", 7, "shan"],
	["heart", 8, "tao"],
	["heart", 9, "tao"],
	["heart", 10, "sha"],
	["heart", 11, "sha"],
	["heart", 12, "huoshaolianying", null, ["lianheng"]],
	["heart", 13, "shuiyanqijunx"],

	["club", 1, "yuxi"],
	["club", 2, "huxinjing", null, ["lianheng"]],
	["club", 3, "chiling"],
	["club", 4, "sha"],
	["club", 5, "sha", "thunder", ["lianheng"]],
	["club", 6, "sha"],
	["club", 7, "sha"],
	["club", 8, "sha"],
	["club", 9, "jiu"],
	["club", 10, "lulitongxin"],
	["club", 11, "huoshaolianying", null, ["lianheng"]],
	["club", 12, "shuiyanqijunx"],
	["club", 13, "wuxie", null, ["guo"]],

	["diamond", 1, "xietianzi", null, ["lianheng"]],
	["diamond", 2, "tao"],
	["diamond", 3, "tao", null, ["lianheng"]],
	["diamond", 4, "xietianzi", null, ["lianheng"]],
	["diamond", 5, "muniu"],
	["diamond", 6, "shan"],
	["diamond", 7, "shan"],
	["diamond", 8, "sha", "fire"],
	["diamond", 9, "sha", "fire"],
	["diamond", 10, "diaohulishan", null, ["lianheng"]],
	["diamond", 11, "wuxie", null, ["guo"]],
	["diamond", 12, "fangtian"],
	["diamond", 13, "shan"],

	["diamond", 6, "dinglanyemingzhu"],
	["heart", 13, "liulongcanjia"],
	["spade", 6, "jilinqianyi"],

	//['spade',12,'gz_haolingtianxia'],
	//['diamond',1,'gz_kefuzhongyuan'],
	//['heart',1,'gz_guguoanbang'],
	//['club',12,'gz_wenheluanwu'],
];

export const old = [
	["spade", 1, "juedou"],
	["spade", 1, "shandian"],
	["spade", 2, "cixiong"],
	["spade", 2, "bagua"],
	["spade", 2, "hanbing"],
	["spade", 3, "guohe"],
	["spade", 3, "shunshou"],
	["spade", 4, "guohe"],
	["spade", 4, "shunshou"],
	["spade", 5, "sha"],
	["spade", 5, "jueying"],
	["spade", 6, "qinggang"],
	["spade", 6, "sha", "thunder"],
	["spade", 7, "sha"],
	["spade", 7, "sha", "thunder"],
	["spade", 8, "sha"],
	["spade", 8, "sha"],
	["spade", 9, "sha"],
	["spade", 9, "jiu"],
	["spade", 10, "sha"],
	["spade", 10, "bingliang"],
	["spade", 11, "sha"],
	["spade", 11, "wuxie"],
	["spade", 12, "zhangba"],
	["spade", 12, "tiesuo"],
	["spade", 13, "nanman"],
	["spade", 13, "dawan"],

	["club", 1, "juedou"],
	["club", 1, "baiyin"],
	["club", 2, "sha"],
	["club", 2, "tengjia"],
	["club", 2, "renwang"],
	["club", 3, "sha"],
	["club", 3, "zhibi"],
	["club", 4, "sha"],
	["club", 4, "zhibi"],
	["club", 5, "sha"],
	["club", 5, "dilu"],
	["club", 6, "lebu"],
	["club", 6, "sha", "thunder"],
	["club", 7, "nanman"],
	["club", 7, "sha", "thunder"],
	["club", 8, "sha"],
	["club", 8, "sha", "thunder"],
	["club", 9, "sha"],
	["club", 9, "jiu"],
	["club", 10, "sha"],
	["club", 10, "bingliang"],
	["club", 11, "sha"],
	["club", 11, "sha"],
	["club", 12, "jiedao"],
	["club", 12, "tiesuo"],
	["club", 13, "wuxie", null, ["guo"]],
	["club", 13, "tiesuo"],

	["diamond", 1, "zhuge"],
	["diamond", 1, "zhuque"],
	["diamond", 2, "shan"],
	["diamond", 2, "tao"],
	["diamond", 3, "shan"],
	["diamond", 3, "shunshou"],
	["diamond", 4, "yiyi"],
	["diamond", 4, "sha", "fire"],
	["diamond", 5, "guanshi"],
	["diamond", 5, "sha", "fire"],
	["diamond", 6, "shan"],
	["diamond", 6, "wuliu"],
	["diamond", 7, "shan"],
	["diamond", 7, "shan"],
	["diamond", 8, "shan"],
	["diamond", 8, "shan"],
	["diamond", 9, "shan"],
	["diamond", 9, "jiu"],
	["diamond", 10, "shan"],
	["diamond", 10, "sha"],
	["diamond", 11, "shan"],
	["diamond", 11, "sha"],
	["diamond", 12, "sha"],
	["diamond", 12, "sanjian"],
	["diamond", 12, "wuxie", null, ["guo"]],
	["diamond", 13, "shan"],
	["diamond", 13, "zixin"],

	["heart", 1, "taoyuan"],
	["heart", 1, "wanjian"],
	["heart", 2, "shan"],
	["heart", 2, "huogong"],
	["heart", 3, "wugu"],
	["heart", 3, "huogong"],
	["heart", 4, "tao"],
	["heart", 4, "sha", "fire"],
	["heart", 5, "qilin"],
	["heart", 5, "chitu"],
	["heart", 6, "tao"],
	["heart", 6, "lebu"],
	["heart", 7, "tao"],
	["heart", 7, "wuzhong"],
	["heart", 8, "tao"],
	["heart", 8, "wuzhong"],
	["heart", 9, "tao"],
	["heart", 9, "yuanjiao"],
	["heart", 10, "tao"],
	["heart", 10, "sha"],
	["heart", 11, "shan"],
	["heart", 11, "yiyi"],
	["heart", 12, "tao"],
	["heart", 12, "sha"],
	["heart", 12, "guohe"],
	["heart", 13, "shan"],
	["heart", 13, "zhuahuang"],
];

export const yingbian = [
	//黑桃普通
	["spade", 1, "shandian"],
	["spade", 1, "xietianzi"],
	["spade", 1, "juedou"],
	["spade", 2, "bagua"],
	["spade", 2, "heiguangkai"],
	["spade", 2, "cixiong"],
	["spade", 2, "taigongyinfu"],
	["spade", 3, "zhujinqiyuan", null, ["yingbian_zhuzhan", "yingbian_add"]],
	["spade", 3, "huoshaolianying"],
	["spade", 3, "shuiyanqijunx", null, ["yingbian_zhuzhan", "yingbian_add"]],
	["spade", 4, "guohe"],
	["spade", 4, "sha"],
	["spade", 4, "shuiyanqijunx", null, ["yingbian_zhuzhan", "yingbian_add"]],
	["spade", 5, "jueying"],
	["spade", 5, "qinglong"],
	["spade", 5, "sha"],
	["spade", 6, "qinggang"],
	["spade", 6, "jiu"],
	["spade", 6, "sha", "ice"],
	["spade", 7, "sha"],
	["spade", 7, "sha"],
	["spade", 7, "sha", "ice"],
	["spade", 8, "sha", "ice"],
	["spade", 8, "sha", "ice"],
	["spade", 8, "sha"],
	["spade", 9, "jiu"],
	["spade", 9, "sha", "thunder"],
	["spade", 9, "sha"],
	["spade", 10, "bingliang"],
	["spade", 10, "sha", "thunder"],
	["spade", 10, "sha", null, ["yingbian_canqu", "yingbian_add"]],
	["spade", 11, "wuxie", null, ["yingbian_kongchao", "yingbian_draw"]],
	["spade", 11, "sha", null, ["yingbian_canqu", "yingbian_add"]],
	["spade", 11, "sha", "thunder"],
	["spade", 12, "zhangba"],
	["spade", 12, "lulitongxin"],
	["spade", 12, "tiesuo"],
	["spade", 13, "wutiesuolian"],
	["spade", 13, "wuxie"],
	["spade", 13, "nanman", null, ["yingbian_fujia", "yingbian_remove"]],
	//草花普通
	["club", 1, "juedou"],
	["club", 1, "yuxi"],
	["club", 1, "huxinjing"],
	["club", 2, "sha"],
	["club", 2, "tianjitu"],
	["club", 2, "renwang"],
	["club", 2, "tengjia"],
	["club", 3, "sha"],
	["club", 3, "chiling"],
	["club", 3, "zhibi"],
	["club", 4, "sha", null, ["yingbian_kongchao", "yingbian_add"]],
	["club", 4, "sha", "thunder"],
	["club", 4, "zhibi"],
	["club", 5, "sha", null, ["yingbian_kongchao", "yingbian_add"]],
	["club", 5, "sha", "thunder"],
	["club", 5, "tongque"],
	["club", 6, "sha", "thunder"],
	["club", 6, "sha", null, ["yingbian_kongchao", "yingbian_add"]],
	["club", 6, "lebu"],
	["club", 7, "sha", "thunder"],
	["club", 7, "sha"],
	["club", 7, "nanman", null, ["yingbian_fujia", "yingbian_remove"]],
	["club", 8, "sha", "thunder"],
	["club", 8, "sha", null, ["yingbian_canqu", "yingbian_add"]],
	["club", 8, "sha"],
	["club", 9, "sha"],
	["club", 9, "jiu"],
	["club", 9, "jiu"],
	["club", 10, "bingliang"],
	["club", 10, "lulitongxin"],
	["club", 10, "sha"],
	["club", 11, "sha"],
	["club", 11, "huoshaolianying"],
	["club", 11, "sha"],
	["club", 12, "zhujinqiyuan", null, ["yingbian_zhuzhan", "yingbian_add"]],
	["club", 12, "jiedao", null, ["yingbian_fujia", "yingbian_hit"]],
	["club", 12, "tiesuo"],
	["club", 13, "tiesuo"],
	["club", 13, "wuxie", null, ["guo"]],
	["club", 13, "wuxie", null, ["guo"]],
	//红桃普通
	["heart", 1, "wanjian"],
	["heart", 1, "taoyuan"],
	["heart", 1, "lianjunshengyan"],
	["heart", 2, "shan"],
	["heart", 2, "chuqibuyi", null, ["yingbian_zhuzhan", "yingbian_add"]],
	["heart", 2, "diaohulishan"],
	["heart", 3, "chuqibuyi", null, ["yingbian_zhuzhan", "yingbian_add"]],
	["heart", 3, "wugu"],
	["heart", 3, "jingfanma"],
	["heart", 4, "tao"],
	["heart", 4, "sha", "fire", ["yingbian_canqu", "yingbian_damage"]],
	["heart", 4, "shan"],
	["heart", 5, "qilin"],
	["heart", 5, "chitu"],
	["heart", 5, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
	["heart", 6, "lebu"],
	["heart", 6, "tao"],
	["heart", 6, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
	["heart", 7, "tao"],
	["heart", 7, "dongzhuxianji"],
	["heart", 7, "shan"],
	["heart", 8, "tao"],
	["heart", 8, "dongzhuxianji"],
	["heart", 8, "tao"],
	["heart", 9, "tao"],
	["heart", 9, "yuanjiao"],
	["heart", 9, "tao"],
	["heart", 10, "sha"],
	["heart", 10, "shan"],
	["heart", 10, "sha"],
	["heart", 11, "yiyi"],
	["heart", 11, "tao"],
	["heart", 11, "sha", null, ["yingbian_zhuzhan", "yingbian_add"]],
	["heart", 12, "tao"],
	["heart", 12, "sha"],
	["heart", 12, "huoshaolianying"],
	["heart", 13, "zhuahuang"],
	["heart", 13, "shan"],
	["heart", 13, "huogong", null, ["yingbian_zhuzhan", "yingbian_add"]],
	//方片普通
	["diamond", 1, "wuxinghelingshan"],
	["diamond", 1, "zhuge"],
	["diamond", 1, "xietianzi"],
	["diamond", 2, "shan"],
	["diamond", 2, "tao"],
	["diamond", 2, "tao"],
	["diamond", 3, "shunshou"],
	["diamond", 3, "shan"],
	["diamond", 3, "tao"],
	["diamond", 4, "yiyi"],
	["diamond", 4, "sha", "fire", ["yingbian_canqu", "yingbian_damage"]],
	["diamond", 4, "sha", "fire", ["yingbian_zhuzhan", "yingbian_add"]],
	["diamond", 5, "guanshi"],
	["diamond", 5, "sha", "fire"],
	["diamond", 5, "muniu"],
	["diamond", 6, "wuliu"],
	["diamond", 6, "shan"],
	["diamond", 6, "shan"],
	["diamond", 7, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
	["diamond", 7, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
	["diamond", 7, "shan"],
	["diamond", 8, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
	["diamond", 8, "shan", null, ["yingbian_kongchao", "yingbian_draw"]],
	["diamond", 8, "sha", "fire"],
	["diamond", 9, "jiu"],
	["diamond", 9, "shan"],
	["diamond", 9, "sha", "fire"],
	["diamond", 10, "shan"],
	["diamond", 10, "sha"],
	["diamond", 10, "diaohulishan"],
	["diamond", 11, "sha"],
	["diamond", 11, "shan"],
	["diamond", 11, "wuxie", null, ["guo"]],
	["diamond", 12, "sha"],
	["diamond", 12, "sanjian"],
	["diamond", 12, "wuxie", null, ["guo"]],
	["diamond", 12, "fangtian"],
	["diamond", 13, "zixin"],
	["diamond", 13, "shan"],
	["diamond", 13, "shan"],
	//特殊
	["heart", 3, "taipingyaoshu"],
	["diamond", 4, "dinglanyemingzhu"],
	["heart", 5, "liulongcanjia"],
	["spade", 6, "feilongduofeng"],
	["spade", 6, "jilinqianyi"],
	["club", 12, "gz_wenheluanwu"],
	["heart", 1, "gz_guguoanbang"],
	["spade", 12, "gz_haolingtianxia"],
	["diamond", 1, "gz_kefuzhongyuan"],
];
