export default {
	junling: "军令",
	junling1: "军令一",
	junling1_bg: "令",
	junling1_info: "若被执行，执行者对发起者指定的一名角色造成1点伤害。",
	junling2: "军令二",
	junling2_bg: "令",
	junling2_info: "若被执行，执行者摸一张牌，然后依次交给发起者两张牌。",
	junling3: "军令三",
	junling3_bg: "令",
	junling3_info: "若被执行，执行者失去1点体力。",
	junling4: "军令四",
	junling4_bg: "令",
	junling4_info: "若被执行，直到回合结束，执行者不能使用或打出手牌且非锁定技全部失效。",
	junling4_eff: "军令四",
	junling5: "军令五",
	junling5_bg: "令",
	junling5_info: "若被执行，执行者将武将牌叠置，且不能回复体力直到回合结束。",
	junling5_eff: "军令五",
	junling6: "军令六",
	junling6_bg: "令",
	junling6_info: "若被执行，执行者选择一张手牌和一张装备区内牌（若有），然后弃置其余的牌。",
};
