const translate = {
	zhenfa: "阵法",
	changshezhen: "长蛇阵",
	pozhenjue: "破阵决",
	tianfuzhen: "天覆阵",
	dizaizhen: "地载阵",
	fengyangzhen: "风扬阵",
	yunchuizhen: "云垂阵",
	qixingzhen: "七星阵",
	shepanzhen: "蛇蟠阵",
	shepanzhen_bg: "列",
	yunchuizhen_bg: "垂",
	longfeizhen: "龙飞阵",
	huyizhen: "虎翼阵",
	niaoxiangzhen: "鸟翔阵",
	niaoxiangzhen_info: "令所有非你阵营的队列的角色依次打出一张【闪】，或者受到1点伤害。",
	qixingzhen_info: "弃置所有围攻你的角色各一张牌，然后视为对所有你围攻的角色使用一张不计入出杀次数的杀。",
	// longfeizhen_info:'弃置围攻你的角色各一张牌，然后摸一张牌。',
	// qixingzhen_info:'令我方所有角色进入围攻状态。',
	// shepanzhen_info:'令我方所有角色进入队列状态。',
	// yunchuizhen_info:'令所有围攻角色获得技能〖无双〗，直到其首次造成伤害。',
	// fengyangzhen_info:'令所有被围攻角色获得技能〖飞影〗，直到其首次受到伤害。',
	dizaizhen_info: "所有小势力角色摸一张牌。",
	changshezhen_info: "若你处于队列中，与你同一队列的所有角色摸一张牌，否则将与你逆时针距离最近的同势力角色移至你下家。",
	// pozhenjue_info:'将所有角色的顺序随机重排。',
	tianfuzhen_info: "所有大势力角色弃置一张牌。",
};

export default translate;
