const characters = {
	xin_fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xinxuanhuo", "xinenyuan"],
	},
	guanzhang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["fuhun"],
		names: "关|兴-张|苞",
	},
	wangyi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["zhenlie", "miji"],
	},
	caozhang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_jiangchi"],
	},
	guohuai: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["rejingce"],
	},
	zhangchunhua: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["jueqing", "shangshi"],
	},
	caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["luoying", "jiushi"],
	},
	caochong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["chengxiang", "renxin"],
	},
	xunyou: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qice", "zhiyu"],
		clans: ["颍川荀氏"],
	},
	xin_xushu: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xinwuyan", "xinjujian"],
		groupBorder: "wei",
	},
	xin_masu: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olsanyao", "rezhiman"],
	},
	zhuran: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["danshou"],
	},
	xusheng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xinpojun"],
	},
	wuguotai: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["ganlu", "buyi"],
		names: "丁|null",
	},
	lingtong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xuanfeng"],
	},
	liubiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rezishou", "zongshi"],
	},
	yufan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["zhiyan", "zongxuan"],
	},
	chengong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["mingce", "zhichi"],
	},
	bulianshi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["old_anxu", "zhuiyi"],
	},
	handang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["gongji", "jiefan"],
	},
	fuhuanghou: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["qiuyuan", "zhuikong"],
	},
	zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["quanji", "zili"],
		clans: ["颍川钟氏"],
	},
	jianyong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qiaoshui", "jyzongshi"],
	},
	old_madai: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "qianxi"],
	},
	liufeng: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xiansi"],
	},
	manchong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["junxing", "yuce"],
	},
	chenqun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["pindi", "faen"],
	},
	sunluban: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["chanhui", "jiaojin"],
	},
	guyong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["shenxing", "olbingyi"],
	},
	caifuren: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["qieting", "xianzhou"],
		names: "蔡|null",
	},
	yj_jushou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jianying", "shibei"],
	},
	zhangsong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qiangzhi", "xiantu"],
	},
	zhuhuan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["fenli", "pingkou"],
	},
	xiahoushi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["qiaoshi", "yanyu"],
		names: "夏侯|null",
	},

	panzhangmazhong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["duodao", "anjian"],
		names: "潘|璋-马|忠",
	},
	zhoucang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinzhongyong"],
	},
	guanping: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longyin"],
	},
	liaohua: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dangxian", "fuli"],
	},
	chengpu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["lihuo", "chunlao"],
	},
	gaoshun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinxianzhen", "jinjiu"],
	},
	caozhen: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xinsidi"],
	},
	wuyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olbenxi"],
		clans: ["陈留吴氏"],
	},
	hanhaoshihuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["shenduan", "yonglve"],
		names: "韩|浩-史|涣",
	},

	caorui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["huituo", "mingjian", "xingshuai"],
		isZhugong: true,
	},
	caoxiu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qianju", "qingxi"],
	},
	zhongyao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["huomo", "zuoding"],
		clans: ["颍川钟氏"],
	},
	liuchen: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["zhanjue", "qinwang"],
		isZhugong: true,
	},
	zhangyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wurong", "shizhi"],
	},
	sunxiu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["yanzhu", "xingxue", "xinzhaofu"],
		isZhugong: true,
	},
	zhuzhi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xinanguo"],
	},
	quancong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["yaoming"],
	},
	gongsunyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["huaiyi"],
		names: "公孙|渊",
	},
	guotufengji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jigong", "shifei"],
		names: "郭|图-逢|纪",
	},

	xin_liru: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinjuece", "xinmieji", "xinfencheng"],
		dieAudios: ["liru"],
	},

	guohuanghou: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["jiaozhao", "danxin"],
		names: "郭|null",
	},
	liuyu: {
		sex: "male",
		group: "qun",
		hp: 2,
		skills: ["zhige", "zongzuo", "twchongwang"],
		isZhugong: true,
	},
	liyan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcduliang", "fulin"],
	},
	sundeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["kuangbi"],
	},

	cenhun: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jishe", "lianhuo"],
	},
	huanghao: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qinqing", "huisheng"],
	},
	zhangrang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["taoluan"],
		trashBin: ["sex:male_castrated"],
	},
	sunziliufang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["guizao", "jiyu"],
		names: "孙|资-刘|放",
	},

	xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["zhongjian", "caishi"],
	},
	wuxian: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["fumian", "daiyan"],
		clans: ["陈留吴氏"],
	},
	xushi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["wengua", "fuzhu"],
		names: "徐|null",
	},
	caojie: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["shouxi", "huimin"],
	},

	caiyong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["bizhuan", "tongbo"],
	},
	jikang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qingxian", "juexiang"],
	},
	qinmi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jianzheng", "zhuandui", "tianbian"],
	},
	xuezong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["funan", "xinjiexun"],
	},

	old_huaxiong: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["shiyong"],
	},

	yujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["rezhenjun"],
		dieAudios: ["ol_yujin.mp3"],
	},
};

export default characters;
