const translates = {
	diy_luxun: "陆伯言",
	diy_yuji: "于吉",
	diy_zhouyu: "周公瑾",
	diy_lukang: "陆抗",
	diy_caiwenji: "蔡昭姬",
	diy_zhenji: "甄宓",
	old_majun: "骰子马钧",
	old_majun_prefix: "骰子",

	shaoying: "烧营",
	zonghuo: "纵火",
	diychanyuan: "缠怨",
	diyguhuo: "蛊惑",
	jieyan: "劫焰",
	honglian: "红莲",
	luweiyan: "围堰",
	guihan: "归汉",
	diy_jiaoxia: "皎霞",
	diy_jiaoxia_info: "每当你成为红色牌的目标，你可以摸一张牌。",
	guihan_info: "限定技，当你进入濒死状态时，可以指定一名男性角色与其各回复1点体力并摸两张牌。",
	luweiyan_info: "出牌阶段限一次，你可以将一张非基本牌当作【水攻】使用；结算后你可以视为对其中一个目标使用一张不计入出杀次数的【杀】。",
	honglian_info: "每当你受到来自其他角色的伤害，可以弃置伤害来源的所有红色牌。",
	jieyan_info: "出牌阶段限一次，你可以弃置一张红色手牌令场上所有角色受到1点火焰伤害。",
	diyguhuo_info: "锁定技，准备阶段，你摸两张牌，然后弃置区域内的两张牌。",
	diychanyuan_info: "锁定技，杀死你的角色失去1点体力上限。",
	zonghuo_info: "你可弃置一张牌将你即将造成的伤害变为火焰伤害。",
	shaoying_info: "每当你造成一次火焰伤害，可指定距离受伤害角色1以内的另一名角色，并亮出牌堆顶的一张牌，若此牌为红色，该角色受到1点火焰伤害。",
	xinfu_qiaosi: "巧思",
	xinfu_qiaosi_info: "出牌阶段限一次，你可以投掷一枚六面骰子，亮出牌堆顶的X张牌并获得之。然后，你选择一项：1.交给一名其他角色X张牌。2.弃置X张牌。（X为骰子的点数）",

	diy_caocao: "曹孟德",
	xicai: "惜才",
	xicai_info: "你可以立即获得对你造成伤害的牌。",
	diyjianxiong: "奸雄",
	diyjianxiong_info: "锁定技，在身份局中，于你回合内死亡的角色均视为反贼，国战中，于你回合内死亡的角色若与你势力相同则随机改为另一个势力。",

	diy_weiyan: "魏文长",
	diykuanggu: "狂骨",
	diykuanggu_info: "锁定技，当你造成1点伤害后，若你在其攻击范围内，你回复1点体力；否则你摸一张牌。",

	diy_sp_zhouyu: "周公瑾",
	xiongzi: "雄姿",
	xiongzi_info: "锁定技，你于摸牌阶段额外摸X+1张牌，X为你装备区牌数的一半，向下取整。",
	yaliang: "雅量",
	yaliang_info: "每当你对其他角色造成1点伤害后，或受到其他角色造成的1点伤害后，你可与该角色各摸一张牌。",
};

export default translates;
