const characters = {
	dc_sb_huangquan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcsbqiaodui", "dcsbtuicheng"],
	},
	dc_sb_luotong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcsbjuce", "dcsbkangming"],
	},
	dongxu: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcqingleng", "dczhendu"],
	},
	v_machao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dczhongtao", "dcjizhan"],
	},
	dc_sb_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcsbjunmou", "dcsbzhanyan"],
	},
	dc_sb_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcsbzhouxi", "dcsbshijin"],
	},
	x_dc_zhangqiying: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["x_dc_falu", "x_dc_zhenyi", "x_dc_dianhua"],
	},
	y_dc_zhangqiying: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["y_dc_falu", "y_dc_zhenyi", "y_dc_dianhua"],
	},
	renwan: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcjuanji", "dcrenshuang"],
	},
	dc_sb_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 2,
		maxHp: 4,
		skills: ["dcsbjuemou", "dcsbfuzhan"],
	},
	dc_sb_hulie: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcsbchuanyu", "dcsbyitou"],
	},
	cuilingyi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dchuashang", "dcyuzhi"],
	},
	dc_wuzhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcweiti", "dcyuanrong"],
	},
	dc_zhushuo: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dczsshuhe", "dcjilie"],
	},
	v_caopi: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcdianlun", "dcjiwei", "dcsugang"],
	},
	dc_zhongyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dczhidui", "dcjiesi"],
	},
	dc_xiahouhui: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcdujun", "dcjikun"],
		names: "夏侯|徽",
	},
	dc_sb_liuxie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcsbzhanban", "dcsbchensheng", "dcsbtiancheng"],
		isZhugong: true,
	},
	dc_sb_caohong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcsbyingjia", "dcsbxianju"],
	},
	dc_sb_dongcheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcsbbaojia", "dcsbdouwei"],
	},
	dc_sb_xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcsbbizuo", "dcsbshimou"], //, "dcsbxianshi"
	},
	v_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["dcguangyong", "dcjuchui"],
	},
	liujinliupei: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcllqixin", "dcjiusi"],
		names: "刘|衿-刘|佩",
	},
	caoyuan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcwuyan", "dczhanyu"],
	},
	dc_caochun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xinshanjia"],
		dieAudios: ["caochun"],
	},
	zhanghuai: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dclaoyan", "dcrejueyan"],
		names: "张|null",
	},
	xuxin: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcyuxian", "dcminshan"],
	},
	v_lvbu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["dcxiaowu", "dcbaguan"],
	},
	wu_lukang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcshenduan", "dckegou", "dcdixian"],
		clans: ["吴郡陆氏"],
	},
	sunba: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcjiedang", "dcjidi"],
	},
	v_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcwoheng", "dcyuhui"],
	},
	moqiongshu: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcwanchan", "dcjiangzhi"],
	},
	v_zhangliao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcyuxi", "dcporong"],
	},
	pangfengyi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dcyitong", "dcpeiniang"],
	},
	dc_sb_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcsblieji", "dcsbquzhou"],
	},
	dc_sb_chenlin: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcsbyaozuo", "dcsbzhuanwen"],
	},
	wu_huangfusong: {
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 4,
		skills: ["dcchaozhen", "dclianjie", "dcjiangxian"],
		names: "皇甫|嵩",
	},
	wenyuan: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dckengqiang", "dckuichi", "dcshangjue"],
	},
	dc_jiangqing: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcshangyi", "dcniaoxiang"],
		dieAudios: ["jiangqin.mp3"],
	},
	dc_tianfeng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["sijian", "dcsuishi"],
		dieAudios: ["tianfeng"],
	},
	dc_zhangren: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcchuanxin", "dcfengshi"],
		dieAudios: ["zhangren"],
	},
	dc_sb_jushou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcsbzuojun", "dcsbmuwang"],
	},
	dc_sb_chengyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcshizha", "dcgaojian"],
	},
	dc_lingcao: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 5,
		skills: ["dcdufeng"],
	},
	zhugejing: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcyanzuo", "dczuyin", "dcpijian"],
		names: "诸葛|京",
	},
	liutan: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dcjingyin", "dcchixing"],
	},
	bianyue: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcbizu", "dcwuxie"],
	},
	zhupeilan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dccilv", "dctongdao"],
	},
	dc_sb_zhangxiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcsbfuxi", "dcsbhaoyi"],
	},
	dc_sb_hucheer: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcsbkongwu"],
	},
	dc_sb_guanping: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcsbwuwei"],
	},
	dc_sb_caoang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcsbfengmin", "dcsbzhiwang"],
	},
	dc_sb_dianwei: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 5,
		skills: ["dcsbkuangzhan", "dcsbkangyong"],
	},
	dc_caoshuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcjianzhuan", "dcfanshi"],
	},
	dc_simashi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcsanshi", "dczhenrao", "dcchenlve"],
		names: "司马|师",
		groupBorder: "jin",
	},
	dc_wangling: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcjichou", "dcmouli"],
		clans: ["太原王氏"],
	},
	dc_jiangji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcshiju", "dcyingshi"],
	},
	dc_sb_zhugejin: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcsbtaozhou", "dcsbhoude"],
		names: "诸葛|瑾",
	},
	dc_sb_jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcsbsushen", "dcsbfumou"],
	},
	guanyue: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcshouzhi", "dcfenhui"],
	},
	sp_zhenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcjijie", "dchuiji"],
	},
	wu_guanyu: {
		sex: "male",
		group: "shu",
		hp: 5,
		skills: ["dcjuewu", "dcwuyou", "dcyixian"],
	},
	caofang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dczhimin", "dcjujian"],
		isZhugong: true,
	},
	dc_sb_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcsbquanmou", "dcsbpingliao"],
		names: "司马|懿",
	},
	chendong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcduanxie", "fenming"],
		names: "陈|武-董|袭",
	},
	lvfan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["diaodu", "diancai"],
	},
	cuimao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["zhengbi", "fengying"],
		names: "崔|琰-毛|玠",
	},
	huzun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dczhantao", "dcanjing"],
	},
	zhugemengxue: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcjichun", "dchanying"],
		names: "诸葛|梦雪",
	},
	bailingyun: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dclinghui", "dcxiace", "dcyuxin"],
	},
	dc_qinghegongzhu: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dczhangji", "dczengou"],
		names: "曹|null",
	},
	caoxian: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dclingxi", "dczhifou"],
	},
	dc_sb_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcsbronghuo", "dcsbyingmou"],
	},
	dc_sb_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcsbmingshi", "dcsbmengmou"],
	},
	zhangjian: {
		sex: "male",
		group: "qun",
		hp: 105,
		skills: ["dc_zj_a", "dc_zj_b"],
	},
	zhugeruoxue: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcqiongying", "dcnuanhui"],
		names: "诸葛|若雪",
	},
	caoyi: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["dcmiyi", "dcyinjun"],
	},
	malingli: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dclima", "dcxiaoyin", "dchuahuo"],
	},
	wu_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcxiongmu", "dczhangcai", "dcruxian"],
		clans: ["吴郡陆氏"],
	},
	dc_xujing: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcshangyu", "dccaixia"],
	},
	dc_zhaoxiang: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["refanghun", "refuhan"],
		dieAudios: ["zhaoxiang"],
	},
	dc_guansuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinzhengnan", "xiefang"],
		dieAudios: ["guansuo"],
	},
	xin_baosanniang: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["decadewuniang", "decadexushen"],
		dieAudios: ["baosanniang"],
	},
	xurong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinfu_xionghuo", "xinfu_shajue"],
	},
	dc_shixie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rebiluan", "ollixia"],
		dieAudios: ["shixie"],
	},
	dc_sp_machao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twodcspzhuiji", "twodcspshichou"],
		dieAudios: ["sp_machao"],
	},
	old_huangfusong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinfenyue"],
		names: "皇甫|嵩",
		dieAudios: ["huangfusong"],
	},
	dc_xiahouba: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rebaobian"],
		names: "夏侯|霸",
		dieAudios: ["xiahouba"],
		tempname: ["xiahouba"],
	},
	dc_daxiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcxingwu", "dcluoyan"],
		tempname: ["daxiaoqiao"],
		names: "桥|null-桥|null",
		dieAudios: ["daxiaoqiao"],
	},
	tianshangyi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcposuo", "dcxiaoren"],
	},
	sunlingluan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dclingyue", "dcpandi"],
	},
	dc_wangjun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dctongye", "dcchangqu"],
		groupBorder: "jin",
	},
	zhoubuyi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcshiji", "dcsilun"],
	},
	dc_duyu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcjianguo", "dcdyqingshi"],
		groupBorder: "jin",
	},
	ganfurenmifuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dcchanjuan", "dcxunbie"],
		names: "甘|null-糜|null",
	},
	dc_ganfuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dcshushen", "dcshenzhi"],
		names: "甘|null",
		dieAudios: ["ganfuren"],
	},
	dc_mifuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dcguixiu", "dccunsi"],
		names: "糜|null",
		dieAudios: ["mifuren"],
	},
	wanglang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["regushe", "rejici"],
	},
	ruanji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dczhaowen", "dcjiudun"],
	},
	wu_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 7,
		skills: ["dcjincui", "dcqingshi", "dczhizhe"],
		names: "诸葛|亮",
	},
	duanqiaoxiao: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dccaizhuang", "dchuayi"],
	},
	zhangjinyun: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dchuizhi", "dcjijiao"],
	},
	huanfan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcjianzheng", "dcfumou"],
	},
	chentai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcctjiuxian", "dcchenyong"],
	},
	sunyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcquanshou", "dcshexue"],
	},
	xizheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcdanyi", "dcwencan"],
	},
	dc_ruiji: {
		sex: "female",
		group: "wu",
		hp: 4,
		skills: ["dcwangyuan", "dclingyin", "dcliying"],
		names: "芮|null",
	},
	zerong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dccansi", "dcfozong"],
	},
	xielingyu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcyuandi", "dcxinyou"],
	},
	dc_yangbiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dczhaohan", "dcjinjie", "dcjue"],
		clans: ["弘农杨氏"],
	},
	dc_tengfanglan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcluochong", "dcaichen"],
	},
	yanghong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcjianji", "dcyuanmo"],
	},
	xuelingyun: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcxialei", "dcanzhi"],
	},
	dc_wangyun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dclianji", "dcmoucheng"],
		dieAudios: ["wangyun"],
		clans: ["太原王氏"],
	},
	dc_zhouxuān: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcwumei", "dczhanmeng"],
	},
	chengbing: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcjingzao", "dcenyu"],
	},
	dongguiren: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dclianzhi", "dclingfang", "dcfengying"],
		names: "董|null",
	},
	yuanji: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dcfangdu", "dcjiexing"],
		names: "袁|null",
	},
	zhujianping: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcxiangmian", "dctianji"],
	},
	zhaozhi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dctongguan", "dcmengjie"],
	},
	dc_liuye: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcpoyuan", "dchuace"],
	},
	luyi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["dcyaoyi", "dcshoutan", "dcfuxue"],
	},
	dingshangwan: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["dcfengyan", "dcfudao"],
	},
	quanhuijie: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["dchuishu", "dcyishu", "dcligong"],
	},
	dukui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dcfanyin", "dcpeiqi"],
	},
	zhangfen: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcwanglu", "dcxianzhu", "dcchaixie"],
	},
	liuhui: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcgeyuan", "dcjieshu", "dcgusuan"],
	},
	dc_wangchang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dckaiji", "dcpingxi"],
		clans: ["太原王氏"],
	},
	zhaoang: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		skills: ["dczhongjie", "dcsushou"],
	},
	caohua: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["caiyi", "guili"],
	},
	dc_liuyu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcsuifu", "dcpijing"],
	},
	dc_huangzu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcjinggong", "dcxiaojuan"],
	},
	laiyinger: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["xiaowu", "huaping"],
	},
	caomao: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		skills: ["qianlong", "fensi", "juetao", "zhushi"],
		isZhugong: true,
	},
	dc_luotong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["renzheng", "jinjian"],
	},
	re_fengfangnv: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["tiqi", "baoshu"],
	},
	wufan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tianyun", "wfyuyan"],
	},
	re_zhangbao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinzhoufu", "xinyingbing"],
		dieAudios: ["zhangbao"],
	},
	re_sunyi: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["syjiqiao", "syxiongyi"],
	},
	caojinyu: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["yuqi", "shanshen", "xianjing"],
	},
	zhouyi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["zhukou", "mengqing"],
	},
	re_panshu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["zhiren", "yaner"],
	},
	yangwan: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["youyan", "zhuihuan"],
	},
	ruanyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xingzuo", "miaoxian"],
	},
	fanyufeng: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["bazhan", "jiaoying"],
	},
	guozhao: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["pianchong", "zunwei"],
	},
	re_xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["rezhongjian", "recaishi"],
		dieAudios: ["xinxianying"],
	},
	liubian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["shiyuan", "dushi", "yuwei"],
		isZhugong: true,
	},
	re_liuzan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["refenyin", "liji"],
	},
	wenyang: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["xinlvli", "choujue"],
	},
	wangshuang: {
		sex: "male",
		group: "wei",
		hp: 8,
		skills: ["spzhuilie"],
	},
	huaman: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["manyi", "mansi", "souying", "zhanyuan"],
		names: "孟|null",
	},
	puyuan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["pytianjiang", "pyzhuren"],
	},
	guanlu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tuiyan", "busuan", "mingjie"],
	},
	gexuan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["gxlianhua", "zhafu"],
	},
	leitong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["kuiji"],
	},
	wulan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wlcuorui"],
	},
	lvju: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dczhengyue"],
	},
};

export default characters;
