const characterSort = {
	sp2_huben: ["lvju", "dc_zhangren", "dc_jiangqing", "chendong", "wangshuang", "wenyang", "re_liuzan", "dc_huangzu", "wulan", "leitong", "chentai", "dc_duyu", "dc_wangjun", "dc_xiahouba", "old_huangfusong", "huzun", "dc_lingcao"],
	sp2_shengun: ["puyuan", "guanlu", "gexuan", "wufan", "re_zhangbao", "dukui", "zhaozhi", "zhujianping", "dc_zhouxuān", "zerong"],
	sp2_bizhe: ["dc_zhushuo", "dc_wuzhi", "dc_zhongyu", "dc_luotong", "dc_wangchang", "chengbing", "dc_yangbiao", "ruanji", "cuimao"],
	sp2_huangjia: ["dc_xiahouhui", "caomao", "liubian", "dc_liuyu", "quanhuijie", "dingshangwan", "yuanji", "xielingyu", "sunyu", "ganfurenmifuren", "dc_ganfuren", "dc_mifuren", "dc_shixie", "caofang", "zhupeilan", "bianyue", "sunba", "xuxin", "liujinliupei"],
	sp2_zhangtai: ["guozhao", "fanyufeng", "ruanyu", "yangwan", "re_panshu"],
	sp2_jinse: ["dongxu", "zhanghuai", "wenyuan", "liutan", "caojinyu", "re_sunyi", "re_fengfangnv", "caohua", "laiyinger", "zhangfen", "zhugeruoxue", "caoxian", "dc_qinghegongzhu", "zhugemengxue"],
	sp2_yinyu: ["zhouyi", "luyi", "sunlingluan", "caoyi", "pangfengyi"],
	sp2_wangzhe: ["dc_daxiaoqiao", "dc_sp_machao", "sp_zhenji"],
	sp2_doukou: ["cuilingyi", "re_xinxianying", "huaman", "xuelingyun", "dc_ruiji", "duanqiaoxiao", "tianshangyi", "malingli", "bailingyun", "moqiongshu", "caoyuan"],
	sp2_jichu: ["zhaoang", "dc_liuye", "dc_wangyun", "yanghong", "huanfan", "xizheng", "lvfan", "dc_tianfeng"],
	sp2_yuxiu: ["dongguiren", "dc_tengfanglan", "zhangjinyun", "zhoubuyi", "dc_xujing", "guanyue", "zhugejing", "dc_caochun", "renwan"],
	sp2_qifu: ["dc_guansuo", "xin_baosanniang", "dc_zhaoxiang", "xurong", "x_dc_zhangqiying", "y_dc_zhangqiying"],
	sp2_gaoshan: ["wanglang", "liuhui", "zhangjian"],
	sp2_wumiao: ["wu_zhugeliang", "wu_luxun", "wu_guanyu", "wu_huangfusong", "wu_lukang"],
	sp2_mouding: ["dc_sb_luxun", "dc_sb_jiangwei", "dc_sb_jiaxu", "dc_sb_lusu", "dc_sb_zhouyu", "dc_sb_simayi", "dc_sb_xunyu"],
	sp2_zhonghu: ["dc_jiangji", "dc_wangling", "dc_simashi", "dc_caoshuang"],
	sp2_zijing: ["dc_sb_zhugejin", "dc_sb_guanping"],
	sp2_dushi: ["dc_sb_caoang", "dc_sb_zhangxiu", "dc_sb_dianwei", "dc_sb_hucheer"],
	sp2_zhoulang: ["dc_sb_chengyu", "dc_sb_huanggai"],
	sp2_qizuo: ["dc_sb_jushou", "dc_sb_chenlin"],
	sp2_wangzuo: ["dc_sb_liuxie", "dc_sb_dongcheng", "dc_sb_caohong"],
	sp2_youlin: ["dc_sb_hulie", "dc_sb_dengai"],
	sp2_boyan: ["dc_sb_huangquan", "dc_sb_luotong"],
	sp2_weizhen: ["v_zhangliao", "v_lvbu", "v_dongzhuo", "v_machao"],
	sp2_junwei: ["v_caopi", "v_sunquan"],
	sp2_waitingforsort: [],
};

const characterSortTranslate = {
	sp2_yinyu: "隐山之玉",
	sp2_huben: "百战虎贲",
	sp2_shengun: "奇人异士",
	sp2_huangjia: "皇家贵胄",
	sp2_zhangtai: "章台春望",
	sp2_jinse: "锦瑟良缘",
	sp2_bizhe: "笔舌如椽",
	sp2_wangzhe: "往者可荐",
	sp2_doukou: "豆蔻梢头",
	sp2_jichu: "计将安出",
	sp2_yuxiu: "钟灵毓秀",
	sp2_wumiao: "武庙",
	sp2_gaoshan: "高山仰止",
	sp2_qifu: "祈福",
	sp2_mouding: "谋定天下",
	sp2_zhonghu: "冢虎狼顾",
	sp2_zijing: "子敬邀刀",
	sp2_dushi: "毒士鸩计",
	sp2_zhoulang: "周郎将计",
	sp2_qizuo: "奇佐论胜",
	sp2_wangzuo: "王佐倡义",
	sp2_youlin: "幼麟绝战",
	sp2_boyan: "伯言绽火",
	sp2_weizhen: "威震天下",
	sp2_junwei: "君威盖世",
	sp2_waitingforsort: "等待分包",
};

export { characterSort, characterSortTranslate };
