const characters = {
	sb_lvbu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["sbwushuang", "sbliyu"],
	},
	sb_xiahouyuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sbshensu", "sbzhengzi"],
		names: "夏侯|渊",
	},
	sb_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sbjingce"],
	},
	sb_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sbtuxi", "sbdengfeng"],
	},
	sb_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["sbtiandu", "sbyiji"],
	},
	sb_zhugejin: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["sbhuanshi", "sbhongyuan", "sbmingzhe"],
		names: "诸葛|瑾",
	},
	sb_jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["sbwansha", "sbluanwu", "sbweimu"],
	},
	sb_handang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sbgongqi", "sbjiefan"],
	},
	sb_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["sbyicong", "sbqiaomeng"],
		names: "公孙|瓒",
	},
	sb_gaoshun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["sbxianzhen", "sbjinjiu"],
	},
	sb_xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 1,
		skills: ["sbganglie", "sbqingjian"],
		names: "夏侯|惇",
	},
	sb_xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["sbquhu", "sbjieming"],
	},
	sb_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["sbxingshang", "sbfangzhu", "sbsongwei"],
		isZhugong: true,
	},
	sb_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sbwusheng", "sbyijue"],
	},
	sb_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["sbjizhi", "sbqicai"],
	},
	sb_sp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["sbhuoji", "sbkanpo"],
		names: "诸葛|亮",
	},
	sb_zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sbqiaobian"],
	},
	sb_yujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sbxiayuan", "sbjieyue"],
	},
	sb_huaxiong: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 4,
		hujia: 1,
		skills: ["new_reyaowu", "sbyangwei"],
	},
	liucheng: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["splveying", "spyingwu"],
	},
	sp_yangwan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["spmingxuan", "spxianchou"],
	},
	sb_huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sbliegong"],
	},
	sb_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sbkeji", "sbdujiang"],
	},
	sb_sunshangxiang: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["sbjieyin", "sbliangzhu", "sbxiaoji"],
		groupBorder: "wu",
	},
	sb_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sbzhiheng", "sbtongye", "sbjiuyuan"],
		isZhugong: true,
	},
	sb_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sbkurou", "sbzhaxiang"],
	},
	sb_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["sbyingzi", "sbfanjian"],
	},
	sb_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 2,
		skills: ["sbjushou", "sbjiewei"],
	},
	sb_xiahoushi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["sbqiaoshi", "sbyanyu"],
		names: "夏侯|null",
	},
	sb_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["sbleiji", "sbguidao", "sbhuangtian"],
		isZhugong: true,
	},
	sb_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sbjianxiong", "sbqingzheng", "sbhujia"],
		isZhugong: true,
	},
	sb_zhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["sbluoshen", "qingguo"],
	},
	sb_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sbqixi", "sbfenwei"],
	},
	sb_machao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "sbtieji"],
	},
	sb_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sbduanliang", "sbshipo"],
	},
	sb_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sbpaoxiao", "sbxieji"],
	},
	sb_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sblongdan", "sbjizhu"],
	},
	sb_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sbrende", "sbzhangwu", "sbjijiang"],
		isZhugong: true,
	},
	sb_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 1,
		skills: ["sbtiaoxin", "sbzhiji"],
	},
	sb_fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["sbxuanhuo", "sbenyuan"],
	},
	sb_chengong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["twmingce", "sbzhichi"],
	},
	sb_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["sblijian", "sbbiyue"],
		names: "null|null",
	},
	sb_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["sbluanji", "sbxueyi"],
		isZhugong: true,
	},
	sb_pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["sblianhuan", "sbniepan"],
	},
	sb_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sbjiang", "sbhunzi", "sbzhiba"],
		isZhugong: true,
	},
	sb_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["sbguose", "sbliuli"],
		names: "桥|null",
	},
	sb_liubiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["sbzishou", "sbzongshi"],
	},
	sb_zhurong: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["sblieren", "sbjuxiang"],
		doubleGroup: ["shu", "qun"],
		names: "null|null",
	},
	sb_menghuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sbhuoshou", "sbzaiqi"],
		doubleGroup: ["shu", "qun"],
	},
	sb_yl_luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["sbmingren", "sbzhenliang"],
	},
	sb_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["sbtianxiang", "xinhongyan"],
		names: "桥|null",
	},
	sb_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["sbqianxun", "sblianying"],
		clans: ["吴郡陆氏"],
	},
};

export default characters;
