const characters = {
	xia_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["peqinyi", "pejixin", "pejiwei"],
	},
	eu_kaisa: {
		sex: "male",
		group: "western",
		hp: 4,
		skills: ["eu_ducai", "eu_zhitong", "eu_jiquan"],
		isZhugong: true,
		names: "尤利乌斯|盖乌斯",
	},
	pe_xiahouxuan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["pehuanfu", "olqingyi", "olzeyue"],
	},
	wn_zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["wn_qiaobian"],
	},
	wn_jiaxu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["wn_jianshu", "wn_zhenlve"],
	},
	wn_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["wn_zhuying", "wn_chiyuan"],
	},
	wn_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		isZhugong: true,
		skills: ["wn_dingluan", "wn_zhuijiang"],
	},
	wn_hansui: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 5,
		isZhugong: true,
		skills: ["wn_jubing", "wn_xiongju"],
	},
	wn_houxuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wn_zhongtao", "mashu"],
	},
	wn_chengyi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wn_dutan"],
	},
	wn_yangqiú: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wn_qifeng"],
	},
	pe_jun_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		isZhugong: true,
		skills: ["jun_renwang", "jijiang"],
		dieAudios: ["re_liubei"],
	},
	pe_jun_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		isZhugong: true,
		skills: ["jun_xiongtu", "hujia"],
		dieAudios: ["sb_caocao"],
	},
	pe_jun_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		isZhugong: true,
		skills: ["jun_jiang", "jun_zhiyang", "zhiba"],
		dieAudios: ["sb_sunce"],
	},
	pe_jun_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		isZhugong: true,
		skills: ["jun_hefa", "xueyi"],
		dieAudios: ["ol_sb_yuanshao"],
	},
	pe_jun_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		isZhugong: true,
		skills: ["jun_huanlei", "jun_xiandao", "huangtian"],
		dieAudios: ["re_zhangjiao"],
	},
	pe_jun_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		isZhugong: true,
		skills: ["jun_cuanzun", "jun_liufang", "songwei"],
		dieAudios: ["sb_caopi"],
	},
	pe_jun_liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		isZhugong: true,
		skills: ["jun_fuxiang", "jun_leling", "ruoyu"],
		tempname: ["re_liushan"],
		dieAudios: ["re_liushan"],
	},
	pe_jun_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		isZhugong: true,
		skills: ["jun_henglv", "jiuyuan"],
		dieAudios: ["re_sunquan"],
	},
	pe_jun_liuxie: {
		sex: "male",
		group: "qun",
		hp: 3,
		isZhugong: true,
		skills: ["jun_tianze", "jun_zhaoshou", "twzhuiting"],
		dieAudios: ["liuxie"],
	},
	pe_jun_liuhong: {
		sex: "male",
		group: "qun",
		hp: 4,
		isZhugong: true,
		skills: ["jun_gezhi", "jun_julian"],
		dieAudios: ["jsrg_liuhong"],
	},
	pe_que: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["peyingzhen", "peyuanjue", "peaoyong"],
		names: "null|null",
	},
	yj_caocaoyuanshao: {
		sex: "male",
		group: "wei",
		doubleGroup: ["wei", "qun"],
		hp: 4,
		skills: ["yjguibei", "yjjiechu", "yjdaojue", "yjtuonan"],
		names: "曹|操-袁|绍",
	},
	ps_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["psjuebing", "psfengxie"],
	},
	ps_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["pshuji", "pshoufa"],
	},
	ps_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["pszhanlun", "psjueyi"],
	},
	ca_fanchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["caxingwei", "caqianmu"],
	},
	ca_zhangji: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["casilve", "casuibian"],
	},
	ca_guosi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["casixi", "calvedao"],
	},
	ca_lijue: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["cacuixi", "cajujun"],
	},
	ca_lvbu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["wushuang", "caliyu"],
	},
	ca_wangyun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["calianji", "camoucheng"],
		clans: ["太原王氏"],
		img: "image/character/wangyun.jpg",
	},
	hs_caohuan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["hsjunwei", "hsmoran"],
	},
	hs_liuxuan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["hssifen", "hsfunan"],
		isZhugong: true,
	},
	hs_liuxie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["hsjixu", "hsyouchong"],
	},
	hs_sunhao: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["hsshezuo"],
	},
	chenshou: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["hschenzhi", "hsdianmo", "hszaibi"],
	},
	drag_huaci: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 6,
		skills: ["dragshiyao", "dragzuoyu", "dragduyi", "dragjuliao"],
	},
	drag_guansuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dragqianfu", "dragchengyuan", "dragyuxian"],
	},
	drag_guanping: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["draglongyin", "dragjiezhong"],
	},
	drag_guanyinping: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["dragxueji", "draghuxiao", "tywuji"],
		dieAudios: ["guanyinping"],
	},
	drag_zhoucang: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 5,
		skills: ["dragzhongyong"],
	},
	drag_liaohua: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 5,
		skills: ["dragzhawang", "dragxigui"],
	},
	drag_shendan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["draglianxiang", "dragpingmeng"],
	},
	drag_shenyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["draglianxiang", "dragpanfeng"],
	},
	drag_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dragqianxun", "draglianying"],
	},
	drag_xusheng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dragpojun"],
	},
	she_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 4,
		hujia: 1,
		skills: ["shefujing", "shefujiang", "shetonglu"],
	},
	ps_zhangrang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["pstaoluan", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	ps_zhaozhong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["pschiyan", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	ps_sunzhang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["pszimou", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	ps_bilan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["psbicai", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	ps_xiayun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["psyaozhuo", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	ps_hankui: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["psxiaolu", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	ps_lisong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["pskuiji", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	ps_duangui: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["pschihe", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	ps_guosheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["psniqu", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	ps_gaowang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["psmiaoyu", "pschangshi"],
		dieAudios: ["shichangshi"],
	},
	jy_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jylijun", "jytongbei"],
	},
	jy_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jybeirong", "jyyujun"],
	},
	jy_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 4,
		skills: ["jyqibian", "jycailve"],
		names: "诸葛|亮",
	},
	jy_pangtong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["jylianhuan", "jysuozhou", "jyyuhuo"],
	},
	jy_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["jydimeng", "jyzhouji"],
	},
	jy_zhangzhao: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["jyboyan", "jymushi"],
	},
	jy_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["jysashuang", "jyhuoce"],
	},
	jy_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 5,
		skills: ["jyliezhou", "jyzhaxiang"],
	},
	yj_chezhou: {
		sex: "male",
		group: "wei",
		hp: 6,
		skills: ["psanmou", "pstousuan"],
	},
	yj_yongkai: {
		sex: "male",
		group: "shu",
		hp: 5,
		skills: ["psxiaofan", "psjiaohu", "psquanpan", "pshuoluan"],
		//doubleGroup: ["qun", "shu", "wu"],
	},
	hm_guigu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["hm_tuntian", "hm_qianjun"],
	},
	hm_bosi: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 6,
		skills: ["hm_weiluan", "hm_tianpan", "hm_gaiming"],
	},
	hm_nanhualaoxian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["hm_yufeng", "hm_tianshu"],
		names: "庄|周",
	},
	hm_yudu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["hm_dafu", "hm_jipin"],
	},
	hm_taosheng: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["hm_zhannei", "hm_qianwei"],
	},
	hm_fuyun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["hm_shuiqu", "hm_yure"],
	},
	hm_tangzhou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["hm_jukou", "hm_weichenn"],
	},
	hm_chengyuanzhi: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["hm_wuxiao", "hm_qianhu"],
	},
	hm_gaosheng: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["hm_xiongshi", "hm_difeng"],
	},
	hm_heman: {
		sex: "male",
		group: "qun",
		hp: 5,
		maxHp: 6,
		skills: ["hm_juedian", "hm_nitian"],
	},
	hm_yanzheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["hm_didao", "hm_xianxiang"],
	},
	hm_bocai: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["hm_kunjun", "hm_yingzhan", "hm_cuiji"],
	},
	hm_bairao: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["hm_huoyin"],
	},
	hm_dengmao: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["hm_paoxi", "hm_houying"],
	},
	xk_luoli: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xkjuluan", "xkxianxing"],
	},
	xk_cuilian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xktanlu", "xkjubian"],
	},
	xk_penghu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["xkjuqian", "xkkanpo", "xkyizhong"],
	},
	xk_shanfu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xkbimeng", "xkzhue", "xkfuzhu"],
		doubleGroup: ["shu", "qun"],
		names: "徐|庶",
	},
	xk_pengqi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["xkjushou", "xkliaoluan", "xkhuaying", "xkjizhong"],
	},
	xk_zulang: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["xkxijun", "xkhaokou", "xkronggui"],
		doubleGroup: ["qun", "wu"],
	},
	yy_quyi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yyfuqi", "jiaozi"],
		dieAudios: ["quyi"],
	},
	yy_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yyqizhen", "yicong", "yymujun"],
		isZhugong: true,
		names: "公孙|瓒",
	},
	yy_wenchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yyxuezhan", "yyyazhen"],
	},
	yy_gongsunyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yyxuanshi", "yyxiongye"],
		isZhugong: true,
		names: "公孙|渊",
	},
	yy_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yysudi", "yyqishe", "yylinzhen"],
		isZhugong: true,
	},
	yy_simayi: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yyyanggu", "yyzuifu"],
		names: "司马|懿",
	},
	yy_caorui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yyhuituo", "yymingjian", "xingshuai"],
		isZhugong: true,
		dieAudios: ["caorui"],
	},
	yy_zhaoyun: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["longdan", "chongzhen", "yicong"],
		dieAudios: ["zhaoyun"],
	},
	yy_quancong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["yyyaoming"],
		dieAudios: ["xin_quancong"],
	},
	scl_pangdegong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["scls_yinshi", "scls_pingcai"],
		dieAudios: ["pangdegong"],
	},
	scl_sunhanhua: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["scls_chongxu", "scls_miaojian", "scls_lianhua"],
		dieAudios: ["sunhanhua"],
	},
	scl_miheng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["scls_kuangcai", "scls_shejian"],
		dieAudios: ["miheng"],
	},
	scl_peixiu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xingtu", "scls_juezhi"],
		dieAudios: ["peixiu"],
		groupBorder: "jin",
	},
	scl_caoying: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["scls_lingren"],
		tempname: ["caoying"],
		dieAudios: ["caoying"],
	},
	scl_luotong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["scls_qinzheng"],
		dieAudios: ["luotong"],
	},
	ty_anyingx: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["tyliupo", "tyzhuiling", "tyxihun", "tyxianqi", "tyfansheng"],
		names: "null|null",
		img: "image/character/ty_anying.jpg",
	},
	ty_anying: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["tyliupo", "tyzhuiling", "tyxihun", "tyxianqi"],
		names: "null|null",
	},
	ty_wuque: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["tyansha", "tycangshen", "tyxiongren"],
		names: "null|null",
	},
	ty_yanque: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["tysiji", "tycangshen"],
		names: "null|null",
	},
	ty_wangque: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["tydaifa", "tycangshen"],
		names: "null|null",
	},
	ty_fanjiang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tybianta", "tybenxiang", "tyxiezhan"],
	},
	ty_zhangda: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tyxingsha", "tyxianshou", "tyxiezhan"],
	},
	ty_liue: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["tyxiyu"],
	},
	ty_tanxiong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tylengjian", "tysheju"],
	},
	ty_buzhi: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["tyhongde", "tydingpan"],
	},
	ty_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tyqixi", "tyfenwei"],
	},
	ty_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["tyqianshou", "tytanlong", "tyxibei"],
		clans: ["吴郡陆氏"],
	},
	ty_guanyinping: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["xueji", "huxiao", "tywuji"],
		dieAudios: ["guanyinping"],
	},
	ty_shamoke: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["gzjili", "tymanyong"],
		names: "null|null",
	},
	ty_guanxing: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tyconglong", "tyzhaowu"],
	},
	ty_shicong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tyjinzhong"],
		names: "null|null",
	},
	ty_wuban: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tyyoujun", "tyjicheng"],
		clans: ["陈留吴氏"],
		img: "image/character/wuban.jpg",
	},
	ty_huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinliegong", "tyyizhuang"],
	},
	ty_liaohua: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tydangxian", "tyfuli"],
	},
	ty_fengxí: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tyqingkou"],
		img: "image/character/tw_fengxí.jpg",
	},
	ty_zhangnan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tyfenwu"],
		img: "image/character/tw_zhangnan.jpg",
	},
	ty_zhaorong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tyyuantao"],
	},
	ty_chengjix: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["tyzhongen", "tyliebao"],
	},
	ty_chenshi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tyzhuan"],
	},
	ty_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tyqingshi", "tyyilin", "tychengming"],
	},
	ty_sunquan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["tyfuhan", "tychende", "tywansu"],
	},
	ty_guanyu: {
		sex: "male",
		group: "shu",
		hp: 5,
		skills: ["tywusheng", "tychengshi", "tyfuwei"],
	},
	jd_sb_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jdsbduanliang", "sbshipo"],
		dieAudios: ["sb_xuhuang"],
	},
	jd_jin_wangyuanji: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["jdshiren", "jdyanxi"],
		hasHiddenSkill: true,
		dieAudios: ["jin_wangyuanji"],
	},
	jd_ol_huaxin: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["jdcaozhao", "olxibing"],
		dieAudios: ["ol_huaxin"],
	},
	jd_sp_yangwan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["jdmingxuan", "spxianchou"],
		dieAudios: ["sp_yangwan"],
	},
	jd_sb_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["jdjizhi", "jdqicai"],
		dieAudios: ["sb_huangyueying"],
	},
	jd_sb_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jdlongdan", "jdjizhu"],
		dieAudios: ["sb_zhaoyun"],
	},
	jd_sb_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jdqixi", "jdfenwei"],
		dieAudios: ["sb_ganning"],
	},
	jd_sb_pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jdlianhuan", "oldniepan"],
		tempname: ["sb_pangtong"],
		dieAudios: ["sb_pangtong"],
	},
	jd_hanlong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["duwang", "jdcibei"],
		dieAudios: ["hanlong"],
	},
	jd_jin_xiahouhui: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["jdbaoqie", "jyishi", "shiduo"],
		hasHiddenSkill: true,
		dieAudios: ["jin_xiahouhui"],
		names: "夏侯|徽",
	},
	jd_jin_simazhao: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["tuishi", "choufa", "zhaoran", "chengwu"],
		isZhugong: true,
		hasHiddenSkill: true,
		dieAudios: ["jin_simazhao"],
		names: "司马|昭",
	},
	jd_sb_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jdjianxiong", "sbqingzheng", "sbhujia"],
		isZhugong: true,
		dieAudios: ["sb_caocao"],
	},
	jd_sb_sp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jdhuoji", "jdkanpo"],
		dieAudios: ["sb_sp_zhugeliang"],
		names: "诸葛|亮",
	},
	jd_jin_simashi: {
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 4,
		skills: ["taoyin", "yimie", "jdtairan", "ruilve"],
		isZhugong: true,
		hasHiddenSkill: true,
		dieAudios: ["jin_simashi"],
		names: "司马|师",
	},
	jd_sb_menghuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jdsbhuoshou", "jdsbzaiqi"],
		dieAudios: ["sb_menghuo"],
		doubleGroup: ["shu", "qun"],
	},
	jd_sb_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jdsbluanji", "jdsbxueyi"],
		isZhugong: true,
		dieAudios: ["sb_yuanshao"],
	},
	jd_sb_yujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sbxiayuan", "jdsbjieyue"],
		dieAudios: ["sb_yujin"],
	},
	jd_sb_sunshangxiang: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["jdsbjieyin", "jdsbliangzhu", "sbxiaoji"],
		dieAudios: ["sb_sunshangxiang"],
		groupBorder: "wu",
	},
	jd_sb_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sbrende", "jdsbzhangwu", "sbjijiang"],
		isZhugong: true,
		dieAudios: ["sb_liubei"],
	},
	jd_sb_fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jdsbxuanhuo", "jdsbenyuan"],
		dieAudios: ["sb_fazheng"],
	},
	jd_sb_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jdsbpaoxiao", "sbxieji"],
		dieAudios: ["sb_zhangfei"],
	},
	jd_sb_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jdsbzhiheng", "jdsbtongye", "jdsbjiuyuan"],
		isZhugong: true,
		dieAudios: ["sb_sunquan"],
	},
	jd_sb_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jdsbtianxiang", "jdsbhongyan"],
		dieAudios: ["sb_xiaoqiao"],
		names: "桥|null",
	},
	jd_sb_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jdsbwusheng", "jdsbyijue"],
		dieAudios: ["sb_guanyu"],
	},
	jd_sb_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jdsbtiaoxin", "jdsbzhiji"],
		dieAudios: ["sb_jiangwei"],
	},
	jd_sb_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jdsbguose", "jdsbliuli"],
		dieAudios: ["sb_daqiao"],
		names: "桥|null",
	},
	jd_simayan: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["jdjuqi", "jdfengtu", "jdtaishi"],
		isZhugong: true,
		names: "司马|炎",
	},
	jx_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jxxiongzi", "jxzhanyan"],
	},
	jx_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jxwusheng", "jsrgguanjue", "nuzhan"],
	},
	yj_tianchuan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["pshuying", "psqianjing", "psbianchi"],
	},
	yj_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["psmouchuan", "pszizhong", "psjizun", "psqingsuan"],
		isZhugong: true,
	},
	yj_ehuan: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["psdiwan", "pssuiluan", "psconghan"],
		doubleGroup: ["shu", "qun"],
	},
	yj_zhouji: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["psyanmou", "pszhanyan", "psyuhuo"],
		names: "周|null",
	},
	drag_pangde: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dragtaiguan", "mashu"],
	},
	drag_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dragchaojue", "dragjunshen"],
	},
	drag_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["draglizhong", "dragjuesui"],
	},
	drag_lvchang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["dragjuwu", "dragshouxiang"],
	},
	jsp_ganfuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["shushen", "shenzhi"],
		img: "image/character/gz_ganfuren.jpg",
		names: "甘|null",
	},
	ol_xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["xincaishi", "xinzhongjian"],
	},
	ol_liuyu: {
		sex: "male",
		group: "qun",
		hp: 2,
		skills: ["xinzhige", "xinzongzuo"],
	},
	ol_zhangrang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xintaoluan"],
		trashBin: ["sex:male_castrated"],
	},
	zhangliang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["old_jijun", "old_fangtong"],
	},
	jsp_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["kuiwei", "yanzheng"],
	},
	old_machao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["zhuiji", "oldcihuai"],
	},
	vtb_xiaosha: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["vtbguisha", "vtbshuli"],
		names: "null|杀",
	},
	vtb_xiaoshan: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["vtbshanwu", "vtbxianli"],
		names: "null|闪",
	},
	vtb_xiaotao: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["vtbtaoyan", "vtbyanli"],
		names: "null|桃",
	},
	vtb_xiaole: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["vtbleyu", "vtbyuanli"],
		names: "null|乐",
	},
	vtb_xiaojiu: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["vtbmeiniang", "vtbyaoli"],
		names: "null|酒",
	},
	mateng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "xiongyi"],
	},
	tianfeng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["sijian", "gzsuishi"],
	},
	jiling: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["shuangren"],
	},
	kongrong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zymingshi", "lirang"],
	},
	jiangqing: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["zyshangyi"],
	},
	pk_sp_duyu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["pkwuku", "pksanchen"],
		groupBorder: "jin",
	},
	ps_lvbu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wushuang", "pssheji"],
	},
	ps_jiaxu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wansha", "psqupo", "psbaoquan"],
	},
	ps_machao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "tieji", "psweihou"],
	},
	ps2066_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["pszhiji", "psjiefeng", "kongcheng"],
		names: "诸葛|亮",
	},
	ps_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["psguanxing", "pslongyin"],
		names: "诸葛|亮",
	},
	ps_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["reguicai", "pshuxiao"],
		names: "司马|懿",
	},
	ps2068_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["refankui", "reguicai", "pszhonghu"],
		names: "司马|懿",
	},
	ps_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["psjianwei", "fangzhu", "songwei"],
		isZhugong: true,
	},
	ps_jin_simayi: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["smyyingshi", "psquanyi"],
		names: "司马|懿",
	},
	ps_caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["psliushang", "psqibu"],
	},
	ps1062_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["yingzi", "psoldshiyin"],
	},
	ps2080_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["psshiyin", "psquwu", "psliaozou"],
	},
	ps2063_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["psqijin", "psqichu", "pslongxin"],
	},
	ps2067_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longdan", "pshuiqiang", "pshuntu"],
	},
	ps1059_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tiandu", "psqizuo"],
	},
	ps2070_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yiji", "psquanmou"],
	},
	ps_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wusheng", "pszhonghun", "nuzhan"],
	},
	pe_wenqin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["gzjinfa"],
	},
	pe_sunchen: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["zyshilu", "zyxiongnve"],
	},
	pe_mengda: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qiuan", "liangfan"],
	},
	pe_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zyquanji", "zypaiyi"],
		clans: ["颍川钟氏"],
	},
	pe_wangyun: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zylianji", "zymoucheng"],
		clans: ["太原王氏"],
	},
	yj_zhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["yjluoshen", "qingguo"],
	},
	yj_jiaxu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yjzhenlve", "yjjianshu", "yjyongdi"],
	},
	yj_xuyou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["yjshicai", "yjchenggong", "yjzezhu"],
	},
	yj_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 7,
		skills: ["yjtuicheng", "yjyaoling", "yjshicha", "yjyongquan"],
		isZhugong: true,
	},
	yongjian_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["yjjielve"],
	},
	yj_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["yjmangji"],
	},
	yj_caohong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yjlifeng"],
	},
	yj_liru: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["yjdumou", "yjweiquan", "yjrenwang"],
	},
	yj_caocao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yjxiandao", "yjsancai", "yjyibing"],
	},
	longyufei: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["longyi", "zhenjue"],
	},
	sp_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["zhaolie", "shichou"],
		isZhugong: true,
	},
	sp_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jie", "dahe"],
	},
	sp_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["tanhu", "mouduan"],
	},
	sp_xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["fenyong", "xuehen"],
		names: "夏侯|惇",
	},
	sp_ganning: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yinling", "junwei"],
	},
	sp_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["yanxiao", "anxian"],
		names: "桥|null",
	},
	sp_pangtong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinmanjuan", "zuixiang"],
	},
	huangjinleishi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["fulu", "fuji"],
		names: "null|null-null|null",
	},
	jsp_zhaoyun: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["chixin", "reyicong", "suiren"],
	},
	sp_xiahoushi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["xinfu_yanyu", "xinfu_xiaode"],
		names: "夏侯|null",
	},
	sp_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["spyicong", "sptuji"],
		names: "公孙|瓒",
	},
	sp_simazhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["spzhaoxin", "splanggu"],
		names: "司马|昭",
		groupBorder: "jin",
	},
	sp_wangyuanji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["spfuluan", "spshude"],
		groupBorder: "jin",
	},
	sp_xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["spmingjian", "spyinzhi"],
	},
	sp_liuxie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["sphuangen", "sphantong"],
	},
	ns_lijue: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 6,
		skills: ["nsfeixiong", "nscesuan"],
	},
	ns_zhangji: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nslulve"],
	},
	ns_fanchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nsyangwu"],
	},
	ns_jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nsyice", "luanwu"],
	},
	ns_chendao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["nsjianglie"],
	},
	yj_caoang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yjxuepin"],
	},
	ns_caoanmin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["nskuishe"],
	},
	jsp_liubei: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jsprende"],
	},
	yj_jiling: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yjshuangren"],
	},
};

export default characters;
