const list = [
	/** 虚实篇 */
	// ["heart", 3, "zou"],
	// ["diamond", 6, "zou"],
	// ["club", 3, "zou"],
	// ["club", 6, "zou"],
	// ["spade", 3, "zou"],
	// ["heart", 10, "liang"],
	// ["diamond", 1, "liang"],
	// ["diamond", 10, "liang"],
	// ["heart", 2, "jin"],
	// ["diamond", 2, "jin"],
	// ["heart", 9, "sha", "poison"],
	// ["club", 4, "sha", "poison"],
	// ["club", 10, "sha", "poison"],
	// ["spade", 9, "sha", "poison"],
	["diamond", 9, "sha"],
	["spade", 6, "sha"],
	["heart", 6, "shan"],
	["diamond", 3, "shan"],
	["diamond", 11, "shan"],
	["heart", 5, "tao"],
	["heart", 7, "tao"],

	["heart", 4, "diaobingqianjiang"],
	["diamond", 4, "diaobingqianjiang"],
	// ["heart", 8, "yuqinguzong"],
	// ["diamond", 7, "yuqinguzong"],
	// ["diamond", 8, "yuqinguzong"],
	// ["spade", 8, "yuqinguzong"],
	["club", 9, "youdishenru"],
	["spade", 11, "youdishenru"],
	["spade", 12, "youdishenru"],
	// ["club", 1, "shuiyanqijun"],
	// ["club", 7, "shuiyanqijun"],
	// ["spade", 1, "shuiyanqijun"],
	// ["diamond", 13, "caochuanjiejian"],
	// ["spade", 13, "caochuanjiejian"],
	["club", 8, "wangmeizhike"],
	["club", 11, "wangmeizhike"],
	// ["heart", 11, "yangjingxurui"],
	["spade", 4, "tiesuo"],

	// ["spade", 7, "qixingdao"],
	// ["spade", 5, "fashiche"],
	// ["heart", 13, "riyueji"],
	// ["club", 12, "riyueji"],
	["club", 5, "sanjian"],
	// ["heart", 1, "huxinjing"],
	// ["spade", 10, "liannuzhanche"],
	// ["club", 13, "nanmanzhanxiang"],
	// ["diamond", 5, "baihu"],
];

export default list;
