const characters = {
	noname: {
		sex: "female",
		group: "key",
		hp: 3,
		skills: ["noname_zhuyuan", "noname_duocai"],
		names: "null|无",
	},
	ns_shijian: {
		sex: "female",
		group: "key",
		hp: 4,
		skills: ["nspianwu"],
	},

	ns_huangchengyan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["nslongyue", "nszhenyin"],
	},
	ns_sunchensunjun: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["nsxianhai", "nsxingchu"],
		names: "孙|綝-孙|峻",
	},
	ns_yuanxi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nsshengyan", "nsdaizhan"],
	},
	ns_caoshuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["nsjiquan", "nsfuwei"],
	},
	ns_sunyi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["nsguolie"],
	},
	ns_huangwudie: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["nsdiewu", "nslingying", "nspojian"],
	},
	ns_chentai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["nsweiyuan", "nsjuxian"],
	},
	ns_zhangning: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["nsfuzhou", "nsguidao", "nstaiping"],
	},
	ns_yanghu: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["nsbizhao", "nsqingde", "nsyidi"],
		hasHiddenSkill: true,
	},
	ns_zanghong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nsshimeng"],
	},
	ns_ruanji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["nsshizui", "nsxiaoye"],
	},
	ns_limi: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["nstuilun"],
	},
	ns_zhonglimu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["nskuanhuai", "nsdingbian"],
		names: "钟离|牧",
	},
	prp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["nsxingyun", "nshanlang"],
		names: "诸葛|亮",
	},

	ns_zhangwei: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["nsqiyue", "nsxuezhu"],
	},
	diy_wenyang: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 6,
		skills: ["lvli", "choujue"],
	},

	ns_zuoci: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nsxinsheng", "nsdunxing"],
	},
	ns_lvzhi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["nsnongquan", "nsdufu"],
		names: "吕|雉",
	},
	ns_wangyun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["liangji", "jugong", "chengmou"],
	},
	ns_nanhua: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nshuanxian", "nstaiping_nh", "nsshoudao"],
		names: "庄|周",
	},
	ns_nanhua_left: {
		sex: "male",
		group: "qun",
		hp: 2,
		skills: [],
		isUnseen: true,
		names: "null|null",
	},
	ns_nanhua_right: {
		sex: "female",
		group: "qun",
		hp: 2,
		skills: [],
		isUnseen: true,
		names: "null|null",
	},
	ns_huamulan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["nscongjun", "xiaoji", "gongji"],
		names: "null|null",
	},
	ns_huangzu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nsjihui", "nsmouyun"],
	},
	ns_jinke: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nspinmin", "nsshishou"],
		names: "姜|荆轲",
	},
	ns_yanliang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nsduijue", "nsshuangxiong", "dualside"],
		dualSideCharacter: "ns_wenchou",
	},
	ns_wenchou: {
		sex: "male",
		group: "qun",
		hp: 2,
		skills: ["nsguanyong", "dualside"],
		isUnseen: true,
	},

	ns_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["nscaiyi", "nsgefa", "nshaoling"],
	},
	ns_caocaosp: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nsjianxiong", "nsxionglue"],
	},
	ns_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["nsguanxing", "kongcheng", "nsyunxing"],
		names: "诸葛|亮",
	},
	ns_wangyue: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nsjianshu", "nscangjian"],
	},
	ns_yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nsyaowang", "nshuanhuo"],
	},
	ns_xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["nsdongcha", "nscaijian", "nsgongjian"],
	},
	ns_guanlu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["nsbugua", "nstuiyan", "nstianji"],
	},
	ns_simazhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["nszhaoxin", "nsxiuxin", "nsshijun"],
		names: "司马|昭",
	},
	ns_sunjian: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["nswulie", "nshunyou", "nscangxi"],
	},

	ns_duangui: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nscuanquan", "nsjianning", "nschangshi", "nsbaquan"],
	},
	ns_zhangbao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nsfuhuo", "nswangfeng"],
	},
	ns_masu: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["nstanbing", "nsxinzhan"],
	},
	ns_zhangxiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nsbaiming", "nsfuge"],
	},
	ns_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["nsqinxue", "nsbaiyi"],
	},
	ns_shenpei: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nshunji", "shibei"],
	},

	ns_yujisp: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nsguhuo"],
	},
	ns_yangyi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["nsjuanli", "nsyuanchou"],
	},
	ns_liuzhang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nsanruo", "nsxunshan", "nskaicheng"],
	},
	ns_xinnanhua: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["ns_xiandao", "ns_xiuzheng", "ns_chuanshu"],
		names: "庄|周",
	},
	ns_caimao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nsdingzhou"],
	},
	ns_luyusheng: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["nshuaishuang", "nsfengli"],
		clans: ["吴郡陆氏"],
	},
	ns_chengpu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["decadelihuo", "decadechunlao"],
	},
	ns_sundeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xinkuangbi"],
	},
	ns_duji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xinfu_andong", "xinyingshi"],
	},
	ns_mengyou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["nsmanzhi"],
	},

	junk_zhangrang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["junktaoluan"],
		trashBin: ["sex:male_castrated"],
	},
	old_bulianshi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["anxu", "zhuiyi"],
	},
	ol_maliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zishu", "xinyingyuan"],
	},
	junk_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["junkrende", "jijiang"],
		isZhugong: true,
	},
	junk_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["junkjizhi", "junkqicai"],
	},
	junk_lidian: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xunxun", "junkwangxi"],
	},
	junk_duanwei: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["langmie"],
	},
	junk_xuyou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nzry_chenglve", "junkshicai", "nzry_cunmu"],
	},
	junk_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olsbfumeng", "olsbguidao"],
	},
	junk_liuyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 6,
		skills: ["olpianan", "olyinji", "olkuisi"],
	},
	zhangren: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["chuanxin", "zfengshi"],
		//xdm我打赢复活赛了，虽然在垃圾桶里
	},
};

export default characters;
