const translate = {
	land: "地图",
	mtg_yixialan: "依夏兰",
	mtg_yixialan_skill: "依夏兰",
	mtg_yixialan_info: "选项一：随机获得一张基本牌；选项二：随机获得一张锦囊牌。地图效果：出牌阶段限一次，你可以将一张基本牌重铸为锦囊牌。",
	mtg_yixialan_skill_info: "出牌阶段限一次，你可以将一张基本牌重铸为锦囊牌。",
	mtg_shuimomuxue: "水没墓穴",
	mtg_shuimomuxue_skill: "水没墓穴",
	mtg_shuimomuxue_info: "你可以弃置一张牌并摸两张牌。地图效果：锁定技，你的手牌上限-1；若弃牌阶段弃置了至少一张牌，则在此阶段结束时摸一张牌。",
	mtg_shuimomuxue_skill_info: "锁定技，你的手牌上限-1；若弃牌阶段弃置了至少一张牌，则在此阶段结束时摸一张牌。",
	mtg_feixu: "废墟",
	mtg_feixu_skill: "废墟",
	mtg_feixu_info: "从弃牌堆中发现一张牌。地图效果：准备阶段，随机将弃牌堆的一张牌置于牌堆顶。",
	mtg_feixu_skill_info: "准备阶段，随机将弃牌堆的一张牌置于牌堆顶。",
	mtg_haidao: "海岛",
	mtg_haidao_skill: "海岛",
	mtg_haidao_info: "选项一：获得1点护甲（无视地图效果）；选项二：弃置一张牌并回复1点体力。地图效果：锁定技，当你获得护甲时，若你已受伤，改为回复等量体力。",
	mtg_haidao_skill_info: "锁定技，当你获得护甲时，若你已受伤，改为回复等量体力。",
	mtg_youlin: "幽林",
	mtg_youlin_skill: "幽林",
	mtg_youlin_info: "随机使用一张普通锦囊牌，随机指定一个具有正收益的目标。地图效果：出牌阶段限一次，你可以弃置一张锦囊牌并发现一张牌。",
	mtg_youlin_skill_info: "出牌阶段限一次，你可以弃置一张锦囊牌并发现一张牌。",
	mtg_shamolvzhou: "沙漠绿洲",
	mtg_shamolvzhou_skill: "沙漠绿洲",
	mtg_shamolvzhou_info: "发现一张基本牌。地图效果：你的基本牌不计入手牌上限。",
	mtg_shamolvzhou_skill_info: "你的基本牌不计入手牌上限。",

	mtg_duzhao: "毒沼",
	mtg_duzhao_skill: "毒沼",
	mtg_duzhao_info: "选择一名角色令其获得一张毒。地图效果：结束阶段，你获得一张毒。",
	mtg_duzhao_skill_info: "结束阶段，你获得一张毒。",
	mtg_linzhongjianta: "林中尖塔",
	mtg_linzhongjianta_skill: "林中尖塔",
	mtg_linzhongjianta_info: "发现一张武器牌并装备之。地图效果：若你装备区内有武器牌，你可以将一张基本牌当作杀使用。",
	mtg_linzhongjianta_skill_info: "若你装备区内有武器牌，你可以将一张基本牌当作杀使用。",
	mtg_cangbaohaiwan: "藏宝海湾",
	mtg_cangbaohaiwan_skill: "藏宝海湾",
	mtg_cangbaohaiwan_info: "选择一个扩展包，随机获得来自该扩展包的一张衍生牌。地图效果：你在摸牌时有可能摸到衍生牌。",
	mtg_cangbaohaiwan_skill_info: "你在摸牌时有可能摸到衍生牌。",
	mtg_longlushanfeng: "龙颅山峰",
	mtg_longlushanfeng_skill: "龙颅山峰",
	mtg_longlushanfeng_info: "选项一：获得一张杀；选项二：获得一张闪。地图效果：你出杀的次数上限+1。",
	mtg_longlushanfeng_skill_info: "你出杀的次数上限+1。",
	mtg_bingheyaosai: "冰河要塞",
	mtg_bingheyaosai_skill: "冰河要塞",
	mtg_bingheyaosai_info: "摸两张牌，然后弃置两张牌。地图效果：锁定技，每当你使用一张杀，若你有牌，则需弃置一张牌。",
	mtg_bingheyaosai_skill_info: "锁定技，每当你使用一张杀，若你有牌，则需弃置一张牌。",
	mtg_lindixiliu: "林地溪流",
	mtg_lindixiliu_skill: "林地溪流",
	mtg_lindixiliu_info: "从牌堆中摸一张红桃牌，然后弃置任意张红桃牌，每弃置一张牌，将一张延时锦囊牌置入一名随机敌方角色的判定区。地图效果：准备阶段，你可以弃置一张红桃牌，然后弃置判定区内的一张牌。",
	mtg_lindixiliu_skill_info: "准备阶段，你可以弃置一张红桃牌，然后弃置判定区内的一张牌。",
};

export default translate;
