window.noname_character_perfectPairs = {
	bailingyun: ["jin_simayi", "new_jin_simayi"],
	bulianshi: ["sunquan"],
	caifuren: ["liubiao"],
	caoang: ["caocao"],
	caocao: ["xuzhu", "dianwei", "bianfuren"],
	caohong: ["caoren"],
	caopi: ["zhenji", "cuimao", "luzhi"],
	caoying: ["caocao", "caopi"],
	caozhi: ["zhenji"],
	chengong: ["lvbu"],
	chengpu: ["zhouyu"],
	cuiyan: ["caocao"],
	daqiao: ["xiaoqiao"],
	daxiaoqiao: ["zhouyu", "sunce"],
	dingfeng: ["xusheng", "re_xusheng", "zhugeke"],
	dongzhuo: ["liru", "dongbai", "xurong"],
	fuhuanghou: ["liuxie"],
	fuwan: ["fuhuanghou"],
	gaolan: ["yj_zhanghe"],
	ganning: ["lingtong", "xf_sufei"],
	guanping: ["guanyu"],
	guanqiujian: ["wenqin"],
	guansuo: ["guanyu"],
	guanyinping: ["guanyu"],
	guanyu: ["zhangfei", "liaohua", "guanyinping"],
	huangzhong: ["weiyan"],
	jiangqing: ["zhoutai"],
	jiangwei: ["xiahouba"],
	jiaxu: ["liqueguosi"],
	jin_guohuai: ["jin_jiachong"],
	jin_simashi: ["jin_xiahouhui", "jin_yanghuiyu"],
	jin_simayi: ["jin_zhangchunhua", "shibao", "new_jin_zhangchunhua"],
	jin_simazhao: ["jin_wangyuanji"],
	jin_yanghu: ["duyu"],
	key_ao: ["key_inari"],
	key_chihaya: ["key_sakuya"],
	key_doruji: ["key_rin"],
	key_hinata: ["key_yui"],
	key_iwasawa: ["key_hisako"],
	key_jojiro: ["key_yusa"],
	key_kaori: ["key_shiori"],
	key_komari: ["key_rin", "key_sasami"],
	key_kud: ["key_harukakanata"],
	key_lucia: ["key_shizuru"],
	key_masato: ["key_kengo"],
	key_riki: ["key_rin", "key_saya", "key_kyousuke", "key_kud"],
	key_shiroha: ["key_umi"],
	key_shizuku: ["key_tsumugi"],
	key_tomoya: ["key_nagisa", "key_sunohara", "key_kotomi"],
	key_yuiko: ["key_harukakanata"],
	key_yuri: ["key_kanade", "key_abyusa"],
	key_yuu: ["key_nao"],
	key_yuzuru: ["key_hinata", "key_kanade", "key_ayato"],
	lijue: ["guosi", "jiaxu"],
	lingcao: ["lingtong"],
	lingju: ["diaochan", "lvbu"],
	lingtong: ["ganning"],
	liubei: ["guanyu", "zhangfei", "ganfuren", "fazheng"],
	liuchen: ["liushan"],
	lukang: ["luxun"],
	lvbu: ["diaochan", "lvlingqi"],
	machao: ["madai", "mayunlu", "yangwan"],
	maliang: ["masu"],
	mateng: ["machao", "madai", "mayunlu"],
	menghuo: ["zhurong"],
	nanhualaoxian: ["zuoci", "yuji"],
	new_jin_simayi: ["jin_zhangchunhua", "shibao", "new_jin_zhangchunhua"],
	pangtong: ["zhugejin"],
	re_guohuai: ["xiahouyuan", "zhanghe"],
	re_nanhualaoxian: ["zuoci", "yuji"],
	re_xushu: ["zhaoyun", "sp_zhugeliang"],
	re_yuanshao: ["yanwen", "tianfeng", "yanliang", "wenchou"],
	simahui: ["pangdegong"],
	simazhao: ["wangyuanji", "simayi"],
	sp_zhugeliang: ["pangtong", "huangyueying"],
	sunben: ["zhouyu", "taishici", "re_taishici", "daqiao"],
	sunce: ["zhouyu", "taishici", "re_taishici", "daqiao"],
	sundeng: ["sunquan", "zhoufei"],
	sunluban: ["quancong"],
	sunquan: ["zhoutai"],
	sunshangxiang: ["liubei"],
	sunxiù: ["simalun"],
	taishici: ["liuyao", "kongrong"],
	tw_liufuren: ["yuanshao"],
	tw_xiahoushang: ["caopi"],
	wangping: ["jiangfei"],
	wuguotai: ["sunjian", "ol_sb_sunjian", "sunshangxiang"],
	wujing: ["sunce", "sunben", "wuguotai"],
	xf_sufei: ["ganning"],
	xiahoudun: ["xiahouyuan", "yujin"],
	xiahoushi: ["zhangfei"],
	xuangongzhu: ["duyu"],
	xugong: ["yanbaihu"],
	xunyou: ["xunyu"],
	//xushu: ["liubei"],
	yuanshu: ["jiling"],
	yuejin: ["re_lidian"],
	yuji: ["zuoci"],
	zhangbao: ["zhangliang", "zhangjiao"],
	zhangchunhua: ["simayi"],
	zhangji: ["zhangxiu", "zoushi"],
	zhangliang: ["zhangjiao"],
	zhangliao: ["zangba"],
	zhangqiying: ["zhanglu"],
	zhangxingcai: ["liushan"],
	zhangxiu: ["jiaxu"],
	zhangxuan: ["zhangyao"],
	zhaoyun: ["liushan"],
	zhonghui: ["jiangwei"],
	zhoucang: ["guanyu"],
	zhouyu: ["huanggai", "xiaoqiao", "zhouyi"],
	zhugejin: ["zhugeke", "sunquan"],
	zhugeliang: ["jiangwei", "jiangfei", "huangyueying"],
	zuoci: ["yuji"],
};
