window.noname_character_replace = {
	//大致按照OL，新杀，手杀，外服，线下，DIY，怀旧的顺序排列。（同服按标，界，谋，sp）
	key_yuri: ["key_yuri", "sp_key_yuri"],
	sp_key_kanade: ["sp_key_kanade", "kanade"],
	shen_caocao: ["shen_caocao", "old_caocao", "ca_shen_caocao"],
	shen_guanyu: ["shen_guanyu", "tw_shen_guanyu", "ty_shen_guanyu"],
	shen_huatuo: ["dc_shen_huatuo", "shen_huatuo"],
	shen_jiaxu: ["le_shen_jiaxu", "shen_jiaxu", "zombie_jiaxu"],
	shen_liubei: ["shen_liubei", "ty_shen_liubei"],
	shen_lvmeng: ["shen_lvmeng", "tw_shen_lvmeng"],
	shen_machao: ["shen_machao", "ps_shen_machao", "wn_shen_machao", "mark_shen_machao"],
	shen_simayi: ["shen_simayi", "xin_simayi", "new_simayi"],
	shen_sunquan: ["shen_sunquan", "junk_sunquan"],
	shen_xuzhu: ["shen_xuzhu", "wn_shen_xuzhu"],
	shen_zhangfei: ["shen_zhangfei", "ty_shen_zhangfei"],
	shen_zhangliao: ["ol_zhangliao", "shen_zhangliao"],
	shen_zhangjiao: ["junk_zhangjiao", "shen_zhangjiao", "hm_shen_zhangjiao"],
	shen_zhaoyun: ["shen_zhaoyun", "dc_zhaoyun", "boss_zhaoyun", "old_shen_zhaoyun"],
	baosanniang: ["baosanniang", "xin_baosanniang", "re_baosanniang", "std_baosanniang", "sy_baosanniang", "fx_baosanniang"],
	baoxin: ["baoxin", "tw_baoxin", "std_baoxin"],
	beimihu: ["beimihu", "tw_beimihu"],
	bulianshi: ["bulianshi", "dc_bulianshi", "re_bulianshi", "old_bulianshi"],
	buzhi: ["buzhi", "ty_buzhi"],
	caifuren: ["caifuren", "ol_caifuren", "re_caifuren", "xin_caifuren"],
	caimao: ["caimao", "ns_caimao"],
	caiwenji: ["caiwenji", "sp_caiwenji", "ol_caiwenji", "re_caiwenji", "yue_caiwenji"],
	caiyong: ["caiyong", "re_caiyong", "yue_caiyong"],
	caizhenji: ["caizhenji", "ol_caizhenji"],
	caoang: ["caoang", "dc_sb_caoang", "tw_caoang", "huan_caoang", "yj_caoang"],
	caoanmin: ["caoanmin", "ns_caoanmin"],
	caocao: ["caocao", "re_caocao", "sp_ol_caocao", "ol_jsrg_caocao", "dc_caocao", "sb_caocao", "tw_caocao", "jsrg_caocao", "jd_sb_caocao", "yj_caocao", "ns_caocao", "ns_caocaosp", "jy_caocao", "ps_caocao", "sxrm_caocao", "wn_caocao", "pe_jun_caocao"],
	caochong: ["caochong", "ol_caochong", "re_caochong", "huan_caochong", "old_caochong", "strong_caochong"],
	caochun: ["caochun", "dc_caochun", "old_caochun"],
	caofang: ["caofang", "jsrg_caofang"],
	caohong: ["caohong", "dc_sb_caohong", "tw_re_caohong", "tw_caohong", "yj_caohong", "mb_caohong"],
	caomao: ["caomao", "mb_caomao"],
	caopi: ["caopi", "v_caopi", "re_caopi", "sb_caopi", "tw_sb_caopi", "huan_caopi", "ps_caopi", "sxrm_caopi", "pe_jun_caopi", "xia_caopi"],
	caoren: ["caoren", "old_caoren", "sp_caoren", "star_caoren", "sb_caoren", "jsp_caoren", "drag_caoren", "new_caoren", "jy_caoren"],
	caorui: ["caorui", "re_caorui", "std_caorui", "yy_caorui", "old_caorui"],
	caoshuang: ["caoshuang", "dc_caoshuang", "ns_caoshuang"],
	caosong: ["caosong", "sp_caosong"],
	caoxiu: ["caoxiu", "re_caoxiu", "xin_caoxiu", "tw_caoxiu", "old_caoxiu"],
	caoxing: ["caoxing", "mb_caoxing"],
	caoying: ["caoying", "scl_caoying"],
	caozhang: ["caozhang", "ol_caozhang", "re_caozhang", "xin_caozhang"],
	caozhen: ["caozhen", "re_caozhen", "xin_caozhen", "old_caozhen", "std_caozhen"],
	caozhi: ["caozhi", "ol_caozhi", "dc_caozhi", "re_caozhi", "huan_caozhi", "ps_caozhi"],
	cenhun: ["cenhun", "shi_cenhun", "std_cenhun"],
	chendao: ["chendao", "pot_chendao", "ns_chendao", "old_chendao"],
	chendeng: ["chendeng", "ol_chendeng", "re_chendeng", "jsrg_chendeng"],
	chendong: ["chendong", "sp_chendong", "tw_chendong"],
	chengong: ["chengong", "re_chengong", "sb_chengong"],
	chengpu: ["chengpu", "ol_chengpu", "xin_chengpu", "re_chengpu", "tw_chengpu", "std_chengpu", "ns_chengpu"],
	chengui: ["chengui", "mb_chengui"],
	chengyu: ["chengyu", "dc_sb_chengyu", "std_chengyu"],
	chenlin: ["chenlin", "dc_sb_chenlin"],
	chenqun: ["chenqun", "dc_chenqun", "re_chenqun", "old_chenqun"],
	chenshi: ["chenshi", "ty_chenshi"],
	cuiyan: ["cuiyan", "sp_cuiyan"],
	chunyuqiong: ["chunyuqiong", "re_chunyuqiong", "jsrg_chunyuqiong"],
	daqiao: ["daqiao", "re_daqiao", "yue_daqiao", "sb_daqiao", "jd_sb_daqiao", "sp_daqiao"],
	daxiaoqiao: ["daxiaoqiao", "dc_daxiaoqiao", "tw_daxiaoqiao"],
	dengai: ["dengai", "ol_dengai", "ol_sb_dengai", "re_dengai", "jsrg_dengai", "ren_dengai", "dc_sb_dengai"],
	dengzhi: ["ol_dengzhi", "re_dengzhi", "dengzhi", "tw_dengzhi", "std_re_dengzhi"],
	dianwei: ["dianwei", "ol_dianwei", "dc_sb_dianwei", "re_dianwei", "xia_dianwei", "huan_dianwei"],
	diaochan: ["diaochan", "re_diaochan", "sp_diaochan", "dm_diaochan", "yue_diaochan", "sb_diaochan"],
	dingfeng: ["dingfeng", "star_dingfeng", "tw_dingfeng", "std_dingfeng", "old_dingfeng"],
	dingshangwan: ["dingshangwan", "ol_dingshangwan", "huan_dingshangwan"],
	dingyuan: ["ol_dingyuan", "dingyuan"],
	dongbai: ["dongbai", "re_dongbai", "jsrg_dongbai"],
	dongcheng: ["re_dongcheng", "dc_sb_dongcheng", "dongcheng"],
	dongxie: ["ol_dongxie", "dongxie"],
	dongzhuo: ["dongzhuo", "ol_dongzhuo", "ol_sb_dongzhuo", "star_dongzhuo", "v_dongzhuo", "re_dongzhuo", "new_yj_dongzhuo", "jsrg_dongzhuo", "sp_dongzhuo", "yj_dongzhuo"],
	duanwei: ["duanwei", "junk_duanwei"],
	duji: ["duji", "re_duji", "ns_duji"],
	duyu: ["duyu", "dc_duyu", "sp_duyu", "pk_sp_duyu"],
	fanchou: ["fanchou", "tw_fanchou", "ns_fanchou", "ca_fanchou"],
	fanjiangzhangda: ["fanjiangzhangda", "jsrg_fanjiangzhangda"],
	fanyufeng: ["fanyufeng", "std_fanyufeng"],
	fazheng: ["xin_fazheng", "ol_fazheng", "re_fazheng", "star_fazheng", "sb_fazheng", "tw_re_fazheng", "fazheng", "jd_sb_fazheng"],
	feiyi: ["ol_feiyi", "feiyi", "tw_feiyi", "std_feiyi"],
	fengfangnv: ["fengfangnv", "re_fengfangnv"],
	fuhuanghou: ["fuhuanghou", "ol_fuhuanghou", "re_fuhuanghou", "xin_fuhuanghou", "tw_fuhuanghou", "std_fuhuanghou", "sp_fuhuanghou", "old_fuhuanghou", "sxrm_fuhuanghou"],
	furong: ["ol_furong", "furong", "tw_furong"],
	fuwan: ["fuwan", "tw_fuwan", "sp_fuwan"],
	ganfuren: ["ganfuren", "dc_ganfuren", "mb_ganfuren", "jsp_ganfuren"],
	ganning: ["ganning", "re_ganning", "sb_ganning", "yj_ganning", "yongjian_ganning", "jd_sb_ganning", "sp_ganning", "ty_ganning"],
	gaolan: ["gaolan", "dc_gaolan", "sp_gaolan"],
	gaoshun: ["gaoshun", "ol_gaoshun", "xin_gaoshun", "re_gaoshun", "sb_gaoshun", "old_gaoshun"],
	gaoxiang: ["gaoxiang", "jsrg_gaoxiang"],
	gexuan: ["gexuan", "tw_gexuan"],
	gongsunyuan: ["gongsunyuan", "re_gongsunyuan", "std_gongsunyuan", "yy_gongsunyuan"],
	gongsunzan: ["gongsunzan", "re_gongsunzan", "ol_sb_gongsunzan", "dc_gongsunzan", "xin_gongsunzan", "sb_gongsunzan", "sp_gongsunzan", "yy_gongsunzan"],
	guanlu: ["guanlu", "ns_guanlu"],
	guanping: ["guanping", "re_guanping", "dc_sb_guanping", "drag_guanping"],
	guanqiujian: ["guanqiujian", "re_guanqiujian", "mb_sp_guanqiujian", "tw_guanqiujian", "old_guanqiujian"],
	guansuo: ["guansuo", "dc_guansuo", "std_guansuo", "drag_guansuo"],
	guanyinping: ["guanyinping", "mb_guanyinping", "old_guanyinping", "ty_guanyinping", "drag_guanyinping"],
	guanyu: ["guanyu", "re_guanyu", "jsp_guanyu", "ol_sb_guanyu", "wu_guanyu", "dc_jsp_guanyu", "sb_guanyu", "tw_jsp_guanyu", "xia_guanyu", "jsrg_guanyu", "jd_sb_guanyu", "drag_guanyu", "ty_guanyu", "jx_guanyu", "ps_guanyu", "old_guanyu", "junk_guanyu"],
	guanzhang: ["guanzhang", "ol_guanzhang", "re_guanzhang", "old_guanzhang"],
	guohuai: ["guohuai", "re_guohuai", "ol_guohuai", "xin_guohuai", "sb_guohuai", "tw_guohuai"],
	guohuanghou: ["guohuanghou", "ol_guohuanghou", "re_guohuanghou", "std_guohuanghou", "ol_guohuanghou"],
	guojia: ["guojia", "re_guojia", "yj_sb_guojia", "sb_guojia", "jsrg_guojia", "ps1059_guojia", "ps2070_guojia"],
	guosi: ["guosi", "ca_guosi"],
	guotufengji: ["guotufengji", "re_guotufengji"],
	guozhao: ["ol_guozhao", "guozhao", "xin_guozhao", "jsrg_guozhao", "std_guozhao"],
	guyong: ["guyong", "re_guyong", "xin_guyong", "tw_guyong"],
	handang: ["handang", "xin_handang", "re_handang", "sb_handang", "tw_handang", "old_handang"],
	hanfu: ["hanfu", "ol_hanfu"],
	hanhaoshihuan: ["hanhaoshihuan", "re_hanhaoshihuan"],
	hanlong: ["hanlong", "jd_hanlong"],
	hansui: ["hansui", "re_hansui", "xin_hansui", "jsrg_hansui", "wn_hansui"],
	haomeng: ["haomeng", "tw_haomeng"],
	hejin: ["hejin", "re_hejin", "tw_hejin", "jsrg_hejin"],
	heqi: ["re_heqi", "heqi"],
	huaman: ["huaman", "sp_huaman"],
	huangchengyan: ["huangchengyan", "dc_huangchengyan", "ns_huangchengyan"],
	huangfusong: ["huangfusong", "wu_huangfusong", "sp_huangfusong", "jsrg_huangfusong", "std_huangfusong", "old_huangfusong"],
	huanggai: ["huanggai", "re_huanggai", "dc_sb_huanggai", "sb_huanggai", "huan_huanggai", "jy_huanggai"],
	huanghao: ["huanghao", "dc_huanghao", "old_huanghao"],
	huangyueying: ["huangyueying", "re_huangyueying", "jsp_huangyueying", "ol_sb_huangyueying", "re_jsp_huangyueying", "sb_huangyueying", "jd_sb_huangyueying", "junk_huangyueying"],
	huangzhong: ["re_huangzhong", "ol_huangzhong", "sb_huangzhong", "yj_huangzhong", "jsrg_huangzhong", "ty_huangzhong", "huangzhong"],
	huangzu: ["huangzu", "dc_huangzu", "mb_huangzu", "ns_huangzu"],
	huatuo: ["huatuo", "re_huatuo", "old_huatuo", "sxrm_huatuo"],
	huaxin: ["ol_huaxin", "huaxin", "sp_huaxin", "std_huaxin", "jd_ol_huaxin"],
	huaxiong: ["huaxiong", "re_huaxiong", "ol_huaxiong", "ol_sb_huaxiong", "sb_huaxiong", "old_huaxiong"],
	hucheer: ["re_hucheer", "dc_sb_hucheer", "hucheer", "tw_hucheer"],
	hujinding: ["ol_hujinding", "hujinding", "dc_hujinding"],
	huojun: ["huojun", "dc_huojun", "xin_huojun", "tw_huojun"],
	jiachong: ["jin_jiachong", "dc_jiachong", "mb_jiachong", "jiachong"],
	jiakui: ["jiakui", "old_jiakui", "std_jiakui"],
	jianggan: ["jianggan", "sp_jianggan", "std_jianggan", "sxrm_jianggan"],
	jiangji: ["dc_jiangji", "tw_jiangji", "jiangji"],
	jiangqing: ["dc_jiangqing", "sp_jiangqing", "tw_jiangqing", "jiangqing"],
	jiangwei: ["jiangwei", "ol_jiangwei", "re_jiangwei", "ol_sb_jiangwei", "sp_jiangwei", "dc_sb_jiangwei", "sb_jiangwei", "huan_jiangwei", "jsrg_jiangwei", "jd_sb_jiangwei", "ren_jiangwei"],
	jianyong: ["jianyong", "ol_jianyong", "re_jianyong", "xin_jianyong"],
	jiaxu: ["jiaxu", "re_jiaxu", "sp_jiaxu", "ol_sb_jiaxu", "dc_sb_jiaxu", "dc_sp_jiaxu", "sb_jiaxu", "yj_jiaxu", "ps_jiaxu", "ns_jiaxu", "wn_jiaxu"],
	jikang: ["jikang", "re_jikang", "dc_jikang"],
	jiling: ["jiling", "dc_jiling", "tw_jiling", "std_jiling", "yj_jiling"],
	kanze: ["kanze", "re_kanze"],
	kebineng: ["kebineng", "ol_kebineng"],
	kongrong: ["ol_sb_kongrong", "dc_kongrong", "sp_kongrong", "jsrg_kongrong", "kongrong", "std_kongrong"],
	liaohua: ["liaohua", "ol_liaohua", "xin_liaohua", "re_liaohua", "ty_liaohua", "drag_liaohua"],
	lifeng: ["ol_lifeng", "dc_lifeng", "lifeng"],
	lijue: ["lijue", "std_lijue", "ns_lijue", "ca_lijue"],
	lingcao: ["lingcao", "dc_lingcao"],
	lingju: ["lingju", "old_lingju"],
	lingtong: ["lingtong", "ol_lingtong", "re_lingtong", "xin_lingtong", "old_lingtong"],
	liru: ["xin_liru", "ol_liru", "dc_liru", "re_liru", "std_liru", "yj_liru", "liru", "wild_liru"],
	lisu: ["ol_lisu", "lisu"],
	liuba: ["ol_liuba", "dc_liuba", "liuba", "std_liuba"],
	liubei: ["liubei", "re_liubei", "sp_ol_liubei", "dc_liubei", "sb_liubei", "xia_liubei", "jsrg_liubei", "jd_sb_liubei", "ty_liubei", "sp_liubei", "jsp_liubei", "junk_liubei", "ps_liubei", "sxrm_liubei", "pe_jun_liubei"],
	liubiao: ["liubiao", "ol_liubiao", "xin_liubiao", "re_liubiao", "sb_liubiao", "jsrg_liubiao", "std_liubiao", "old_liubiao", "oldre_liubiao"],
	liuchen: ["liuchen", "re_liuchen", "std_liuchen"],
	liufeng: ["liufeng", "re_liufeng", "huan_liufeng"],
	liuhong: ["liuhong", "ol_jsrg_liuhong", "tw_liuhong", "jsrg_liuhong", "pe_jun_liuhong"],
	liupi: ["ol_liupi", "liupi"],
	liushan: ["liushan", "ol_liushan", "re_liushan", "huan_liushan", "pe_jun_liushan"],
	liuxie: ["liuxie", "dc_sb_liuxie", "sp_liuxie", "std_liuxie", "hs_liuxie", "pe_jun_liuxie"],
	liuyan: ["liuyan", "jsrg_liuyan", "junk_liuyan"],
	liuye: ["dc_liuye", "liuye", "std_liuye"],
	liuyong: ["liuyong", "jsrg_liuyong"],
	liuyu: ["liuyu", "ol_liuyu", "dc_liuyu"],
	liuzan: ["re_liuzan", "liuzan", "std_liuzan"],
	liuzhang: ["liuzhang", "ol_liuzhang", "tw_liuzhang", "std_liuzhang", "ns_liuzhang"],
	liyan: ["liyan", "old_liyan"],
	liwan: ["ol_liwan", "liwan"],
	liwei: ["liwei", "tw_liwei"],
	luji: ["luji", "clan_luji"],
	lukai: ["ol_lukai", "lukai"],
	lukang: ["lukang", "wu_lukang", "jsrg_lukang"],
	luotong: ["dc_luotong", "luotong", "std_dc_luotong", "scl_luotong", "dc_sb_luotong"],
	luxun: ["luxun", "re_luxun", "wu_luxun", "dc_sb_lunxun", "sb_luxun", "jsrg_luxun", "huan_luxun", "ty_luxun", "drag_luxun"],
	luyusheng: ["ol_luyusheng", "luyusheng", "mb_luyusheng", "ns_luyusheng"],
	lvboshe: ["lvboshe", "sxrm_lvboshe"],
	lvbu: ["lvbu", "re_lvbu", "ol_jsrg_lvbu", "dm_lvbu", "v_lvbu", "sb_lvbu", "jsrg_lvbu", "ps_lvbu", "ca_lvbu"],
	lvfan: ["lvfan", "sp_lvfan", "std_lvfan"],
	lvkuanglvxiang: ["lvkuanglvxiang", "dc_lvkuanglvxiang"],
	lvlingqi: ["lvlingqi", "std_lvlingqi"],
	lvmeng: ["lvmeng", "re_lvmeng", "sb_lvmeng", "sp_lvmeng", "ns_lvmeng", "she_lvmeng"],
	machao: ["machao", "re_machao", "sp_machao", "dc_sp_machao", "one_dc_sp_machao", "two_dc_sp_machao", "sb_machao", "jsrg_machao", "ps_machao", "old_machao"],
	madai: ["old_madai", "ol_madai", "re_madai", "tw_madai", "madai"],
	majun: ["majun", "yj_majun", "cx_majun", "qq_majun"],
	maliang: ["ol_maliang", "maliang", "re_maliang", "tw_maliang", "std_maliang", "old_maliang"],
	mamidi: ["mamidi", "xin_mamidi"],
	manchong: ["manchong", "re_manchong"],
	masu: ["xin_masu", "re_masu", "masu", "ns_masu"],
	mateng: ["dc_mateng", "tw_mateng", "std_mateng", "mateng"],
	mayunlu: ["mayunlu", "tw_mayunlu", "std_mayunlu"],
	mazhong: ["mazhong", "re_mazhong", "tw_mazhong"],
	menghuo: ["menghuo", "re_menghuo", "sb_menghuo", "sp_menghuo", "dc_sp_menghuo", "jd_sb_menghuo"],
	mengyou: ["mengyou", "ns_mengyou"],
	miheng: ["ol_miheng", "yue_miheng", "re_miheng", "miheng", "scl_miheng"],
	mushun: ["mushun", "sp_mushun"],
	nanhualaoxian: ["ol_nanhualaoxian", "re_nanhualaoxian", "nanhualaoxian", "jsrg_nanhualaoxian", "hm_nanhualaoxian", "std_nanhualaoxian", "ns_nanhua", "ns_xinnanhua"],
	niufu: ["ol_niufu", "niufu"],
	niujin: ["niujin", "re_niujin", "tw_niujin"],
	panfeng: ["panfeng", "re_panfeng", "std_panfeng"],
	pangde: ["ol_pangde", "sp_pangde", "re_pangde", "drag_pangde", "pangde"],
	pangdegong: ["re_pangdegong", "pangdegong", "scl_pangdegong", "std_pangdegong"],
	pangtong: ["pangtong", "ol_pangtong", "ol_sb_pangtong", "re_jsp_pangtong", "re_pangtong", "sb_pangtong", "friend_pangtong", "jsrg_pangtong", "jd_sb_pangtong", "sp_pangtong", "jy_pangtong"],
	panshu: ["panshu", "re_panshu"],
	panzhangmazhong: ["panzhangmazhong", "re_panzhangmazhong", "xin_panzhangmazhong"],
	peixiu: ["ol_peixiu", "fj_peixiu", "xj_peixiu", "peixiu", "scl_peixiu", "std_peixiu"],
	puyuan: ["ol_puyuan", "puyuan"],
	qianzhao: ["ol_qianzhao", "qianzhao"],
	qiaogong: ["ol_qiaogong", "qiaogong", "tw_qiaogong"],
	qiaorui: ["qiaorui", "tw_qiaorui"],
	ol_qiaoxuan: ["ol_qiaoxuan", "jsrg_qiaoxuan"],
	qiaozhou: ["yj_qiaozhou", "qiaozhou", "tw_qiaozhou"],
	qinghegongzhu: ["qinghegongzhu", "dc_qinghegongzhu", "mb_qinghegongzhu"],
	qinlang: ["ol_qinlang", "qinlang"],
	quancong: ["quancong", "re_quancong", "xin_quancong", "yy_quancong", "old_quancong"],
	quyi: ["quyi", "re_quyi", "yy_quyi"],
	ruiji: ["ruiji", "dc_ruiji"],
	shamoke: ["shamoke", "ty_shamoke"],
	shenpei: ["shenpei", "sp_shenpei", "ns_shenpei"],
	shixie: ["shixie", "dc_shixie", "old_shixie"],
	simafu: ["yj_simafu", "mb_simafu", "simafu"],
	simalang: ["simalang", "re_simalang"],
	simashi: ["jin_simashi", "dc_simashi", "simashi", "tw_simashi", "std_simashi", "jd_jin_simashi"],
	simayi: ["simayi", "re_simayi", "jin_simayi", "dm_simayi", "dc_sb_simayi", "huan_simayi", "jsrg_simayi", "yy_simayi", "ps_simayi", "ps_jin_simayi", "ps2068_simayi", "junk_simayi"],
	simazhao: ["jin_simazhao", "mb_simazhao", "simazhao", "sp_simazhao", "jsrg_simazhao", "jin_jsrg_simazhao", "jd_jin_simazhao", "ns_simazhao", "std_simazhao"],
	simazhou: ["simazhou", "mb_simazhou"],
	sunce: ["sunce", "re_sunce", "sp_sunce", "dc_sunce", "re_sunben", "sb_sunce", "jsrg_sunce", "pe_jun_sunce"],
	sundeng: ["sundeng", "re_sundeng", "ns_sundeng"],
	sunhanhua: ["dc_sunhanhua", "sunhanhua", "scl_sunhanhua"],
	sunhao: ["sunhao", "std_sunhao", "hs_sunhao"],
	sunjian: ["sunjian", "ol_sunjian", "ol_sb_sunjian", "re_sunjian", "star_sunjian", "jsrg_sunjian", "ns_sunjian"],
	sunliang: ["sunliang", "xin_sunliang"],
	sunluban: ["re_sunluban", "xin_sunluban", "tw_sunluban", "std_sunluban", "sunluban", "ol_sunluban"],
	sunluyu: ["sunluyu", "re_sunluyu", "mb_sunluyu", "std_sunluyu"],
	sunquan: ["sunquan", "re_sunquan", "v_sunquan", "dc_sunquan", "xin_sunquan", "sb_sunquan", "jd_sb_sunquan", "ty_sunquan", "ps_sunquan", "pe_jun_sunquan"],
	sunru: ["dc_sunru", "ol_sunru", "sunru"],
	sunshangxiang: ["sunshangxiang", "re_sunshangxiang", "sp_sunshangxiang", "star_sunshangxiang", "sb_sunshangxiang", "jsrg_sunshangxiang", "jd_sb_sunshangxiang"],
	sunshao: ["sunshao", "sp_sunshao", "std_sunshao"],
	sunxiu: ["sunxiu", "ol_sunxiu", "re_sunxiu", "xin_sunxiu"],
	sunyi: ["re_sunyi", "sunyi", "tw_sunyi", "std_sunyi", "ns_sunyi"],
	sunziliufang: ["sunziliufang", "dc_sunziliufang"],
	taishici: ["taishici", "re_taishici", "ol_sb_taishici", "sp_taishici", "re_sp_taishici", "pot_taishici"],
	taoqian: ["ol_taoqian", "re_taoqian", "taoqian", "std_taoqian"],
	tengfanglan: ["tengfanglan", "dc_tengfanglan"],
	tianfeng: ["dc_tianfeng", "tianfeng", "mb_tianfeng", "std_tianfeng"],
	tianyu: ["tianyu", "tw_tianyu"],
	tongyuan: ["tongyuan", "xia_tongyuan"],
	wangcan: ["wangcan", "sp_wangcan", "tw_wangcan"],
	wangjun: ["dc_wangjun", "wangjun", "jsrg_wangjun"],
	wanglang: ["ol_wanglang", "wanglang", "std_wanglang", "old_wanglang"],
	wangling: ["clan_wangling", "dc_wangling", "wangling", "tw_wangling"],
	wangrong: ["ol_wangrong", "wangrong"],
	wangshuang: ["wangshuang", "sp_wangshuang"],
	wangyi: ["wangyi", "ol_wangyi", "re_wangyi", "old_wangyi"],
	wangyuanji: ["jin_wangyuanji", "wangyuanji", "std_wangyuanji", "jd_jin_wangyuanji", "sp_wangyuanji"],
	wangyun: ["wangyun", "clan_wangyun", "dc_wangyun", "re_wangyun", "jsrg_wangyun", "std_wangyun", "pe_wangyun", "ns_wangyun", "old_wangyun", "ca_wangyun"],
	weiwenzhugezhi: ["weiwenzhugezhi", "re_weiwenzhugezhi", "jsrg_weiwenzhugezhi"],
	weiyan: ["re_weiyan", "ol_weiyan", "weiyan", "yj_weiyan", "huan_weiyan", "pot_weiyan"],
	wenpin: ["wenpin", "re_wenpin"],
	wenyang: ["wenyang", "db_wenyang", "jsrg_wenyang", "std_db_wenyang", "diy_wenyang"],
	wuanguo: ["ol_wuanguo", "wuanguo"],
	wuban: ["clan_wuban", "dc_wuban", "wuban", "xin_wuban", "ty_wuban"],
	wuguotai: ["wuguotai", "ol_wuguotai", "xin_wuguotai", "re_wuguotai"],
	wuhujiang: ["wuhujiang", "hanshiwuhu"],
	wujing: ["ol_wujing", "wujing", "tw_wujing"],
	wuxian: ["wuxian", "clan_wuxian"],
	wuyi: ["wuyi", "re_wuyi", "clan_wuyi", "dc_wuyi", "xin_wuyi", "old_wuyi"],
	xiahouba: ["xiahouba", "dc_xiahouba", "tw_xiahouba", "std_xiahouba"],
	xiahoudun: ["xiahoudun", "re_xiahoudun", "xin_xiahoudun", "sb_xiahoudun", "xia_xiahoudun", "sp_xiahoudun"],
	xiahoushi: ["xiahoushi", "re_xiahoushi", "sb_xiahoushi", "sp_xiahoushi"],
	xiahouxuan: ["xiahouxuan", "dc_xiahouxuan", "pe_xiahouxuan"],
	xiahouyuan: ["re_xiahouyuan", "ol_xiahouyuan", "sb_xiahouyuan", "xiahouyuan"],
	xiangchong: ["xiangchong", "dc_xiangchong"],
	xianglang: ["xianglang", "mb_xianglang"],
	xiaoqiao: ["xiaoqiao", "ol_xiaoqiao", "ol_sb_xiaoqiao", "yue_xiaoqiao", "re_xiaoqiao", "sb_xiaoqiao", "jd_sb_xiaoqiao", "old_xiaoqiao"],
	xinpi: ["xinpi", "sp_xinpi"],
	xinxianying: ["xinxianying", "re_xinxianying", "ol_xinxianying", "sp_xinxianying", "ns_xinxianying", "pot_xinxianying"],
	xuangongzhu: ["xuangongzhu", "yj_xuangongzhu"],
	xuelingyun: ["ol_xuelingyun", "xuelingyun"],
	xuezong: ["xuezong", "mb_xuezong", "tw_xuezong", "std_xuezong"],
	xugong: ["xugong", "re_xugong", "jsrg_xugong"],
	xuhuang: ["re_xuhuang", "ol_xuhuang", "sb_xuhuang", "yj_xuhuang", "jd_sb_xuhuang", "xuhuang", "wn_xuhuang"],
	xujing: ["xujing", "dc_xujing", "sp_xujing", "tw_xujing"],
	xunchen: ["xunchen", "clan_xunchen", "re_xunchen", "sp_xunchen", "tw_xunchen"],
	xunyou: ["xunyou", "clan_xunyou", "re_xunyou"],
	xunyu: ["xunyu", "ol_xunyu", "dc_sb_xunyu", "star_xunyu", "re_xunyu", "sb_xunyu", "sxrm_xunyu"],
	xushao: ["xushao", "jsrg_xushao"],
	xusheng: ["xusheng", "xin_xusheng", "re_xusheng", "old_xusheng", "drag_xusheng"],
	xushu: ["xin_xushu", "re_xushu", "dc_xushu", "friend_xushu", "xia_xushu", "std_xushu", "xushu", "xk_shanfu"],
	xuyou: ["xuyou", "sp_xuyou", "jsrg_xuyou", "yj_xuyou", "junk_xuyou"],
	xuzhu: ["xuzhu", "re_xuzhu"],
	yangbiao: ["dc_yangbiao", "yangbiao", "jsrg_yangbiao", "clan_yangbiao", "std_yangbiao"],
	yangfeng: ["ol_yangfeng", "yangfeng"],
	yanghuiyu: ["jin_yanghuiyu", "yanghuiyu"],
	yangwan: ["yangwan", "sp_yangwan", "jd_sp_yangwan"],
	yangyan: ["yangyan", "old_yangyan"],
	yangyi: ["ol_yangyi", "yangyi", "tw_yangyi", "ns_yangyi"],
	yangzhi: ["yangzhi", "old_yangzhi"],
	yanwen: ["yanwen", "ol_yanwen", "re_yanwen"],
	yanxiang: ["yanxiang", "tw_yanxiang"],
	yuanhuan: ["ol_yuanhuan", "yuanhuan"],
	yuanji: ["ol_yuanji", "yuanji"],
	yuanshu: ["yuanshu", "re_yuanshu", "ol_sb_yuanshu", "star_yuanshu", "yl_yuanshu", "old_yuanshu", "ol_yuanshu"],
	yuantanyuanshang: ["yuantanyuanshang", "yuantanyuanxiyuanshang"],
	yuejin: ["yuejin", "std_yuejin"],
	yuejiu: ["dc_yuejiu", "yuejiu"],
	yufan: ["yufan", "ol_yufan", "xin_yufan", "re_yufan", "std_yufan"],
	yuji: ["xin_yuji", "re_yuji", "yuji", "pot_yuji", "ns_yuji", "ns_yujisp"],
	yujin: ["yujin", "ol_yujin", "yujin_yujin", "sb_yujin", "tw_yujin", "jd_sb_yujin", "xin_yujin", "re_yujin"],
	zangba: ["zangba", "tw_zangba"],
	zhangbao: ["zhangbao", "re_zhangbao", "ns_zhangbao"],
	zhangchangpu: ["ol_zhangchangpu", "zhangchangpu", "sp_zhangchangpu"],
	zhangchu: ["zhangchu", "jsrg_zhangchu"],
	zhangchunhua: ["zhangchunhua", "ol_zhangchunhua", "jin_zhangchunhua", "re_zhangchunhua", "star_zhangchunhua"],
	zhangfei: ["zhangfei", "re_zhangfei", "ol_sb_zhangfei", "old_zhangfei", "xin_zhangfei", "sb_zhangfei", "tw_zhangfei", "jsrg_zhangfei", "jd_sb_zhangfei", "yj_zhangfei", "sp_zhangfei", "yj_zhangfei"],
	zhangfen: ["zhangfen", "mb_zhangfen"],
	zhangji: ["zhangji", "ns_zhangji", "ca_zhangji"],
	zhangjiao: ["sp_zhangjiao", "re_zhangjiao", "sb_zhangjiao", "jsrg_zhangjiao", "zhangjiao", "pe_jun_zhangjiao"],
	zhanggong: ["zhanggong", "re_zhanggong"],
	zhanghe: ["zhanghe", "re_zhanghe", "sp_ol_zhanghe", "yj_zhanghe", "sp_zhanghe", "sb_zhanghe", "tw_yj_zhanghe", "huan_zhanghe", "jsrg_zhanghe", "wn_zhanghe"],
	zhangliang: ["zhangliang", "xin_zhangliang", "re_zhangliang"],
	zhangliao: ["zhangliao", "re_zhangliao", "sp_zhangliao", "v_zhangliao", "yj_zhangliao", "sb_zhangliao", "jsrg_zhangliao"],
	zhangning: ["zhangning", "tw_zhangning", "ns_zhangning"],
	zhangrang: ["ol_zhangrang", "zhangrang", "ol_sb_zhangrang", "star_zhangrang", "junk_zhangrang", "ps_zhangrang"],
	zhangsong: ["zhangsong", "re_zhangsong"],
	zhangwen: ["zhangwen", "sp_zhangwen"],
	zhangxingcai: ["zhangxingcai", "old_zhangxingcai"],
	zhangxiu: ["zhangxiu", "ol_sb_zhangxiu", "dc_sb_zhangxiu", "ns_zhangxiu"],
	zhangxuan: ["zhangxuan", "jsrg_zhangxuan"],
	zhangyi: ["zhangyi", "re_zhangyi", "xin_zhangyi"],
	zhangyì: ["ol_zhangyì", "dc_zhangyì", "zhangyì", "std_zhangyì"],
	zhangzhang: ["zhangzhang", "ol_zhangzhang", "re_zhangzhang"],
	zhaotongzhaoguang: ["dc_zhaotongzhaoguang", "zhaotongzhaoguang"],
	zhaoxiang: ["zhaoxiang", "dc_zhaoxiang", "tw_zhaoxiang"],
	zhaoyǎn: ["zhaoyǎn", "dc_zhaoyǎn"],
	zhaoyun: ["zhaoyun", "re_zhaoyun", "sp_zhaoyun", "ol_sb_zhaoyun", "ol_jsrg_zhaoyun", "old_zhaoyun", "sb_zhaoyun", "huan_zhaoyun", "jsrg_zhaoyun", "jd_sb_zhaoyun", "jsp_zhaoyun", "yy_zhaoyun", "ps2063_zhaoyun", "ps2067_zhaoyun"],
	zhenji: ["zhenji", "re_zhenji", "sp_zhenji", "sb_zhenji", "mb_sp_zhenji", "tw_zhenji", "jsrg_zhenji", "yj_zhenji"],
	zhonghui: ["zhonghui", "clan_zhonghui", "xin_zhonghui", "re_zhonghui", "std_zhonghui", "yj_zhonghui", "pe_zhonghui", "old_zhonghui"],
	zhongyan: ["zhongyan", "clan_zhongyan"],
	zhongyao: ["zhongyao", "clan_zhongyao", "re_zhongyao"],
	zhoubuyi: ["zhoubuyi", "yj_zhoubuyi"],
	zhoucang: ["zhoucang", "re_zhoucang", "xin_zhoucang", "drag_zhoucang"],
	zhouchu: ["jin_zhouchu", "zhouchu", "tw_zhouchu", "std_zhouchu"],
	zhoufei: ["zhoufei", "yue_zhoufei"],
	zhouqun: ["ol_zhouqun", "zhouqun"],
	zhoutai: ["zhoutai", "xin_zhoutai", "old_zhoutai"],
	zhouyu: ["zhouyu", "re_zhouyu", "dc_sb_zhouyu", "yue_zhouyu", "sb_zhouyu", "jx_zhouyu", "ps1062_zhouyu", "ps2080_zhouyu", "jy_zhouyu"],
	zhugedan: ["zhugedan", "re_zhugedan", "jsrg_zhugedan"],
	zhugeguo: ["zhugeguo", "yue_zhugeguo", "tw_zhugeguo", "huan_zhugeguo"],
	zhugejin: ["zhugejin", "dc_sb_zhugejin", "sb_zhugejin"],
	zhugeliang: ["zhugeliang", "re_zhugeliang", "ol_sb_zhugeliang", "wu_zhugeliang", "friend_zhugeliang", "huan_zhugeliang", "jsrg_zhugeliang", "ps_zhugeliang", "ps2066_zhugeliang", "prp_zhugeliang", "ns_zhugeliang", "jy_zhugeliang"],
	zhugezhan: ["zhugezhan", "old_zhugezhan"],
	zhuhuan: ["zhuhuan", "re_zhuhuan", "xin_zhuhuan", "old_zhuhuan"],
	zhujun: ["ol_zhujun", "zhujun", "sp_zhujun", "jsrg_zhujun"],
	zhuling: ["ol_zhuling", "dc_zhuling", "zhuling"],
	zhuran: ["zhuran", "re_zhuran", "xin_zhuran", "old_zhuran"],
	zhurong: ["zhurong", "ol_zhurong", "re_zhurong", "sb_zhurong", "dc_sp_zhurong"],
	zhuzhi: ["zhuzhi", "re_zhuzhi", "xin_zhuzhi", "tw_zhuzhi", "old_zhuzhi"],
	zongyu: ["zongyu", "sp_zongyu", "tw_zongyu"],
	zoushi: ["zoushi", "re_zoushi", "yue_zoushi", "jsrg_zoushi", "std_zoushi"],
	zumao: ["zumao", "tw_zumao"],
	zuoci: ["zuoci", "re_zuoci", "ns_zuoci"],
	zhangyan: ["zhangyan", "yj_zhangyan", "mb_zhangyan"],
	dc_huangwudie: ["dc_huangwudie", "ns_huangwudie"],
	dc_jiben: ["dc_jiben", "sp_jiben"],
	dc_wangchang: ["clan_wangchang", "dc_wangchang", "tw_wangchang"],
	dc_zhangmancheng: ["ol_zhangmancheng", "dc_zhangmancheng", "tw_zhangmancheng"],
	dc_zhangren: ["dc_zhangren", "jsrg_zhangren"],
	ol_bianfuren: ["ol_bianfuren", "sp_bianfuren", "tw_bianfuren"],
	ol_dongzhao: ["ol_dongzhao", "dc_dongzhao", "pot_dongzhao", "tw_dongzhao"],
	ol_huban: ["ol_huban", "dc_huban", "mb_huban"],
	ol_mengda: ["ol_mengda", "dc_mengda", "pe_mengda", "std_mengda", "mb_mengda"],
	ol_pengyang: ["ol_pengyang", "sp_pengyang"],
	ol_wenqin: ["ol_wenqin", "mb_wenqin", "pe_wenqin"],
	re_lidian: ["re_lidian", "old_re_lidian", "junk_lidian"],
	re_lusu: ["re_lusu", "ol_lusu", "ol_sb_lusu", "dc_sb_lusu", "pot_lusu", "xia_lusu", "jy_lusu"],
	re_yuanshao: ["re_yuanshao", "ol_yuanshao", "ol_sb_yuanshao", "star_yuanshao", "xin_yuanshao", "sb_yuanshao", "jsrg_yuanshao", "jd_sb_yuanshao", "yy_yuanshao", "pe_jun_yuanshao"],
	sp_chenzhen: ["sp_chenzhen", "tw_chenzhen"],
	sp_jiangwan: ["ol_jiangwan", "sp_jiangwan", "std_jiangwan"],
	sp_mifuren: ["dc_mifuren", "sp_mifuren"],
	sp_zhugeliang: ["sp_zhugeliang", "ol_sp_zhugeliang", "re_sp_zhugeliang", "sb_sp_zhugeliang", "tw_sb_sp_zhugeliang", "jd_sb_sp_zhugeliang"],
	ty_anying: ["ty_anying", "ty_anyingx"],
	ty_guanxing: ["std_guanxing", "ty_guanxing"],
	tw_fengxí: ["tw_fengxí", "ty_fengxí"],
	tw_wenchou: ["ol_sb_wenchou", "star_wenchou", "tw_wenchou", "yy_wenchou", "ns_wenchou"],
	tw_xiahouen: ["ol_xiahouen", "tw_xiahouen", "jsrg_xiahouen"],
	tw_yanliang: ["tw_yanliang", "ns_yanliang"],
	tw_zhangji: ["tw_zhangji", "ol_tw_zhangji"],
	tw_zhangnan: ["tw_zhangnan", "ty_zhangnan"],
	tw_zhangzhao: ["tw_zhangzhao", "star_zhangzhao", "jy_zhangzhao"],
	xf_huangquan: ["xf_huangquan", "dc_huangquan", "dc_sb_huangquan"],
	yj_jushou: ["yj_jushou", "ol_sb_jushou", "re_jushou", "dc_sb_jushou", "xin_jushou"],
	yj_sufei: ["xf_sufei", "yj_sufei", "sp_sufei"],
	yl_luzhi: ["yl_luzhi", "ol_sb_yl_luzhi", "sb_yl_luzhi", "tw_yl_luzhi", "jsrg_yl_luzhi"],
	jin_yanghu: ["jin_yanghu", "dc_yanghu", "sp_yanghu", "std_dc_yanghu", "ns_yanghu"],
	jin_xiahouhui: ["jin_xiahouhui", "dc_xiahouhui", "jd_jin_xiahouhui"],
	jsrg_limi: ["jsrg_limi", "ns_limi"],
	pot_lougui: ["pot_lougui", "jsrg_lougui"],
	ol_zhaozhong: ["ol_zhaozhong", "zhaozhong", "ps_zhaozhong"],
	friend_shitao: ["friend_shitao", "xia_shitao"],
	tw_xiahoushang: ["mb_xiahoushang", "tw_xiahoushang"],
	yanghong: ["yanghong", "mb_yanghong"],
	peiyuanshao: ["ol_peiyuanshao", "peiyuanshao"],
	xingdaorong: ["xingdaorong", "mb_xingdaorong"],
	yangxiu: ["yangxiu", "clan_yangxiu"],
	zhugeke: ["zhugeke", "std_zhugeke"],
	dongyun: ["dongyun", "std_dongyun"],
	zhoufang: ["zhoufang", "std_zhoufang"],
	yangfu: ["ol_yangfu", "yangfu"],
	chezhou: ["chezhou", "yj_chezhou"],
	clan_zhongyu: ["clan_zhongyu", "dc_zhongyu"],
	guanhai: ["ol_guanhai", "guanhai"],
	zerong: ["zerong", "std_zerong", "mb_zerong"],
	tw_zhugejun: ["tw_zhugejun", "dc_zhugejun"],
	wufu: ["wufu", "hr_wufu"],
	zhangyao: ["zhangyao", "std_zhangyao"],
	sunjun: ["mb_sunjun", "jsrg_sunjun"],
	zhangqiying: ["zhangqiying", "x_dc_zhangqiying", "y_dc_zhangqiying"],
	yj_zhanghuan: ["yj_zhanghuan", "jsrg_zhanghuan"],
	kaisa: ["kaisa", "eu_kaisa"],
};
