const characters = {
	ol_fanyufeng: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olzhuoyue", "olqiaowu"],
		names: "樊|玉凤",
	},
	ol_qiaogong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["olmeiyan", "olshuoyu", "olzuobao"],
		names: "桥|null",
	},
	zhangqiying: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["xinfu_falu", "xinfu_dianhua", "xinfu_zhenyi"],
	},
	ol_qiaoxuan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["oltingji", "olxuanliu"],
	},
	ol_caizhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["olkedi", "olcunze"],
	},
	ol_zhangmancheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olkuangxin", "olleishi"],
	},
	ol_guanhai: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olxiewei", "olyouque"],
	},
	ol_yangfu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olpingzhong", "olsuyi"],
	},
	ol_lifeng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["oljiyun", "olshuliang"],
	},
	ol_miheng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olkuangjuan", "olfeibian"],
	},
	ol_peiyuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olfulve"],
	},
	ol_zhaozhong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olpengbi", "oldici"],
		trashBin: ["sex:male_castrated"],
	},
	ol_wujing: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["heji", "olliubing"],
		dieAudios: ["wujing"],
	},
	ol_yangfeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["oljiawei"],
	},
	ol_yuanhuan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olderu", "ollinjie"],
	},
	sp_ol_liubei: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["spolxudai", "spolzhujiu", "spoljinglei"],
	},
	ol_liuzhang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olfengwei", "olzonghu"],
	},
	ol_taoqian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olzongluan", "olwenren", "olzhaohuo"],
	},
	ol_xuelingyun: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["olsiqi", "olqiaozhi"],
	},
	ol_guozhao: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["oljiaoyu", "olneixun"],
	},
	ol_qinlang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olxianying"],
	},
	ol_wuanguo: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olliyong"],
	},
	ol_nanhualaoxian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olqingshu", "olshoushu", "olhedao"],
		names: "庄|周",
	},
	sp_ol_caocao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["spolxixiang", "spolaige"],
	},
	ol_dongxie: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 5,
		skills: ["oljiaowei", "olbianyu", "olfengyao"],
	},
	ol_hanfu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olshuzi", "olkuangshou"],
	},
	ol_niufu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olshisuan", "olzonglve"],
	},
	chenggongying: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olkuangxiang"],
		names: "成公|英",
	},
	wangkuang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olrenxia"],
	},
	kongshu: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["leiluan", "fuchao"],
	},
	ol_kebineng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olpingduan"],
		names: "科比|罐头",
	},
	ol_yuanji: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["oljieyan", "oljinghua", "olshuiyue"],
		names: "袁|null",
	},
	ol_sunru: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["olchishi", "olweimian"],
	},
	caoteng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olyongzu", "olqingliu"],
	},
	budugen: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olkouchao"],
		names: "null|null",
	},
	mawan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "olhunjiang"],
	},
	ol_jiangwan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olziruo", "olxvfa"],
	},
	caimao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olzuolian", "oljingzhou"],
	},
	ol_peixiu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olmaozhu", "oljinlan"],
		groupBorder: "jin",
	},
	yadan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olqingya", "oltielun"],
		names: "null|null",
	},
	sp_sunce: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["junkliantao"],
	},
	ol_liupi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olyicheng"],
	},
	ol_lukai: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["olxuanzhu", "oljiane"],
		clans: ["吴郡陆氏"],
	},
	liupan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olpijing"],
	},
	guotu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olqushi", "olweijie"],
	},
	ol_hujinding: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["olqingyuan", "olchongshen"],
	},
	tianchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olshandao"],
	},
	liyi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["olchanshuang", "olzhanjin"],
	},
	caoyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olgongjie", "olxiangxv", "olxiangzuo"],
	},
	ol_liwan: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["relianju", "resilv"],
	},
	ol_dingshangwan: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["olfudao", "olfengyan"],
	},
	zhangyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olsuji", "ollangdao"],
	},
	ol_tw_zhangji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["skill_zhangji_A", "skill_zhangji_B"],
	},
	ol_feiyi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["yanru", "hezhong"],
	},
	lvboshe: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olfushi", "oldongdao"],
	},
	ol_luyusheng: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["olcangxin", "olrunwei"],
		clans: ["吴郡陆氏"],
	},
	caoxi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olgangshu", "oljianxuan"],
	},
	ol_pengyang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olxiaofan", "oltuishi", "nzry_cunmu"],
	},
	ol_qianzhao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olweifu", "olkuansai"],
	},
	niujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olcuorui", "liewei"],
	},
	hejin: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mouzhu", "olyanhuo"],
	},
	hansui: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olniluan", "olxiaoxi"],
	},
	duanjiong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olsaogu"],
	},
	ol_zhouqun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["oltianhou", "olchenshuo"],
	},
	ol_wenqin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olguangao", "olhuiqi"],
	},
	haopu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olzhenying"],
	},
	ol_mengda: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olgoude"],
	},
	ol_wanglang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["gushe", "oljici"],
		dieAudios: ["wanglang"],
	},
	lushi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olzhuyan", "releijie"],
		names: "卢|null",
	},
	zhangshiping: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olhongji", "olxinggu"],
	},
	sunhong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["olxianbi", "olzenrun"],
	},
	luoxian: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["oldaili"],
	},
	ol_huban: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olhuiyun"],
	},
	wangguan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olmiuyan", "olshilu"],
	},
	ol_zhangyì: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["oldianjun", "olkangrui"],
	},
	ol_zhujun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olcuipo"],
	},
	maxiumatie: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "rekenshang"],
		names: "马|休-马|铁",
	},
	dongtuna: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["oljianman"],
		names: "null|null",
	},
	zhanghua: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["olbihun", "oljianhe", "olchuanwu"],
	},
	quhuang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["olqiejian", "olnishou"],
	},
	macheng: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "olchenglie"],
	},
	zhangzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olbixin", "olximo"],
	},
	ol_liuba: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["oltongduo", "olzhubi"],
	},
	ol_furong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olxiaosi"],
	},
	ahuinan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jueman"],
		names: "null|null",
	},
	jin_guohuai: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["zhefu", "yidu"],
	},
	xiahouxuan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olhuanfu", "olqingyi", "olzeyue"],
		names: "夏侯|玄",
	},
	dengzhong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dzkanpo", "dzgengzhan"],
	},
	wangyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yangkuang", "cihuang", "sanku"],
		groupBorder: "jin",
	},
	huojun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qiongshou", "fenrui"],
	},
	caoxiancaohua: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["huamu", "qianmeng", "liangyuan", "jisi"],
		names: "曹|宪-曹|华",
	},
	jin_zhouchu: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["shanduan", "yilie"],
	},
	zhaoyǎn: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["tongxie"],
	},
	ol_puyuan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olshengong", "olqisi"],
	},
	ruiji: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["qiaoli", "qingliang"],
		names: "芮|null",
	},
	weizi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["yuanzi", "liejie"],
	},
	tengfanglan: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["luochong", "aichen"],
	},
	sp_menghuo: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["spmanwang"],
	},
	jin_yanghu: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["huaiyuan", "chongxin", "dezhang"],
	},
	qinghegongzhu: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["zengou", "qhzhangji"],
		names: "曹|null",
	},
	fanjiangzhangda: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["yuanchou", "juesheng"],
		names: "范|疆-张|达",
	},
	tianyu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["saodi", "zhuitao"],
	},
	ol_chendeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olfengji", "olxuanhui"],
	},
	ol_zhuling: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jixian"],
	},
	wuyan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["lanjiang"],
	},
	sp_ol_zhanghe: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["spolzhouxuan"],
	},
	ol_dongzhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olxianlve", "olzaowang"],
	},
	fengfangnv: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["zhuangshu", "chuiti"],
	},
	ol_yangyi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["oljuanxia", "oldingcuo"],
	},
	zuofen: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["zhaosong", "lisi"],
	},
	ol_wangrong: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olfengzi", "oljizhan", "olfusong"],
	},
	ol_dengzhi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olxiuhao", "olsujian"],
	},
	ol_bianfuren: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["fuwei", "yuejian"],
		names: "卞|null",
	},
	duxi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["quxi", "bixiong"],
	},
	gaogan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["juguan"],
	},
	huangchengyan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["guanxu", "yashi"],
	},
	huangzu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wangong"],
	},
	panshu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["weiyi", "jinzhi"],
	},
	wolongfengchu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["youlong", "luanfeng"],
		names: "诸葛|亮-庞|统",
	},
	sp_zhangliao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mubing", "ziqu", "diaoling"],
	},
	caoshuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["retuogu", "shanzhuan"],
	},
	ol_zhangchangpu: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["yanjiao", "olxingshen"],
		dieAudios: ["zhangchangpu"],
	},
	zhangling: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zlhuji", "zlshoufu"],
	},
	caiyang: {
		sex: "male",
		group: "qun",
		hp: 1,
		skills: ["yinka", "zhuixi"],
		isAiForbidden: true,
		isUnseen: true,
	},
	sunshao: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["bizheng", "yidian"],
	},
	mifuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["guixiu", "cunsi"],
		names: "糜|null",
		isUnseen: true,
	},
	zoushi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: [],
		names: "邹|null",
		isUnseen: true,
	},

	huangfusong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["fenyue"],
		names: "皇甫|嵩",
	},
	yuantanyuanshang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["neifa"],
		names: "袁|谭-袁|尚",
	},
	xujing: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["yuxu", "xjshijian"],
	},

	jianggan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["weicheng", "daoshu"],
	},
	caoying: {
		sex: "female",
		group: "wei",
		hp: 4,
		skills: ["xinfu_lingren", "fujian"],
	},
	simahui: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jianjie", "xinfu_chenghao", "xinfu_yinshi"],
		names: "司马|徽",
	},
	baosanniang: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["newwuniang", "newzhennan", "newxushen"],
	},
	yangxiu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["jilei", "danlao"],
		clans: ["弘农杨氏"],
	},
	chenlin: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["bifa", "songci"],
	},
	caohong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["yuanhu"],
	},
	xiahouba: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["baobian"],
		names: "夏侯|霸",
	},
	yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yongsi", "weidi"],
	},
	sp_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["lihun", "rebiyue"],
		names: "null|null",
		dieAudios: ["diaochan"],
	},
	sp_zhaoyun: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["ollongdan", "chongzhen"],
	},
	liuxie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["tianming", "mizhao", "twzhuiting"],
		isZhugong: true,
	},
	zhugejin: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["huanshi", "olhongyuan", "olmingzhe"],
		names: "诸葛|瑾",
	},
	zhugeke: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["aocai", "duwu"],
		names: "诸葛|恪",
	},
	guanyinping: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["huxiao", "xueji", "wuji"],
	},
	simalang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["junbing", "quji"],
		names: "司马|朗",
	},
	zhangxingcai: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["shenxian", "qiangwu"],
	},
	fuwan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dcmoukui"],
	},
	sp_sunshangxiang: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["liangzhu", "fanxiang"],
	},
	caoang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["kaikang"],
	},
	sp_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["weikui", "lizhan"],
	},
	zhangbao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rezhoufu", "reyingbing"],
	},
	maliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zishu", "yingyuan"],
	},
	zhugedan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["gongao", "juyi"],
		names: "诸葛|诞",
	},
	sp_jiangwei: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["kunfen", "fengliang"],
	},
	sp_machao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olzhuiji", "ol_shichou"],
	},
	sunhao: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["recanshi", "rechouhai", "guiming"],
		isZhugong: true,
	},
	shixie: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olbiluan", "relixia"],
	},
	mayunlu: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["fengpo", "mashu"],
	},
	zhanglu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["yishe", "bushi", "midao", "twshijun"],
		isZhugong: true,
	},
	wutugu: {
		sex: "male",
		group: "qun",
		hp: 15,
		skills: ["ranshang", "hanyong"],
		names: "null|null",
	},
	sp_caiwenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["chenqing", "mozhi"],
	},
	zhugeguo: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["qirang", "yuhua"],
		names: "诸葛|果",
	},

	lingju: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["jieyuan", "fenxin"],
		names: "吕|null",
	},

	cuiyan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yawang", "xunzhi"],
	},
	jsp_guanyu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_rewusheng", "danji"],
	},
	jsp_huangyueying: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["jiqiao", "linglong"],
	},
	sunluyu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["new_meibu", "new_mumu"],
	},
	hanba: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["fentian", "zhiri"],
		names: "null|null",
	},
	zumao: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["yinbing", "juedi"],
	},
	wenpin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zhenwei"],
	},
	daxiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["new_xingwu", "new_luoyan"],
		names: "桥|null-桥|null",
	},

	guansuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["zhengnan", "xiefang"],
	},
	tadun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["reluanzhan"],
		names: "null|null",
	},
	yanbaihu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["zhidao", "jili"],
	},
	chengyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["shefu", "benyu"],
	},

	sp_pangde: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mashu", "juesi"],
	},
	sp_jiaxu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["zhenlue", "jianshu", "yongdi"],
	},

	litong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["tuifeng"],
	},
	mizhu: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["ziyuan", "jugu"],
	},
	buzhi: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["hongde", "dingpan"],
	},

	caochun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olshanjia"],
	},

	dongbai: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["lianzhu", "xiahui"],
	},

	zhaoxiang: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["fanghun", "fuhan"],
	},
	mazhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["fuman"],
	},
	dongyun: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["bingzheng", "sheyan"],
	},
	kanze: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["xiashu", "kuanshi"],
	},
	heqi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["olqizhou", "olshanxi"],
	},

	yuejin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xiaoguo"],
	},
	sp_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["hengzheng"],
	},
	hetaihou: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["zhendu", "qiluan"],
		names: "何|null",
	},
	dingfeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["reduanbing", "refenxun"],
	},
	shamoke: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["gzjili"],
		names: "null|null",
	},

	wangyun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinlianji", "xinmoucheng"],
		clans: ["太原王氏"],
	},
	sunqian: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qianya", "shuimeng"],
	},
	xizhicai: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tiandu", "xianfu", "chouce"],
	},
	quyi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["fuqi", "jiaozi"],
	},

	luzhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qingzhong", "weijing"],
	},

	wangcan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinfu_sanwen", "xinfu_qiai", "xinfu_denglou"],
	},
	re_jsp_pangtong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["xinfu_guolun", "xinfu_songsang"],
	},
	lvqian: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xinfu_weilu", "xinfu_zengdao"],
	},
	panjun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["xinfu_guanwei", "xinfu_gongqing"],
	},
	zhoufang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["xinfu_duanfa", "xinfu_youdi"],
	},
	yanjun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["xinfu_guanchao", "xinfu_xunxian"],
	},
	liuyan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinfu_tushe", "xinfu_limu"],
	},
};

export default characters;
