const characters = {
	std_yuejin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["stdxiaoguo"],
		dieAudios: ["yuejin"],
		img: "image/character/gz_yuejin.jpg",
	},
	old_re_lidian: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xunxun", "wangxi"],
		dieAudios: ["lidian"],
	},
	ganfuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["stdshushen", "shenzhi"],
		names: "甘|null",
	},
	std_panfeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["stdkuangfu"],
		dieAudios: ["re_panfeng"],
	},
	caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jianxiong", "hujia"],
		isZhugong: true,
	},
	simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["fankui", "guicai"],
		names: "司马|懿",
	},
	xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["ganglie"],
		names: "夏侯|惇",
	},
	zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["tuxi"],
	},
	xuzhu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["luoyi"],
	},
	guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tiandu", "yiji"],
	},
	zhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["luoshen", "qingguo"],
	},
	liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rende", "jijiang"],
		isZhugong: true,
	},
	guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wusheng"],
	},
	zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["paoxiao"],
	},
	zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["guanxing", "kongcheng"],
		names: "诸葛|亮",
	},
	zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longdan"],
	},
	machao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "tieji"],
	},
	huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["jizhi", "qicai"],
	},
	sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["zhiheng", "jiuyuan"],
		isZhugong: true,
	},
	ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qixi"],
	},
	lvmeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["keji"],
	},
	huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["kurou"],
	},
	zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["yingzi", "fanjian"],
	},
	daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["guose", "liuli"],
		names: "桥|null",
	},
	luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["qianxun", "lianying"],
		clans: ["吴郡陆氏"],
	},
	sunshangxiang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["xiaoji", "jieyin"],
	},
	huatuo: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["qingnang", "jijiu"],
	},
	lvbu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["wushuang"],
	},
	diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["lijian", "biyue"],
		names: "null|null",
	},
	huaxiong: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["yaowu"],
	},
	gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["reyicong"],
		names: "公孙|瓒",
	},

	xf_yiji: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xinfu_jijie", "xinfu_jiyuan"],
	},
	re_yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["rewangzun", "retongji"],
	},
};

export default characters;
