const characters = {
	mark_shen_machao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["mark_shouli", "mark_hengwu"],
		groupInGuozhan: "shu",
		dieAudios: ["shen_machao"],
	},
	wn_shen_machao: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["wn_qiangshu", "wn_yuma"],
		groupInGuozhan: "shu",
	},
	wn_shen_xuzhu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["wn_zhuanzhan", "wn_huwei"],
		groupInGuozhan: "wei",
	},
	ca_shen_wangyun: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["caanchao", "cayurong", "cadingxi"],
	},
	ca_shen_caocao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["cazhaoshao", "caxiaoxiong"],
		groupInGuozhan: "wei",
	},
	ca_shen_lijueguosi: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["caweijue", "cachuxiong"],
		names: "李|傕-郭|汜",
	},
	zombie_jiaxu: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["zombiesangluan", "zombieshibao", "zombiechuce", "zombielongmu"],
		groupInGuozhan: "qun",
	},
	zombie_zombie: {
		sex: "male",
		group: "qun",
		hp: 2,
		maxHp: 4,
		skills: ["zombieshibian", "zombieganran"],
		isUnseen: true,
	},
	ps_shen_machao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["psshouli", "pshengwu"],
		groupInGuozhan: "qun",
	},
	shen_jiaxu: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["weimu", "zybishi", "zyjianbing"],
		groupInGuozhan: "qun",
	},
	hm_shen_zhangjiao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["hm_fudao", "hm_zongfu", "hm_dangjing", "hm_sanshou"],
	},
	hm_shen_zhangbao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["hm_zhouyuan", "hm_zhaobing", "hm_sanshou"],
	},
	hm_shen_zhangliang: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["hm_jijun", "hm_fengtong", "hm_sanshou"],
	},
	hm_shen_huangfusong: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["hm_shice", "hm_podai"],
		names: "皇甫|嵩",
	},
	hm_shen_yl_luzhi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["hm_jigan", "hm_weizhu", "hm_guiquan"],
	},
	hm_shen_zhujun: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["hm_cheji", "hm_daicui", "hm_kuixiang"],
	},
	ty_shen_liubei: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["tylongnu", "nzry_jieying", "tytaoyuan"],
		groupInGuozhan: "shu",
	},
	ty_shen_zhangfei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["tyshencai", "tyxunshi"],
		groupInGuozhan: "shu",
	},
	ty_shen_guanyu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["tywushen", "tywuhun"],
		groupInGuozhan: "shu",
	},
	jx_shen_caoren: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["jxjushou"],
		groupInGuozhan: "wei",
	},
	jx_shen_liubiao: {
		sex: "male",
		group: "shen",
		hp: 2,
		skills: ["jxxiongju", "jxfujing", "jxyongrong"],
		groupInGuozhan: "qun",
	},
	shen_zhonghui: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["dclinjie", "dcduzhang", "dcjianghuo"],
		groupInGuozhan: "ye",
	},
	shen_pangtong: {
		sex: "male",
		group: "shen",
		hp: 1,
		maxHp: 1,
		skills: ["luansuo", "fengliao", "kunyu"],
		groupInGuozhan: "shu",
	},
	junk_zhangjiao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["yizhao", "junksijun", "tianjie"],
		groupInGuozhan: "qun",
		dieAudios: ["shen_zhangjiao"],
	},
	shen_huangzhong: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["new_dclieqiong", "dczhanjue"],
		groupInGuozhan: "shu",
	},
	xin_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["xinrenjie", "xinbaiyin", "xinlianpo"],
		tempname: ["new_simayi"],
		groupInGuozhan: "wei",
		names: "司马|懿",
		dieAudios: ["new_simayi"],
	},
	dc_shen_huatuo: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["jingyu", "lvxin", "huandao"],
		groupInGuozhan: "qun",
	},
	shen_xuzhu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["zhengqing", "zhuangpo"],
		groupInGuozhan: "wei",
	},
	shen_lusu: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["tamo", "dingzhou", "zhimeng"],
		groupInGuozhan: "wu",
	},
	shen_huatuo: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["wuling", "youyi"],
		groupInGuozhan: "qun",
	},
	le_shen_jiaxu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["jxlianpo", "jxzhaoluan"],
		groupInGuozhan: "qun",
	},
	shen_dianwei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["juanjia", "qiexie", "cuijue"],
		groupInGuozhan: "wei",
	},
	shen_dengai: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["dctuoyu", "dcxianjin", "dcqijing"],
		groupInGuozhan: "wei",
	},
	tw_shen_lvmeng: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["twshelie", "twgongxin"],
		groupInGuozhan: "wu",
	},
	shen_zhangjiao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["yizhao", "sijun", "sanshou", "tianjie"],
		groupInGuozhan: "qun",
	},
	shen_zhangfei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["shencai", "xunshi"],
		groupInGuozhan: "shu",
	},
	tw_shen_guanyu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["twwushen", "twwuhun"],
		groupInGuozhan: "shu",
	},
	shen_machao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["shouli", "hengwu"],
		groupInGuozhan: "shu",
	},
	shen_sunquan: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["junkyuheng", "junkdili"],
		groupInGuozhan: "wu",
	},
	shen_jiangwei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["jiufa", "tianren", "pingxiang"],
		groupInGuozhan: "shu",
	},

	shen_sunce: {
		sex: "male",
		group: "shen",
		hp: 1,
		maxHp: 6,
		skills: ["yingba", "scfuhai", "pinghe"],
		groupInGuozhan: "wu",
	},
	shen_xunyu: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["tianzuo", "lingce", "dinghan"],
		groupInGuozhan: "wei",
		clans: ["颍川荀氏"],
	},
	shen_taishici: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["dulie", "tspowei"],
		groupInGuozhan: "wu",
		names: "太史|慈",
	},
	shen_guojia: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["reshuishi", "stianyi", "resghuishi"],
		groupInGuozhan: "wei",
	},
	shen_diaochan: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["meihun", "huoxin"],
		groupInGuozhan: "qun",
		names: "null|null",
	},
	shen_guanyu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["wushen", "new_wuhun"],
		groupInGuozhan: "shu",
	},
	shen_zhaoyun: {
		sex: "male",
		group: "shen",
		hp: 2,
		skills: ["xinjuejing", "relonghun"],
		groupInGuozhan: "shu",
	},
	shen_zhugeliang: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["qixing", "kuangfeng", "dawu"],
		groupInGuozhan: "shu",
		names: "诸葛|亮",
	},
	shen_lvmeng: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["shelie", "gongxin"],
		groupInGuozhan: "wu",
	},
	shen_zhouyu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["yeyan", "qinyin"],
		groupInGuozhan: "wu",
	},
	shen_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["renjie", "sbaiyin", "lianpo"],
		groupInGuozhan: "wei",
		names: "司马|懿",
	},
	shen_caocao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["new_guixin", "feiying"],
		groupInGuozhan: "wei",
	},
	shen_lvbu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["baonu", "wumou", "ol_wuqian", "ol_shenfen"],
		groupInGuozhan: "qun",
	},

	shen_liubei: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["nzry_longnu", "nzry_jieying"],
		groupInGuozhan: "shu",
	},
	shen_luxun: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["nzry_junlve", "nzry_cuike", "nzry_dinghuo"],
		groupInGuozhan: "wu",
		clans: ["吴郡陆氏"],
	},
	shen_zhangliao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["drlt_duorui", "drlt_zhiti"],
		groupInGuozhan: "wei",
	},
	shen_ganning: {
		sex: "male",
		group: "shen",
		hp: 3,
		maxHp: 6,
		skills: ["drlt_poxi", "drlt_jieying"],
		groupInGuozhan: "wu",
	},
	ol_zhangliao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["olduorui", "olzhiti"],
		groupInGuozhan: "wei",
		dieAudios: ["shen_zhangliao"],
	},
	shen_caopi: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["chuyuan", "dengji"],
		groupInGuozhan: "wei",
	},
	shen_zhenji: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["shenfu", "qixian"],
		groupInGuozhan: "wei",
	},
	boss_zhaoyun: {
		sex: "male",
		group: "shen",
		hp: 1,
		skills: ["boss_juejing", "xinlonghun", "zhanjiang"],
		groupInGuozhan: "shu",
	},
};

export default characters;
