const characters = {
	mb_caohong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbyuanhu"],
		dieAudios: ["caohong"],
	},
	pot_xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["potchengjie", "potqingshi"],
	},
	mb_chenzhi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["mbquanchong", "mbrenxing"],
	},
	sy_baosanniang: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["mbshuyong", "mbxushen", "mbzhennan"],
		dieAudios: ["baosanniang"],
	},
	fx_baosanniang: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["mbfangxu", "mbzhuguan", "mblisuo"],
	},
	mb_zerong: {
		sex: "male",
		hp: 4,
		group: "qun",
		skills: ["mbfutu", "mbjingtu", "mbjiebian"],
	},
	pot_lusu: {
		sex: "male",
		hp: 3,
		group: "wu",
		skills: ["pothaoshi", "potdimeng"],
	},
	mb_sunjun: {
		sex: "male",
		hp: 3,
		group: "wu",
		skills: ["mbxiongtu", "mbxianshuai"],
	},
	pot_weiyan: {
		hp: 4,
		sex: "male",
		group: "shu",
		skills: ["potzhongao", "potzhuangshi", "potyinzhan"],
	},
	mb_mengda: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbjili", "mbshishu"],
	},
	mb_caoxing: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbjinzu", "mbanxian"],
	},
	mb_zhangyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbfeijing", "mbxiaoge"],
	},
	guoyuan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbqingdao", "mbxiugeng", "mbchenshe"],
	},
	mb_huangzu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbchizhang", "mbduanyang"],
	},
	mb_tianfeng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["mbganggeng", "mbsijian"],
	},
	mb_luyusheng: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["mbrunwei", "mbshuanghuai"],
	},
	mb_guanyinping: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 4,
		skills: ["mbxuehen", "mbhuxiao", "mbwuji"],
		dieAudios: ["guanyinping"],
	},
	pot_chendao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["potwanglie", "pothongyi"],
	},
	mb_xingdaorong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbkuangwu"],
	},
	wuke: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["mbanda", "mbzhuguo"],
		names: "吴|null",
	},
	mb_yanghong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["mbjianji", "mbyuanmo"],
	},
	mb_xiahoushang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbtanfeng"],
		dieAudios: ["tw_xiahoushang"],
		img: "image/character/tw_xiahoushang.jpg",
		names: "夏侯|尚",
	},
	sunsháo: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["mbganjue", "mbzhuji"],
	}, //跟孙邵拼音字母相同了
	pangxi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["mbxuye", "mbkuangxiang"],
	},
	mb_simazhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbxiezheng", "mbqiantun", "mbweisi", "mbzhaoxiong"],
		names: "司马|昭",
		dieAudios: ["jsrg_simazhao"],
		groupBorder: "jin",
	},
	friend_cuijun: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["friendshunyi", "friendbiwei", "friendgongli_cuijun"],
	},
	friend_shitao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["friendqinying", "friendlunxiong", "friendgongli_shitao"],
	},
	pot_yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["potfuji", "potdaozhuan"],
	},
	pot_lougui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["potguansha", "potjiyu"],
	},
	mb_qinghegongzhu: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["mbzengou", "mbfeili"],
		names: "曹|null",
	},
	friend_pangtong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["friendmanjuan", "friendyangming", "friendpangtonggongli"],
	},
	friend_xushu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["friendxiaxing", "friendqihui", "friendxushugongli"],
	},
	friend_zhugeliang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["friendyance", "friendfangqiu", "friendzhugelianggongli"],
		names: "诸葛|亮",
	},
	pot_dongzhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["spmiaolve", "spyingjia"],
		img: "image/character/tw_dongzhao.jpg",
		dieAudios: ["tw_dongzhao"],
	},
	mb_xuezong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["mbfunan", "mbjiexun"],
		dieAudios: ["xuezong"],
	},
	pot_taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["pothanzhan", "potzhanlie", "potzhenfeng"],
		names: "太史|慈",
	},
	mb_ganfuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["mbzhijie", "mbshushen"],
		names: "甘|null",
	},
	mb_sp_zhenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["mbbojian", "mbjiwei"],
	},
	mb_zhangfen: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["mbquchong", "mbxunjie"],
	},
	mb_jiachong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["mbbeini", "mbdingfa"],
		groupBorder: "jin",
		dieAudios: ["jiachong"],
	},
	mb_simazhou: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbbifeng", "mbsuwang"],
		names: "司马|伷",
		groupBorder: "jin",
	},
	mb_wenqin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbbeiming", "mbchoumang"],
	},
	mb_simafu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbpanxiang", "mbchenjie"],
		names: "司马|孚",
		groupBorder: "jin",
	},
	mb_sp_guanqiujian: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbcuizhen", "mbkuili"],
		names: "毌丘|俭",
	},
	mb_caomao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbqianlong", "mbweitong"],
		isZhugong: true,
	},
	chengji: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbkuangli", "mbxiongsi"],
		groupBorder: "jin",
	},
	lizhaojiaobo: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbzuoyou", "mbshishou"],
		names: "李|昭-焦|伯",
	},
	yangfeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbxuetu", "mbweiming"],
	},
	xin_huojun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sidai", "jieyu"],
		dieAudios: ["tw_huojun"],
	},
	muludawang: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 1,
		skills: ["shoufa", "zhoulin", "yuxiang"],
		names: "null|null",
	},
	mb_chengui: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["guimou", "zhouxian"],
	},
	mb_huban: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbyilie"],
	},
	mb_xianglang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["naxue", "yijie"],
	},
	yanxiang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["kujian", "ruilian"],
		dieAudios: ["tw_yanxiang"],
	},
	mb_sunluyu: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["mbmeibu", "mbmumu"],
		dieAudios: ["sunluyu"],
	},
	xin_wuban: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinjintao"],
		clans: ["陈留吴氏"],
		img: "image/character/wuban.jpg",
		dieAudios: ["wuban"],
	},
	baoxin: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mutao", "yimou"],
		dieAudios: ["tw_baoxin"],
	},
	jiangji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twjichou", "jilun"],
		img: "image/character/tw_jiangji.jpg",
		dieAudios: ["tw_jiangji"],
	},
	liwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jiaohua"],
		dieAudios: ["tw_liwei"],
	},
	laimin: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["laishou", "luanqun"],
	},
	xin_guozhao: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["yichong", "wufei"],
	},
	xin_zhangyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinwurong", "shizhi"],
	},
	xin_sunliang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["xinzhizheng", "xinkuizhu", "xinlijun"],
		isZhugong: true,
		dieAudios: ["sunliang"],
	},
	re_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["retianxiang", "xinhongyan"],
		names: "桥|null",
	},
	shichangshi: {
		sex: "male",
		group: "qun",
		hp: 1,
		skills: ["mbdanggu", "mbmowang"],
		trashBin: ["sex:male_castrated"],
		names: "张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望",
	},
	re_zhangzhang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["rezhijian", "guzheng"],
		names: "张|昭-张|纮",
	},
	qianzhao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbshihe", "mbzhenfu"],
	},
	re_yanwen: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["reshuangxiong"],
		names: "颜|良-文|丑",
	},
	xin_zhoutai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["buqu", "new_fenji"],
		dieAudios: ["zhoutai"],
	},
	re_caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["reluoying", "rejiushi", "chengzhang"],
	},
	re_chenqun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["redingpin", "refaen"],
	},
	xin_caoxiu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qianju", "xinqingxi"],
	},
	xin_zhuhuan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["fenli", "xinpingkou"],
	},
	sp_pengyang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["spdaming", "spxiaoni"],
	},
	wangjun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["zhujian", "duansuo"],
		groupBorder: "jin",
	},
	xin_zhuzhi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sbanguo"],
	},
	xin_wuyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sbbenxi"],
	},
	yangfu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["jiebing", "hannan"],
	},
	sp_caosong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["yijin", "guanzong"],
	},
	re_liru: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rejuece", "remieji", "xinfencheng"],
	},
	re_dianwei: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["reqiangxi"],
	},
	xin_mamidi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["chengye", "buxu"],
	},
	ruanhui: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["mingcha", "jingzhong"],
	},
	xin_quancong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["sbyaoming"],
	},
	re_xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["quhu", "rejieming"],
		clans: ["颍川荀氏"],
	},
	xin_jushou: {
		sex: "male",
		group: "qun",
		hp: 2,
		maxHp: 3,
		hujia: 3,
		skills: ["xinjianying", "shibei"],
	},
	re_bulianshi: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["reanxu", "zhuiyi"],
	},
	re_caiwenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["rebeige", "duanchang"],
	},
	sp_jianggan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbdaoshu", "spdaizui"],
	},
	peixiu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xingtu", "juezhi"],
		groupBorder: "jin",
	},
	re_gaoshun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["rexianzhen", "rejinjiu"],
	},
	re_wuguotai: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["reganlu", "buyi"],
		names: "丁|null",
	},
	xin_sunxiu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["mobileyanzhu", "mobilexingxue", "zhaofu"],
		isZhugong: true,
	},
	sp_maojie: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["bingqing", "yingfeng"],
	},
	re_yufan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["zhiyan", "rezongxuan"],
	},
	sunhanhua: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["chongxu", "miaojian", "shhlianhua"],
	},
	yanpu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["twhuantu", "twbihuo"],
	},
	mayuanyi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jibing", "wangjing", "moucuan"],
	},
	fuqian: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jueyong", "poxiang"],
	},
	xin_caozhen: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbsidi"],
	},
	xin_sunluban: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["xinzenhui", "xinjiaojin"],
	},
	qiaozhou: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zhiming", "xingbu"],
	},
	xin_guyong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["xinshenxing", "xinbingyi"],
	},
	re_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["requanji", "zili"],
		clans: ["颍川钟氏"],
	},
	xin_caifuren: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["xinqieting", "xianzhou"],
		names: "蔡|null",
	},
	xin_zhoucang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mobilezhongyong"],
	},
	ol_yujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["rejieyue"],
		dieAudios: ["yujin_yujin.mp3"],
	},
	zhouqun: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["tiansuan"],
	},
	re_zhurong: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["juxiang", "relieren"],
		doubleGroup: ["shu", "qun"],
		names: "null|null",
	},
	re_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["retiaoxin", "zhiji"],
	},
	nanhualaoxian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["yufeng", "tianshu"],
		names: "庄|周",
	},
	re_handang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["regongji", "jiefan"],
	},
	re_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["retuntian", "zaoxian"],
	},
	xin_fuhuanghou: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["xinzhuikong", "xinqiuyuan"],
	},
	xin_panzhangmazhong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["xinduodao", "xinanjian"],
		names: "潘|璋-马|忠",
	},
	xin_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mobilejingce"],
	},
	gongsunkang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["juliao", "taomie"],
		names: "公孙|康",
	},
	xin_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["new_repaoxiao", "liyong"],
		dieAudios: ["re_zhangfei"],
	},
	xin_hansui: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 1,
		skills: ["xinniluan", "xiaoxi_hansui"],
		dieAudios: ["hansui"],
	},
	hucheer: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["daoji"],
	},
	re_lingtong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["rexuanfeng"],
	},
	re_liubiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zishou", "rezongshi"],
	},
	simashi: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["baiyi", "jinglve", "shanli"],
		names: "司马|师",
		groupBorder: "jin",
	},
	yanghuiyu: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["hongyi", "requanfeng"],
		groupBorder: "jin",
	},
	xin_zhuran: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["mobiledanshou"],
	},
	xin_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinyicong", "qiaomeng"],
		dieAudios: ["gongsunzan"],
		names: "公孙|瓒",
	},
	dingyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["beizhu"],
	},
	xin_jianyong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xinqiaoshui", "xinjyzongshi"],
	},
	xin_caozhang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["rejiangchi"],
	},
	xin_liaohua: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["redangxian", "refuli"],
	},
	furong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xuewei", "liechi"],
	},
	re_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 8,
		skills: ["rejiuchi", "roulin", "benghuai", "baonue"],
		isZhugong: true,
	},
	re_xusheng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["repojun"],
	},
	sp_sufei: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["zhengjian", "gaoyuan"],
	},
	re_sunjian: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["gzyinghun", "repolu"],
	},
	zhengxuan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zhengjing"],
	},
	dengzhi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jimeng", "shuaiyan"],
	},
	xin_chengpu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["relihuo", "chunlao"],
	},
	yangyi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["duoduan", "gongsun"],
	},
	dongcheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["chengzhao"],
	},
	re_pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xinlianhuan", "niepan"],
	},
	re_guanqiujian: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["rezhengrong", "rehongju"],
		names: "毌丘|俭",
		dieAudios: ["guanqiujian"],
	},
	chendeng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zhouxuan", "fengji"],
	},
	re_heqi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["reqizhou", "reshanxi"],
		dieAudios: ["heqi"],
	},
	yangbiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zhaohan", "rangjie", "yizheng"],
		clans: ["弘农杨氏"],
	},
	re_sp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["bazhen", "rehuoji", "rekanpo"],
		names: "诸葛|亮",
	},
	xin_xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["reganglie", "xinqingjian"],
		names: "夏侯|惇",
		dieAudios: ["re_xiahoudun"],
	},
	zhangyì: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rezhiyi"],
	},
	jiakui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["tongqu", "xinwanlan"],
	},
	re_jikang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["new_qingxian", "new_juexiang"],
		dieAudios: ["jikang"],
	},
	miheng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["kuangcai", "shejian"],
	},
	taoqian: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zhaohuo", "yixiang", "yirang"],
	},
	liuzan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["fenyin"],
	},
	lingcao: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dujin"],
	},
	sunru: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["yingjian", "shixin"],
	},
	lifeng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["tunchu", "shuliang"],
	},
	zhuling: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xinzhanyi"],
	},
	liuye: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["polu", "choulve"],
	},
	zhaotongzhaoguang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["yizan_use", "xinfu_longyuan"],
		names: "赵|统-赵|广",
	},
	majun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xinfu_jingxie", "qiaosi"],
	},
	simazhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xinfu_daigong", "xinfu_zhaoxin"],
		names: "司马|昭",
		groupBorder: "jin",
	},
	wangyuanji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["xinfu_qianchong", "xinfu_shangjian"],
		groupBorder: "jin",
	},
	pangdegong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinfu_pingcai", "xinfu_pdgyingshi"],
	},
	old_yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinyongsi", "yjixi"],
		dieAudios: ["yuanshu"],
	},
	zhangbu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["mbchengxiong", "mbwangzhuang"],
	},
	mb_wangjing: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbzujin", "mbjiejian"],
	},

	shenpei: {
		sex: "male",
		group: "qun",
		hp: 2,
		maxHp: 3,
		skills: ["shouye", "liezhi"],
	},
	re_wangyun: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["relianji", "remoucheng"],
		clans: ["太原王氏"],
		dieAudios: ["wangyun"],
	},

	re_baosanniang: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["meiyong", "rexushen", "rezhennan"],
		dieAudios: ["baosanniang"],
	},

	hujinding: {
		sex: "female",
		group: "shu",
		hp: 2,
		maxHp: 6,
		skills: ["renshi", "wuyuan", "huaizi"],
	},

	re_zhanggong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["reqianxin", "rezhenxing"],
		dieAudios: ["zhanggong"],
	},
	re_xugong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["rebiaozhao", "yechou"],
		doubleGroup: ["wu", "qun"],
		dieAudios: ["xugong"],
	},
	re_weiwenzhugezhi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["refuhai"],
		names: "卫|温-诸葛|直",
		dieAudios: ["weiwenzhugezhi"],
	},

	xin_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["reluanji", "xueyi"],
		isZhugong: true,
	},
	re_liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xiangle", "refangquan", "ruoyu"],
		isZhugong: true,
	},
	re_sunben: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jiang", "rehunzi", "zhiba"],
		isZhugong: true,
	},

	scs_zhangrang: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scstaoluan"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
	scs_zhaozhong: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scschiyan"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
	scs_sunzhang: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scszimou"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
	scs_bilan: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scspicai"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
	scs_xiayun: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scsyaozhuo"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
	scs_hankui: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scsxiaolu"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
	scs_lisong: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scskuiji"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
	scs_duangui: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scschihe"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
	scs_guosheng: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scsniqu"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
	scs_gaowang: {
		sex: "male",
		group: "qun",
		hp: 0,
		skills: ["scsmiaoyu"],
		isUnseen: true,
		trashBin: ["sex:male_castrated"],
	},
};

export default characters;
