const characters = {
	tw_zhenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["mbbojian", "twjiwei"],
		dieAudios: ["mb_sp_zhenji"],
	},
	tw_zhuzhi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twanguo"],
		dieAudios: ["xin_zhuzhi"],
	},
	huan_dianwei: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twmiewei", "twmiyong"],
	},
	huan_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twqianxiong", "twzhengshi"],
	},
	huan_caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twhanhong", "twhuazhang"],
	},
	tw_zhangyun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twhuiyu", "twbeixing"],
	},
	huan_caochong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twfushu", "twxiumu"],
	},
	tw_simashi: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["baiyi", "twjinglve", "shanli"],
		names: "司马|师",
		groupBorder: "jin",
		dieAudios: ["simashi"],
	},
	tw_sb_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twxingshang", "twfangzhu", "twsongwei"],
		isZhugong: true,
		dieAudios: ["sb_caopi"],
	},
	tw_sb_sp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["sbhuoji", "twkanpo"],
		names: "诸葛|亮",
		dieAudios: ["sb_sp_zhugeliang"],
	},
	huan_dingshangwan: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["twshiyi", "twchunhui"],
	},
	huan_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twfenxian", "twjuyan"],
	},
	huan_caoang: {
		sex: "male",
		group: "wei",
		hp: 2,
		maxHp: 3,
		skills: ["twchihui", "twfuxi"],
	},
	huan_liufeng: {
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 1,
		skills: ["twchenxun"],
	},
	tw_sunluban: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["twzenhui", "xinjiaojin"],
		dieAudios: ["xin_sunluban"],
	},
	tw_mazhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twfuman"],
		dieAudios: ["mazhong"],
	},
	tw_jsp_guanyu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["wusheng", "twdanji"],
		dieAudios: ["jsp_guanyu"],
		tempname: ["jsp_guanyu"],
	},
	tw_fuhuanghou: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["rezhuikong", "xinqiuyuan"],
		dieAudios: ["xin_fuhuanghou"],
	},
	tw_qiaozhou: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zhiming", "twxingbu"],
		dieAudios: ["qiaozhou"],
	},
	tw_yj_zhanghe: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["zhilve"],
		dieAudios: ["yj_zhanghe"],
	},
	old_jiakui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["zhongzuo", "wanlan"],
		dieAudios: ["jiakui"],
	},
	huan_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["twlifeng", "twniwo"],
		clans: ["吴郡陆氏"],
	},
	huan_liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["twguihan", "twrenxian", "twyanzuo"],
		isZhugong: true,
	},
	licuilianzhaoquanding: {
		sex: "double",
		group: "shu",
		hp: 3,
		skills: ["twciyin", "twchenglong"],
		names: "李|翠莲-赵|全定",
	},
	huan_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 4,
		skills: ["twbeiding", "twjielv", "twhunyou"],
		names: "诸葛|亮",
	},
	huan_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twqinghan", "twzhihuan"],
	},
	huan_zhugeguo: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["rexianyuan", "twlingyin"],
		names: "诸葛|果",
	},
	huan_zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twkuiduan"],
	},
	huan_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twjiezhan", "twlongjin"],
	},
	huan_simayi: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twzongquan", "twguimou"],
		names: "司马|懿",
		groupBorder: "ye",
	}, //if线司马懿成野心家了就给野心家border了
	huan_weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twqiji", "twpiankuang"],
	},
	tw_zhugejun: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["twshouzhu", "twdaigui", "twcairu"],
		names: "诸葛|均",
	},
	simafu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xunde", "chenjie"],
		names: "司马|孚",
		groupBorder: "jin",
	},
	tw_yanliang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twduwang", "twylyanshi"],
	},
	tw_wenchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twjuexing", "twxiayong"],
	},
	tw_yuantan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twqiaosi", "twbaizu"],
	},
	xia_yuzhenzi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["twhuajing", "twtianshou"],
	},
	xia_shie: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twdengjian", "twxinshou"],
	},
	xia_shitao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twjieqiu", "twenchou"],
	},
	xia_guanyu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twzhongyi", "twchue"],
	},
	xia_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twshenyi", "twxinghan"],
	},
	xia_xiahousone: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["twchengxi"],
		names: "夏侯|子萼",
	},
	xia_xiahoudun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twdanlie"],
		names: "夏侯|惇",
	},
	xia_zhangwei: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["twhuzhong", "twfenwang"],
	},
	tw_zhanghong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["twquanqian", "twrouke"],
	},
	tw_zhangzhao: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["twlijian", "twchungang"],
	},
	tw_gongsunfan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twhuiyuan", "twshoushou"],
		names: "公孙|范",
	},
	tw_yangang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twzhiqu", "twxianfeng"],
	},
	xia_xiahouzie: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 4,
		skills: ["twxuechang", "twduoren"],
		names: "夏侯|紫萼",
	},
	xia_zhaoe: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["twyanshi", "twrenchou"],
	},
	xia_lusu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twkaizeng", "twyangming"],
	},
	xia_dianwei: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twliexi", "twshezhong"],
	},
	tw_bingyuan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["twbingde", "twqingtao"],
	},
	tw_niufudongxie: {
		sex: "double",
		group: "qun",
		hp: 4,
		skills: ["twjuntun", "twxiongxi", "twxiafeng"],
		names: "牛|辅-董|翓",
	},
	tw_jianshuo: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["twkunsi"],
	},
	tw_jiangji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twjichou", "twjilun"],
	},
	tw_mateng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "twxiongzheng", "twluannian"],
		isZhugong: true,
	},
	tw_baoxin: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twmutao", "twyimou"],
	},
	tw_liufuren: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["twzhuidu", "twshigong"],
		names: "刘|null",
	},
	tw_yufuluo: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["twjiekuang", "twneirao"],
		names: "null|null",
	},
	tw_fengxí: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twqingkou"],
	},
	tw_zhangji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twdingzhen", "twyouye"],
	},
	tw_zhangnan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twfenwu"],
	},
	tw_huchuquan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twfupan"],
	},
	tw_liwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twjiaohua"],
	},
	tw_yanxiang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["twkujian", "twruilian"],
	},
	tw_xiahouen: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["twfujian", "twjianwei"],
		names: "夏侯|恩",
	},
	tw_xiahoushang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twtanfeng"],
		names: "夏侯|尚",
	},
	tw_qiaorui: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["twxiawei", "twqiongji"],
	},
	tw_haomeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twgongge"],
	},
	tw_weixu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twsuizheng", "twtuidao"],
	},
	xia_xushu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twjiange", "twxiawang"],
	},
	xia_wangyue: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twyulong", "twjianming"],
	},
	xia_liyàn: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twzhenhu", "twlvren"],
	},
	xia_tongyuan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twchaofeng", "twchuanshu"],
	},
	tw_zhangning: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["twxingzhui", "twjuchen"],
	},
	tw_yangyi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["duoduan", "twgongsun"],
		dieAudios: ["yangyi"],
	},
	tw_dengzhi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["twjimeng", "shuaiyan"],
		dieAudios: ["dengzhi"],
	},
	tw_wangling: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twmibei", "twxingqi"],
		clans: ["太原王氏"],
		dieAudios: ["wangling"],
	},
	tw_zhugeguo: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["twqirang", "twyuhua"],
		names: "诸葛|果",
		dieAudios: ["zhugeguo"],
	},
	tw_fanchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twxingluan"],
		dieAudios: ["fanchou"],
	},
	tw_xujing: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["twboming", "twejian"],
		dieAudios: ["sp_xujing"],
	},
	tw_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["new_repaoxiao", "twxuhe"],
		dieAudios: ["re_zhangfei"],
		tempname: ["re_zhangfei"],
	},
	tw_xuezong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["funan", "twjiexun"],
		dieAudios: ["xuezong"],
	},
	tw_xunchen: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["twweipo", "mjchenshi", "twmouzhi"],
		dieAudios: ["sp_xunchen"],
	},
	tw_jiangqing: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twshangyi", "twxiangyu"],
		dieAudios: ["sp_jiangqing"],
	},
	tw_guyong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["twgyshenxing", "twbingyi"],
		dieAudios: ["xin_guyong"],
	},
	tw_chendong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twyilie", "twfenming"],
		names: "陈|武-董|袭",
		dieAudios: ["chendong"],
	},
	tw_handang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twgongji", "twjiefan"],
		dieAudios: ["handang"],
	},
	tw_jiling: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twshuangren"],
		dieAudios: ["jiling"],
	},
	tw_re_fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["twxuanhuo", "twenyuan"],
		dieAudios: ["fazheng"],
	},
	tw_madai: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "twqianxi"],
		dieAudios: ["old_madai"],
	},
	tw_niujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twcuorui", "twliewei"],
		dieAudios: ["niujin"],
	},
	tw_guanqiujian: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twzhengrong", "twhongju"],
		names: "毌丘|俭",
		dieAudios: ["guanqiujian"],
	},
	tw_daxiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["twxingwu", "twpingting"],
		tempname: ["daxiaoqiao"],
		names: "桥|null-桥|null",
		dieAudios: ["daxiaoqiao"],
	},
	tw_furong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twxuewei", "twliechi"],
		dieAudios: ["furong"],
	},
	tw_yl_luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["twmingren", "twzhenliang"],
		dieAudios: ["yl_luzhi"],
	},
	tw_liuzhang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jutu", "twyaohu", "rehuaibi"],
		isZhugong: true,
		dieAudios: ["liuzhang"],
	},
	tw_zongyu: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["twzhibian", "twyuyan"],
		dieAudios: ["sp_zongyu"],
	},
	tw_zhouchu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twguoyi", "twchuhai"],
		dieAudios: ["zhouchu"],
	},
	tw_qiaogong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["twyizhu", "twluanchou"],
		names: "桥|null",
		dieAudios: ["qiaogong"],
	},
	tw_feiyi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["twshengxi", "twkuanji"],
		dieAudios: ["feiyi"],
	},
	tw_bianfuren: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["twwanwei", "twyuejian"],
		names: "卞|null",
		dieAudios: ["sp_bianfuren"],
	},
	tw_chenzhen: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["twmuyue", "twchayi"],
		dieAudios: ["sp_chenzhen"],
	},
	tw_caoxiu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twqianju", "twqingxi"],
		dieAudios: ["xin_caoxiu"],
	},
	tw_sunyi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twzaoli"],
		dieAudios: ["sunyi"],
	},
	tw_puyangxing: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twzhengjian", "twzhongchi"],
		names: "濮阳|兴",
	},
	tw_tianyu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twzhenxi", "twyangshi"],
	},
	old_quancong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["zhenshan"],
	},
	tw_wujing: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twfenghan", "twcongji"],
		dieAudios: ["wujing"],
	},
	tw_wangcan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twdianyi", "twyingji", "twshanghe"],
	},
	tw_wangchang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twkaiji", "twshepan"],
		clans: ["太原王氏"],
	},
	tw_caozhao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twfuzuan", "twchongqi", "twfeifu"],
	},
	tw_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twjingce", "yuzhang"],
		dieAudios: ["guohuai"],
	},
	tw_chengpu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twlihuo", "twchunlao"],
		dieAudios: ["chengpu"],
	},
	tw_zhangmancheng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twfengji", "twyiju", "twbudao"],
	},
	tw_caocao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twlingfa"],
	},
	tw_liuhong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twyujue", "twgezhi", "twfengqi"],
		isZhugong: true,
	},
	tw_huojun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twsidai", "twjieyu"],
	},
	tw_zangba: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twhanyu", "twhengjiang"],
		dieAudios: ["zangba"],
	},
	tw_re_caohong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twyuanhu", "twjuezhu"],
		dieAudios: ["caohong"],
	},
	tw_mayunlu: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["mashu", "twfengpo"],
		dieAudios: ["mayunlu"],
	},
	tw_hejin: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twmouzhu", "twyanhuo"],
		dieAudios: ["hejin"],
	},
	tw_hucheer: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twshenxing", "twdaoji"],
		dieAudios: ["hucheer"],
	},
	tw_yujin: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xinzhenjun"],
	},
	tw_fuwan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twmoukui"],
		dieAudios: ["fuwan"],
	},
	tw_zhaoxiang: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["refanghun", "twfuhan", "twqueshi"],
		dieAudios: ["zhaoxiang"],
	},
	yuejiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["cuijin"],
	},
	wuban: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jintao"],
		clans: ["陈留吴氏"],
	},
	duosidawang: {
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 5,
		skills: ["equan", "manji"],
		names: "null|null",
	},
	jiachong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["beini", "dingfa"],
		groupBorder: "jin",
	},
	tw_dongzhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["twmiaolve", "twyingjia"],
	},
	tw_gexuan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["twdanfa", "twlingbao", "twsidao"],
	},
	tw_beimihu: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["zongkui", "guju", "baijia", "bingzhao"],
		isZhugong: true,
		names: "null|null",
	},
	nashime: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["chijie", "waishi", "renshe"],
		names: "null|null",
	},
	tw_xiahouba: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["twyanqin", "twbaobian"],
		names: "夏侯|霸",
	},
	tw_zumao: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twtijin"],
	},
	tw_caoang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twxiaolian"],
	},
	tw_dingfeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["twqijia", "twzhuchen"],
	},
	tw_caohong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["twhuzhu", "twliancai"],
	},
	tw_maliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["twrangyi", "twbaimei"],
	},
	kaisa: {
		sex: "male",
		group: "western",
		hp: 4,
		skills: ["zhengfu"],
		names: "尤利乌斯|盖乌斯",
	},
};

export default characters;
