const characters = {
	clan_luji: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["clangailan", "clanfennu", "clanzelie"],
		clans: ["吴郡陆氏"],
	},
	clan_lujing: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["clantanfeng", "clanjuewei", "clanzelie"],
		clans: ["吴郡陆氏"],
	},
	clan_yangbiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["clanjiannan", "clanyichi", "clanquhuo"],
		clans: ["弘农杨氏"],
	},
	clan_wuyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["clangaojin", "clanmuyin"],
		clans: ["陈留吴氏"],
	},
	clan_wuxian: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["clanyirong", "clanguixiang", "clanmuyin"],
		clans: ["陈留吴氏"],
	},
	clan_wuban: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["clanzhanding", "clanmuyin"],
		clans: ["陈留吴氏"],
	},
	clan_xunshu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["clanshenjun", "clanbalong", "clandaojie"],
		clans: ["颍川荀氏"],
	},
	clan_xunchen: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["clansankuang", "clanbeishi", "clandaojie"],
		clans: ["颍川荀氏"],
	},
	clan_xuncai: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["clanlieshi", "clandianzhan", "clanhuanyin", "clandaojie"],
		clans: ["颍川荀氏"],
	},
	clan_xuncan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["clanyunshen", "clanshangshen", "clanfenchai", "clandaojie"],
		clans: ["颍川荀氏"],
	},
	clan_hanshao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["clanfangzhen", "clanliuju", "clanxumin"],
		clans: ["颍川韩氏"],
	},
	clan_hanrong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["clanlianhe", "clanhuanjia", "clanxumin"],
		clans: ["颍川韩氏"],
	},
	clan_wukuang: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["clanlianzhu", "clanmuyin"],
		clans: ["陈留吴氏"],
	},
	clan_wangling: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["clanbolong", "clanzhongliu"],
		clans: ["太原王氏"],
	},
	clan_zhongyan: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["clanguangu", "clanxiaoyong", "clanbaozu"],
		clans: ["颍川钟氏"],
	},
	clan_wangyun: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["clanjiexuan", "clanmingjie", "clanzhongliu"],
		clans: ["太原王氏"],
	},
	clan_wanghun: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["clanfuxun", "clanchenya", "clanzhongliu"],
		clans: ["太原王氏"],
	},
	clan_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 4,
		skills: ["clanyuzhi", "clanxieshu", "clanbaozu"],
		clans: ["颍川钟氏"],
		dieAudios: ["3"],
	},
	clan_zhongyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["clanjiejian", "clanhuanghan", "clanbaozu"],
		clans: ["颍川钟氏"],
	},
	clan_wanglun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["clanqiuxin", "clanjianyuan", "clanzhongliu"],
		clans: ["太原王氏"],
		groupBorder: "jin",
	},
	clan_xunyou: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["clanbaichu", "clandaojie"],
		clans: ["颍川荀氏"],
	},
	clan_wuqiao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["clanqiajue", "clanmuyin"],
		clans: ["陈留吴氏"],
		groupBorder: "jin",
	},
	clan_wangguang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["clanlilun", "clanjianji", "clanzhongliu"],
		clans: ["太原王氏"],
	},
	clan_wangmingshan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["clantanque", "clanshengmo", "clanzhongliu"],
		clans: ["太原王氏"],
	},
	clan_zhongyao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["clanchengqi", "clanjieli", "clanbaozu"],
		clans: ["颍川钟氏"],
	},
	clan_wangchang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["clankaiji", "clanzhongliu"],
		clans: ["太原王氏"],
	},
	clan_wangshen: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["clananran", "clangaobian", "clanzhongliu"],
		clans: ["太原王氏"],
	},
	clan_yangci: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["clanqieyi", "clanjianzhi", "clanquhuo"],
		clans: ["弘农杨氏"],
	},
	clan_yangxiu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["clanjiewu", "clangaoshi", "clanquhuo"],
		clans: ["弘农杨氏"],
	},
	clan_xunshuang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["clanyangji", "clandandao", "clanqingli", "clandaojie"],
		clans: ["颍川荀氏"],
	},
	clan_yangzhong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["clanjuetu", "clankudu", "clanquhuo"],
		clans: ["弘农杨氏"],
	},
};

export default characters;
