const characters = {
	re_huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinliegong"],
	},
	old_zhoutai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["gzbuqu"],
	},
	old_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jushou"],
		dieAudios: ["new_caoren"],
	},
	re_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["duanliang", "jiezi"],
	},
	re_pangde: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "jianchu"],
	},
	re_xiahouyuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["xinshensu"],
		names: "夏侯|渊",
	},
	re_weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["xinkuanggu", "qimou"],
	},
	xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["retianxiang", "hongyan"],
		names: "桥|null",
	},
	sp_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["releiji", "guidao", "huangtian"],
		isZhugong: true,
	},
	re_yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xinfu_guhuo"],
	},

	sp_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["bazhen", "huoji", "kanpo"],
		names: "诸葛|亮",
	},
	pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["lianhuan", "oldniepan"],
	},
	xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["quhu", "jieming"],
		clans: ["颍川荀氏"],
	},
	dianwei: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qiangxix"],
	},
	taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["tianyi"],
		names: "太史|慈",
	},
	yanwen: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["shuangxiong"],
		names: "颜|良-文|丑",
	},
	re_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["luanji", "xueyi"],
		isZhugong: true,
		dieAudios: ["yuanshao"],
	},

	menghuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["huoshou", "zaiqixx", "twqiushou"],
		isZhugong: true,
		doubleGroup: ["shu", "qun"],
	},
	zhurong: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["juxiang", "lieren"],
		doubleGroup: ["shu", "qun"],
		names: "null|null",
	},
	caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["xingshang", "fangzhu", "songwei"],
		isZhugong: true,
	},
	re_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["haoshi", "dimeng"],
	},
	sunjian: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["gzyinghun"],
	},
	dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 8,
		skills: ["jiuchi", "roulin", "benghuai", "baonue"],
		isZhugong: true,
	},
	jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["luanwu", "wansha", "weimu"],
	},

	jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["tiaoxin", "zhiji"],
	},
	liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xiangle", "fangquan", "ruoyu"],
		isZhugong: true,
	},
	zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qiaobian"],
	},
	dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["tuntian", "zaoxian"],
	},
	sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jiang", "hunzi", "zhiba"],
		isZhugong: true,
	},
	zhangzhang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["zhijian", "guzheng"],
		names: "张|昭-张|纮",
	},
	caiwenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["beige", "duanchang"],
	},
	zuoci: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["huashen", "xinsheng"],
	},

	wangji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qizhi", "jinqu"],
	},
	yanyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["nzry_juzhan"],
	},
	wangping: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["nzry_feijun", "nzry_binglve"],
	},
	luji: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["nzry_huaiju", "nzry_yili", "nzry_zhenglun"],
		clans: ["吴郡陆氏"],
	},
	sunliang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["nzry_kuizhu", "nzry_zhizheng", "nzry_lijun"],
		isZhugong: true,
	},
	xuyou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nzry_chenglve", "nzry_shicai", "nzry_cunmu"],
	},
	yl_luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["nzry_mingren", "nzry_zhenliang"],
	},
	kuailiangkuaiyue: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["nzry_jianxiang", "nzry_shenshi"],
		names: "蒯|良-蒯|越",
	},

	guanqiujian: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zhengrong", "hongju"],
		names: "毌丘|俭",
	},
	haozhao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["drlt_zhengu"],
	},
	zhugezhan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xinfu_zuilun", "xinfu_fuyin"],
		names: "诸葛|瞻",
	},
	lukang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["drlt_qianjie", "drlt_jueyan", "drlt_poshi"],
		clans: ["吴郡陆氏"],
	},
	yl_yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["drlt_yongsi", "drlt_weidi"],
		isZhugong: true,
	},
	zhangxiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["drlt_xiongluan", "drlt_congjian", "twjuxiang"],
		isZhugong: true,
	},
	chendao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcwanglie"],
	},
	zhoufei: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["olliangyin", "olkongsheng"],
		names: "周|null",
	},
};

export default characters;
